/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AchievementSetClaimsIndex200Response,
  AchievementsIndex400Response,
} from '../models/index';
import {
    AchievementSetClaimsIndex200ResponseFromJSON,
    AchievementSetClaimsIndex200ResponseToJSON,
    AchievementsIndex400ResponseFromJSON,
    AchievementsIndex400ResponseToJSON,
} from '../models/index';

export interface AchievementSetClaimsIndexRequest {
    pageSize?: number;
    pageNumber?: number;
    sort?: Array<AchievementSetClaimsIndexSortEnum>;
    filterId?: Array<string>;
    filterGameId?: string;
    filterStatus?: string;
    filterClaimType?: string;
    filterSetType?: string;
    filterSpecialType?: string;
    filterExpired?: string;
    filterUser?: string;
    fieldsAchievementSetClaims?: Array<AchievementSetClaimsIndexFieldsAchievementSetClaimsEnum>;
    fieldsUsers?: Array<AchievementSetClaimsIndexFieldsUsersEnum>;
    fieldsGames?: Array<AchievementSetClaimsIndexFieldsGamesEnum>;
    include?: Array<AchievementSetClaimsIndexIncludeEnum>;
}

/**
 * 
 */
export class AchievementSetClaimsApi extends runtime.BaseAPI {

    /**
     * 
     * Get all achievement-set-claims
     */
    async achievementSetClaimsIndexRaw(requestParameters: AchievementSetClaimsIndexRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AchievementSetClaimsIndex200Response>> {
        const queryParameters: any = {};

        if (requestParameters['pageSize'] != null) {
            queryParameters['page[size]'] = requestParameters['pageSize'];
        }

        if (requestParameters['pageNumber'] != null) {
            queryParameters['page[number]'] = requestParameters['pageNumber'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['filterId'] != null) {
            queryParameters['filter[id][]'] = requestParameters['filterId'];
        }

        if (requestParameters['filterGameId'] != null) {
            queryParameters['filter[gameId]'] = requestParameters['filterGameId'];
        }

        if (requestParameters['filterStatus'] != null) {
            queryParameters['filter[status]'] = requestParameters['filterStatus'];
        }

        if (requestParameters['filterClaimType'] != null) {
            queryParameters['filter[claimType]'] = requestParameters['filterClaimType'];
        }

        if (requestParameters['filterSetType'] != null) {
            queryParameters['filter[setType]'] = requestParameters['filterSetType'];
        }

        if (requestParameters['filterSpecialType'] != null) {
            queryParameters['filter[specialType]'] = requestParameters['filterSpecialType'];
        }

        if (requestParameters['filterExpired'] != null) {
            queryParameters['filter[expired]'] = requestParameters['filterExpired'];
        }

        if (requestParameters['filterUser'] != null) {
            queryParameters['filter[user]'] = requestParameters['filterUser'];
        }

        if (requestParameters['fieldsAchievementSetClaims'] != null) {
            queryParameters['fields[achievement-set-claims]'] = requestParameters['fieldsAchievementSetClaims']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['fieldsUsers'] != null) {
            queryParameters['fields[users]'] = requestParameters['fieldsUsers']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['fieldsGames'] != null) {
            queryParameters['fields[games]'] = requestParameters['fieldsGames']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['include'] != null) {
            queryParameters['include'] = requestParameters['include']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/achievement-set-claims`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AchievementSetClaimsIndex200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Get all achievement-set-claims
     */
    async achievementSetClaimsIndex(requestParameters: AchievementSetClaimsIndexRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AchievementSetClaimsIndex200Response> {
        const response = await this.achievementSetClaimsIndexRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const AchievementSetClaimsIndexSortEnum = {
    Id: 'id',
    Id2: '-id',
    ClaimedAt: 'claimedAt',
    ClaimedAt2: '-claimedAt',
    FinishedAt: 'finishedAt',
    FinishedAt2: '-finishedAt',
    UpdatedAt: 'updatedAt',
    UpdatedAt2: '-updatedAt',
    Status: 'status',
    Status2: '-status',
    ClaimType: 'claimType',
    ClaimType2: '-claimType',
    SetType: 'setType',
    SetType2: '-setType',
    SpecialType: 'specialType',
    SpecialType2: '-specialType',
    ExtensionsCount: 'extensionsCount',
    ExtensionsCount2: '-extensionsCount',
    GameTitle: 'gameTitle',
    GameTitle2: '-gameTitle',
    UserDisplayName: 'userDisplayName',
    UserDisplayName2: '-userDisplayName'
} as const;
export type AchievementSetClaimsIndexSortEnum = typeof AchievementSetClaimsIndexSortEnum[keyof typeof AchievementSetClaimsIndexSortEnum];
/**
 * @export
 */
export const AchievementSetClaimsIndexFieldsAchievementSetClaimsEnum = {
    ClaimedAt: 'claimedAt',
    FinishedAt: 'finishedAt',
    UpdatedAt: 'updatedAt',
    Status: 'status',
    ClaimType: 'claimType',
    SetType: 'setType',
    SpecialType: 'specialType',
    ExtensionsCount: 'extensionsCount',
    MinutesLeft: 'minutesLeft',
    UserId: 'userId',
    UserDisplayName: 'userDisplayName',
    GameId: 'gameId',
    GameTitle: 'gameTitle',
    GameIconUrl: 'gameIconUrl',
    SystemId: 'systemId',
    SystemName: 'systemName',
    User: 'user',
    Game: 'game'
} as const;
export type AchievementSetClaimsIndexFieldsAchievementSetClaimsEnum = typeof AchievementSetClaimsIndexFieldsAchievementSetClaimsEnum[keyof typeof AchievementSetClaimsIndexFieldsAchievementSetClaimsEnum];
/**
 * @export
 */
export const AchievementSetClaimsIndexFieldsUsersEnum = {
    DisplayName: 'displayName',
    AvatarUrl: 'avatarUrl',
    Motto: 'motto',
    Points: 'points',
    PointsHardcore: 'pointsHardcore',
    PointsWeighted: 'pointsWeighted',
    YieldUnlocks: 'yieldUnlocks',
    YieldPoints: 'yieldPoints',
    JoinedAt: 'joinedAt',
    LastActivityAt: 'lastActivityAt',
    DeletedAt: 'deletedAt',
    IsUnranked: 'isUnranked',
    IsUserWallActive: 'isUserWallActive',
    RichPresence: 'richPresence',
    RichPresenceUpdatedAt: 'richPresenceUpdatedAt',
    VisibleRole: 'visibleRole',
    DisplayableRoles: 'displayableRoles',
    AchievementSetClaims: 'achievementSetClaims',
    PlayerAchievements: 'playerAchievements',
    PlayerAchievementSets: 'playerAchievementSets',
    PlayerGames: 'playerGames',
    Tickets: 'tickets',
    WallComments: 'wallComments',
    Awards: 'awards',
    Followers: 'followers',
    Following: 'following'
} as const;
export type AchievementSetClaimsIndexFieldsUsersEnum = typeof AchievementSetClaimsIndexFieldsUsersEnum[keyof typeof AchievementSetClaimsIndexFieldsUsersEnum];
/**
 * @export
 */
export const AchievementSetClaimsIndexFieldsGamesEnum = {
    Title: 'title',
    SortTitle: 'sortTitle',
    BadgeUrl: 'badgeUrl',
    ImageBoxArtUrl: 'imageBoxArtUrl',
    ImageTitleUrl: 'imageTitleUrl',
    ImageIngameUrl: 'imageIngameUrl',
    ReleasedAt: 'releasedAt',
    ReleasedAtGranularity: 'releasedAtGranularity',
    PlayersTotal: 'playersTotal',
    PlayersHardcore: 'playersHardcore',
    AchievementsPublished: 'achievementsPublished',
    AchievementsUnpublished: 'achievementsUnpublished',
    PointsTotal: 'pointsTotal',
    PointsWeighted: 'pointsWeighted',
    TimesBeaten: 'timesBeaten',
    TimesBeatenHardcore: 'timesBeatenHardcore',
    MedianTimeToBeatMinutes: 'medianTimeToBeatMinutes',
    MedianTimeToBeatHardcoreMinutes: 'medianTimeToBeatHardcoreMinutes',
    System: 'system',
    AchievementSets: 'achievementSets',
    AchievementSetClaims: 'achievementSetClaims',
    Comments: 'comments',
    Hashes: 'hashes',
    Tickets: 'tickets'
} as const;
export type AchievementSetClaimsIndexFieldsGamesEnum = typeof AchievementSetClaimsIndexFieldsGamesEnum[keyof typeof AchievementSetClaimsIndexFieldsGamesEnum];
/**
 * @export
 */
export const AchievementSetClaimsIndexIncludeEnum = {
    User: 'user',
    Game: 'game'
} as const;
export type AchievementSetClaimsIndexIncludeEnum = typeof AchievementSetClaimsIndexIncludeEnum[keyof typeof AchievementSetClaimsIndexIncludeEnum];
