/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AchievementSetsAchievementSetVersions200Response,
  AchievementSetsAchievementSetVersionsShow200Response,
  AchievementSetsShow200Response,
  AchievementsIndex400Response,
} from '../models/index';
import {
    AchievementSetsAchievementSetVersions200ResponseFromJSON,
    AchievementSetsAchievementSetVersions200ResponseToJSON,
    AchievementSetsAchievementSetVersionsShow200ResponseFromJSON,
    AchievementSetsAchievementSetVersionsShow200ResponseToJSON,
    AchievementSetsShow200ResponseFromJSON,
    AchievementSetsShow200ResponseToJSON,
    AchievementsIndex400ResponseFromJSON,
    AchievementsIndex400ResponseToJSON,
} from '../models/index';

export interface AchievementSetsAchievementSetVersionsRequest {
    achievementSet: string;
}

export interface AchievementSetsAchievementSetVersionsShowRequest {
    achievementSet: string;
}

export interface AchievementSetsShowRequest {
    achievementSet: string;
}

/**
 * 
 */
export class AchievementSetsApi extends runtime.BaseAPI {

    /**
     * 
     * Show achievementSetVersions
     */
    async achievementSetsAchievementSetVersionsRaw(requestParameters: AchievementSetsAchievementSetVersionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AchievementSetsAchievementSetVersions200Response>> {
        if (requestParameters['achievementSet'] == null) {
            throw new runtime.RequiredError(
                'achievementSet',
                'Required parameter "achievementSet" was null or undefined when calling achievementSetsAchievementSetVersions().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/achievement-sets/{achievement_set}/achievement-set-versions`.replace(`{${"achievement_set"}}`, encodeURIComponent(String(requestParameters['achievementSet']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AchievementSetsAchievementSetVersions200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Show achievementSetVersions
     */
    async achievementSetsAchievementSetVersions(requestParameters: AchievementSetsAchievementSetVersionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AchievementSetsAchievementSetVersions200Response> {
        const response = await this.achievementSetsAchievementSetVersionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * Show achievementSetVersions relation
     */
    async achievementSetsAchievementSetVersionsShowRaw(requestParameters: AchievementSetsAchievementSetVersionsShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AchievementSetsAchievementSetVersionsShow200Response>> {
        if (requestParameters['achievementSet'] == null) {
            throw new runtime.RequiredError(
                'achievementSet',
                'Required parameter "achievementSet" was null or undefined when calling achievementSetsAchievementSetVersionsShow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/achievement-sets/{achievement_set}/relationships/achievement-set-versions`.replace(`{${"achievement_set"}}`, encodeURIComponent(String(requestParameters['achievementSet']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AchievementSetsAchievementSetVersionsShow200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Show achievementSetVersions relation
     */
    async achievementSetsAchievementSetVersionsShow(requestParameters: AchievementSetsAchievementSetVersionsShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AchievementSetsAchievementSetVersionsShow200Response> {
        const response = await this.achievementSetsAchievementSetVersionsShowRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * Show one achievement-set
     */
    async achievementSetsShowRaw(requestParameters: AchievementSetsShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AchievementSetsShow200Response>> {
        if (requestParameters['achievementSet'] == null) {
            throw new runtime.RequiredError(
                'achievementSet',
                'Required parameter "achievementSet" was null or undefined when calling achievementSetsShow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/achievement-sets/{achievement_set}`.replace(`{${"achievement_set"}}`, encodeURIComponent(String(requestParameters['achievementSet']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AchievementSetsShow200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Show one achievement-set
     */
    async achievementSetsShow(requestParameters: AchievementSetsShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AchievementSetsShow200Response> {
        const response = await this.achievementSetsShowRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
