/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AchievementsIndex400Response,
  EventsIndex200Response,
  EventsShow200Response,
} from '../models/index';
import {
    AchievementsIndex400ResponseFromJSON,
    AchievementsIndex400ResponseToJSON,
    EventsIndex200ResponseFromJSON,
    EventsIndex200ResponseToJSON,
    EventsShow200ResponseFromJSON,
    EventsShow200ResponseToJSON,
} from '../models/index';

export interface EventsIndexRequest {
    pageSize?: number;
    pageNumber?: number;
    sort?: Array<EventsIndexSortEnum>;
    filterId?: Array<string>;
    fieldsEvents?: Array<EventsIndexFieldsEventsEnum>;
    fieldsEventAwards?: Array<EventsIndexFieldsEventAwardsEnum>;
    include?: Array<EventsIndexIncludeEnum>;
}

export interface EventsShowRequest {
    event: string;
}

/**
 * 
 */
export class EventsApi extends runtime.BaseAPI {

    /**
     * 
     * Get all events
     */
    async eventsIndexRaw(requestParameters: EventsIndexRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EventsIndex200Response>> {
        const queryParameters: any = {};

        if (requestParameters['pageSize'] != null) {
            queryParameters['page[size]'] = requestParameters['pageSize'];
        }

        if (requestParameters['pageNumber'] != null) {
            queryParameters['page[number]'] = requestParameters['pageNumber'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['filterId'] != null) {
            queryParameters['filter[id][]'] = requestParameters['filterId'];
        }

        if (requestParameters['fieldsEvents'] != null) {
            queryParameters['fields[events]'] = requestParameters['fieldsEvents']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['fieldsEventAwards'] != null) {
            queryParameters['fields[event-awards]'] = requestParameters['fieldsEventAwards']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['include'] != null) {
            queryParameters['include'] = requestParameters['include']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/events`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EventsIndex200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Get all events
     */
    async eventsIndex(requestParameters: EventsIndexRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EventsIndex200Response> {
        const response = await this.eventsIndexRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * Show one event
     */
    async eventsShowRaw(requestParameters: EventsShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EventsShow200Response>> {
        if (requestParameters['event'] == null) {
            throw new runtime.RequiredError(
                'event',
                'Required parameter "event" was null or undefined when calling eventsShow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/events/{event}`.replace(`{${"event"}}`, encodeURIComponent(String(requestParameters['event']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EventsShow200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Show one event
     */
    async eventsShow(requestParameters: EventsShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EventsShow200Response> {
        const response = await this.eventsShowRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const EventsIndexSortEnum = {
    Id: 'id',
    Id2: '-id',
    Title: 'title',
    Title2: '-title',
    SortTitle: 'sortTitle',
    SortTitle2: '-sortTitle',
    ActiveFrom: 'activeFrom',
    ActiveFrom2: '-activeFrom'
} as const;
export type EventsIndexSortEnum = typeof EventsIndexSortEnum[keyof typeof EventsIndexSortEnum];
/**
 * @export
 */
export const EventsIndexFieldsEventsEnum = {
    Title: 'title',
    SortTitle: 'sortTitle',
    BadgeUrl: 'badgeUrl',
    State: 'state',
    PlayersTotal: 'playersTotal',
    AchievementsPublished: 'achievementsPublished',
    ActiveFrom: 'activeFrom',
    ActiveThrough: 'activeThrough',
    Awards: 'awards'
} as const;
export type EventsIndexFieldsEventsEnum = typeof EventsIndexFieldsEventsEnum[keyof typeof EventsIndexFieldsEventsEnum];
/**
 * @export
 */
export const EventsIndexFieldsEventAwardsEnum = {
    TierIndex: 'tierIndex',
    Label: 'label',
    PointsRequired: 'pointsRequired',
    BadgeUrl: 'badgeUrl',
    Event: 'event'
} as const;
export type EventsIndexFieldsEventAwardsEnum = typeof EventsIndexFieldsEventAwardsEnum[keyof typeof EventsIndexFieldsEventAwardsEnum];
/**
 * @export
 */
export const EventsIndexIncludeEnum = {
    Awards: 'awards'
} as const;
export type EventsIndexIncludeEnum = typeof EventsIndexIncludeEnum[keyof typeof EventsIndexIncludeEnum];
