/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AchievementsComments200Response,
  AchievementsIndex400Response,
  AchievementsTickets200Response,
  GamesAchievementSetClaims200Response,
  GamesAchievementSetClaimsShow200Response,
  GamesCommentsShow200Response,
  GamesHashes200Response,
  GamesHashesShow200Response,
  GamesIndex200Response,
  GamesShow200Response,
  GamesTicketsShow200Response,
} from '../models/index';
import {
    AchievementsComments200ResponseFromJSON,
    AchievementsComments200ResponseToJSON,
    AchievementsIndex400ResponseFromJSON,
    AchievementsIndex400ResponseToJSON,
    AchievementsTickets200ResponseFromJSON,
    AchievementsTickets200ResponseToJSON,
    GamesAchievementSetClaims200ResponseFromJSON,
    GamesAchievementSetClaims200ResponseToJSON,
    GamesAchievementSetClaimsShow200ResponseFromJSON,
    GamesAchievementSetClaimsShow200ResponseToJSON,
    GamesCommentsShow200ResponseFromJSON,
    GamesCommentsShow200ResponseToJSON,
    GamesHashes200ResponseFromJSON,
    GamesHashes200ResponseToJSON,
    GamesHashesShow200ResponseFromJSON,
    GamesHashesShow200ResponseToJSON,
    GamesIndex200ResponseFromJSON,
    GamesIndex200ResponseToJSON,
    GamesShow200ResponseFromJSON,
    GamesShow200ResponseToJSON,
    GamesTicketsShow200ResponseFromJSON,
    GamesTicketsShow200ResponseToJSON,
} from '../models/index';

export interface GamesAchievementSetClaimsRequest {
    game: string;
}

export interface GamesAchievementSetClaimsShowRequest {
    game: string;
}

export interface GamesCommentsRequest {
    game: string;
}

export interface GamesCommentsShowRequest {
    game: string;
}

export interface GamesHashesRequest {
    game: string;
}

export interface GamesHashesShowRequest {
    game: string;
}

export interface GamesIndexRequest {
    pageSize?: number;
    pageNumber?: number;
    sort?: Array<GamesIndexSortEnum>;
    filterId?: Array<string>;
    filterSystemId?: string;
    fieldsGames?: Array<GamesIndexFieldsGamesEnum>;
    fieldsSystems?: Array<GamesIndexFieldsSystemsEnum>;
    fieldsAchievementSets?: Array<GamesIndexFieldsAchievementSetsEnum>;
    fieldsGameHashes?: Array<GamesIndexFieldsGameHashesEnum>;
    include?: Array<GamesIndexIncludeEnum>;
}

export interface GamesShowRequest {
    game: string;
}

export interface GamesTicketsRequest {
    game: string;
}

export interface GamesTicketsShowRequest {
    game: string;
}

/**
 * 
 */
export class GamesApi extends runtime.BaseAPI {

    /**
     * 
     * Show achievementSetClaims
     */
    async gamesAchievementSetClaimsRaw(requestParameters: GamesAchievementSetClaimsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GamesAchievementSetClaims200Response>> {
        if (requestParameters['game'] == null) {
            throw new runtime.RequiredError(
                'game',
                'Required parameter "game" was null or undefined when calling gamesAchievementSetClaims().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/games/{game}/achievement-set-claims`.replace(`{${"game"}}`, encodeURIComponent(String(requestParameters['game']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GamesAchievementSetClaims200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Show achievementSetClaims
     */
    async gamesAchievementSetClaims(requestParameters: GamesAchievementSetClaimsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GamesAchievementSetClaims200Response> {
        const response = await this.gamesAchievementSetClaimsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * Show achievementSetClaims relation
     */
    async gamesAchievementSetClaimsShowRaw(requestParameters: GamesAchievementSetClaimsShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GamesAchievementSetClaimsShow200Response>> {
        if (requestParameters['game'] == null) {
            throw new runtime.RequiredError(
                'game',
                'Required parameter "game" was null or undefined when calling gamesAchievementSetClaimsShow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/games/{game}/relationships/achievement-set-claims`.replace(`{${"game"}}`, encodeURIComponent(String(requestParameters['game']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GamesAchievementSetClaimsShow200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Show achievementSetClaims relation
     */
    async gamesAchievementSetClaimsShow(requestParameters: GamesAchievementSetClaimsShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GamesAchievementSetClaimsShow200Response> {
        const response = await this.gamesAchievementSetClaimsShowRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * Show comments
     */
    async gamesCommentsRaw(requestParameters: GamesCommentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AchievementsComments200Response>> {
        if (requestParameters['game'] == null) {
            throw new runtime.RequiredError(
                'game',
                'Required parameter "game" was null or undefined when calling gamesComments().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/games/{game}/comments`.replace(`{${"game"}}`, encodeURIComponent(String(requestParameters['game']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AchievementsComments200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Show comments
     */
    async gamesComments(requestParameters: GamesCommentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AchievementsComments200Response> {
        const response = await this.gamesCommentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * Show comments relation
     */
    async gamesCommentsShowRaw(requestParameters: GamesCommentsShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GamesCommentsShow200Response>> {
        if (requestParameters['game'] == null) {
            throw new runtime.RequiredError(
                'game',
                'Required parameter "game" was null or undefined when calling gamesCommentsShow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/games/{game}/relationships/comments`.replace(`{${"game"}}`, encodeURIComponent(String(requestParameters['game']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GamesCommentsShow200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Show comments relation
     */
    async gamesCommentsShow(requestParameters: GamesCommentsShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GamesCommentsShow200Response> {
        const response = await this.gamesCommentsShowRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * Show hashes
     */
    async gamesHashesRaw(requestParameters: GamesHashesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GamesHashes200Response>> {
        if (requestParameters['game'] == null) {
            throw new runtime.RequiredError(
                'game',
                'Required parameter "game" was null or undefined when calling gamesHashes().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/games/{game}/hashes`.replace(`{${"game"}}`, encodeURIComponent(String(requestParameters['game']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GamesHashes200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Show hashes
     */
    async gamesHashes(requestParameters: GamesHashesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GamesHashes200Response> {
        const response = await this.gamesHashesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * Show hashes relation
     */
    async gamesHashesShowRaw(requestParameters: GamesHashesShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GamesHashesShow200Response>> {
        if (requestParameters['game'] == null) {
            throw new runtime.RequiredError(
                'game',
                'Required parameter "game" was null or undefined when calling gamesHashesShow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/games/{game}/relationships/hashes`.replace(`{${"game"}}`, encodeURIComponent(String(requestParameters['game']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GamesHashesShow200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Show hashes relation
     */
    async gamesHashesShow(requestParameters: GamesHashesShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GamesHashesShow200Response> {
        const response = await this.gamesHashesShowRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * Get all games
     */
    async gamesIndexRaw(requestParameters: GamesIndexRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GamesIndex200Response>> {
        const queryParameters: any = {};

        if (requestParameters['pageSize'] != null) {
            queryParameters['page[size]'] = requestParameters['pageSize'];
        }

        if (requestParameters['pageNumber'] != null) {
            queryParameters['page[number]'] = requestParameters['pageNumber'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['filterId'] != null) {
            queryParameters['filter[id][]'] = requestParameters['filterId'];
        }

        if (requestParameters['filterSystemId'] != null) {
            queryParameters['filter[systemId]'] = requestParameters['filterSystemId'];
        }

        if (requestParameters['fieldsGames'] != null) {
            queryParameters['fields[games]'] = requestParameters['fieldsGames']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['fieldsSystems'] != null) {
            queryParameters['fields[systems]'] = requestParameters['fieldsSystems']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['fieldsAchievementSets'] != null) {
            queryParameters['fields[achievement-sets]'] = requestParameters['fieldsAchievementSets']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['fieldsGameHashes'] != null) {
            queryParameters['fields[game-hashes]'] = requestParameters['fieldsGameHashes']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['include'] != null) {
            queryParameters['include'] = requestParameters['include']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/games`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GamesIndex200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Get all games
     */
    async gamesIndex(requestParameters: GamesIndexRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GamesIndex200Response> {
        const response = await this.gamesIndexRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * Show one game
     */
    async gamesShowRaw(requestParameters: GamesShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GamesShow200Response>> {
        if (requestParameters['game'] == null) {
            throw new runtime.RequiredError(
                'game',
                'Required parameter "game" was null or undefined when calling gamesShow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/games/{game}`.replace(`{${"game"}}`, encodeURIComponent(String(requestParameters['game']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GamesShow200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Show one game
     */
    async gamesShow(requestParameters: GamesShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GamesShow200Response> {
        const response = await this.gamesShowRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * Show tickets
     */
    async gamesTicketsRaw(requestParameters: GamesTicketsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AchievementsTickets200Response>> {
        if (requestParameters['game'] == null) {
            throw new runtime.RequiredError(
                'game',
                'Required parameter "game" was null or undefined when calling gamesTickets().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/games/{game}/tickets`.replace(`{${"game"}}`, encodeURIComponent(String(requestParameters['game']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AchievementsTickets200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Show tickets
     */
    async gamesTickets(requestParameters: GamesTicketsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AchievementsTickets200Response> {
        const response = await this.gamesTicketsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * Show tickets relation
     */
    async gamesTicketsShowRaw(requestParameters: GamesTicketsShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GamesTicketsShow200Response>> {
        if (requestParameters['game'] == null) {
            throw new runtime.RequiredError(
                'game',
                'Required parameter "game" was null or undefined when calling gamesTicketsShow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/games/{game}/relationships/tickets`.replace(`{${"game"}}`, encodeURIComponent(String(requestParameters['game']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GamesTicketsShow200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Show tickets relation
     */
    async gamesTicketsShow(requestParameters: GamesTicketsShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GamesTicketsShow200Response> {
        const response = await this.gamesTicketsShowRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GamesIndexSortEnum = {
    Id: 'id',
    Id2: '-id',
    Title: 'title',
    Title2: '-title',
    SortTitle: 'sortTitle',
    SortTitle2: '-sortTitle',
    ReleasedAt: 'releasedAt',
    ReleasedAt2: '-releasedAt',
    PlayersTotal: 'playersTotal',
    PlayersTotal2: '-playersTotal',
    PlayersHardcore: 'playersHardcore',
    PlayersHardcore2: '-playersHardcore',
    AchievementsPublished: 'achievementsPublished',
    AchievementsPublished2: '-achievementsPublished',
    PointsTotal: 'pointsTotal',
    PointsTotal2: '-pointsTotal',
    PointsWeighted: 'pointsWeighted',
    PointsWeighted2: '-pointsWeighted'
} as const;
export type GamesIndexSortEnum = typeof GamesIndexSortEnum[keyof typeof GamesIndexSortEnum];
/**
 * @export
 */
export const GamesIndexFieldsGamesEnum = {
    Title: 'title',
    SortTitle: 'sortTitle',
    BadgeUrl: 'badgeUrl',
    ImageBoxArtUrl: 'imageBoxArtUrl',
    ImageTitleUrl: 'imageTitleUrl',
    ImageIngameUrl: 'imageIngameUrl',
    ReleasedAt: 'releasedAt',
    ReleasedAtGranularity: 'releasedAtGranularity',
    PlayersTotal: 'playersTotal',
    PlayersHardcore: 'playersHardcore',
    AchievementsPublished: 'achievementsPublished',
    AchievementsUnpublished: 'achievementsUnpublished',
    PointsTotal: 'pointsTotal',
    PointsWeighted: 'pointsWeighted',
    TimesBeaten: 'timesBeaten',
    TimesBeatenHardcore: 'timesBeatenHardcore',
    MedianTimeToBeatMinutes: 'medianTimeToBeatMinutes',
    MedianTimeToBeatHardcoreMinutes: 'medianTimeToBeatHardcoreMinutes',
    System: 'system',
    AchievementSets: 'achievementSets',
    AchievementSetClaims: 'achievementSetClaims',
    Comments: 'comments',
    Hashes: 'hashes',
    Tickets: 'tickets'
} as const;
export type GamesIndexFieldsGamesEnum = typeof GamesIndexFieldsGamesEnum[keyof typeof GamesIndexFieldsGamesEnum];
/**
 * @export
 */
export const GamesIndexFieldsSystemsEnum = {
    Name: 'name',
    NameFull: 'nameFull',
    NameShort: 'nameShort',
    Manufacturer: 'manufacturer',
    IconUrl: 'iconUrl',
    Active: 'active'
} as const;
export type GamesIndexFieldsSystemsEnum = typeof GamesIndexFieldsSystemsEnum[keyof typeof GamesIndexFieldsSystemsEnum];
/**
 * @export
 */
export const GamesIndexFieldsAchievementSetsEnum = {
    Title: 'title',
    PointsTotal: 'pointsTotal',
    PointsWeighted: 'pointsWeighted',
    AchievementsPublished: 'achievementsPublished',
    AchievementsUnpublished: 'achievementsUnpublished',
    BadgeUrl: 'badgeUrl',
    AchievementsFirstPublishedAt: 'achievementsFirstPublishedAt',
    Types: 'types',
    CreatedAt: 'createdAt',
    UpdatedAt: 'updatedAt',
    Games: 'games',
    AchievementSetVersions: 'achievementSetVersions'
} as const;
export type GamesIndexFieldsAchievementSetsEnum = typeof GamesIndexFieldsAchievementSetsEnum[keyof typeof GamesIndexFieldsAchievementSetsEnum];
/**
 * @export
 */
export const GamesIndexFieldsGameHashesEnum = {
    RaMd5: 'raMd5',
    Name: 'name',
    Compatibility: 'compatibility',
    PatchUrl: 'patchUrl',
    CreatedAt: 'createdAt',
    UpdatedAt: 'updatedAt',
    Game: 'game'
} as const;
export type GamesIndexFieldsGameHashesEnum = typeof GamesIndexFieldsGameHashesEnum[keyof typeof GamesIndexFieldsGameHashesEnum];
/**
 * @export
 */
export const GamesIndexIncludeEnum = {
    System: 'system',
    AchievementSets: 'achievementSets',
    Hashes: 'hashes'
} as const;
export type GamesIndexIncludeEnum = typeof GamesIndexIncludeEnum[keyof typeof GamesIndexIncludeEnum];
