/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AchievementsIndex400Response,
  HubsGames200Response,
  HubsGamesShow200Response,
  HubsIndex200Response,
  HubsLinks200Response,
  HubsLinksShow200Response,
  HubsShow200Response,
} from '../models/index';
import {
    AchievementsIndex400ResponseFromJSON,
    AchievementsIndex400ResponseToJSON,
    HubsGames200ResponseFromJSON,
    HubsGames200ResponseToJSON,
    HubsGamesShow200ResponseFromJSON,
    HubsGamesShow200ResponseToJSON,
    HubsIndex200ResponseFromJSON,
    HubsIndex200ResponseToJSON,
    HubsLinks200ResponseFromJSON,
    HubsLinks200ResponseToJSON,
    HubsLinksShow200ResponseFromJSON,
    HubsLinksShow200ResponseToJSON,
    HubsShow200ResponseFromJSON,
    HubsShow200ResponseToJSON,
} from '../models/index';

export interface HubsGamesRequest {
    hub: string;
}

export interface HubsGamesShowRequest {
    hub: string;
}

export interface HubsIndexRequest {
    pageSize?: number;
    pageNumber?: number;
    sort?: Array<HubsIndexSortEnum>;
    filterId?: Array<string>;
    filterParentId?: boolean;
    filterTitle?: boolean;
    fieldsHubs?: Array<HubsIndexFieldsHubsEnum>;
    include?: Array<string>;
}

export interface HubsLinksRequest {
    hub: string;
}

export interface HubsLinksShowRequest {
    hub: string;
}

export interface HubsShowRequest {
    hub: string;
}

/**
 * 
 */
export class HubsApi extends runtime.BaseAPI {

    /**
     * 
     * Show games
     */
    async hubsGamesRaw(requestParameters: HubsGamesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HubsGames200Response>> {
        if (requestParameters['hub'] == null) {
            throw new runtime.RequiredError(
                'hub',
                'Required parameter "hub" was null or undefined when calling hubsGames().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/hubs/{hub}/games`.replace(`{${"hub"}}`, encodeURIComponent(String(requestParameters['hub']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HubsGames200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Show games
     */
    async hubsGames(requestParameters: HubsGamesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HubsGames200Response> {
        const response = await this.hubsGamesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * Show games relation
     */
    async hubsGamesShowRaw(requestParameters: HubsGamesShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HubsGamesShow200Response>> {
        if (requestParameters['hub'] == null) {
            throw new runtime.RequiredError(
                'hub',
                'Required parameter "hub" was null or undefined when calling hubsGamesShow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/hubs/{hub}/relationships/games`.replace(`{${"hub"}}`, encodeURIComponent(String(requestParameters['hub']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HubsGamesShow200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Show games relation
     */
    async hubsGamesShow(requestParameters: HubsGamesShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HubsGamesShow200Response> {
        const response = await this.hubsGamesShowRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * Get all hubs
     */
    async hubsIndexRaw(requestParameters: HubsIndexRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HubsIndex200Response>> {
        const queryParameters: any = {};

        if (requestParameters['pageSize'] != null) {
            queryParameters['page[size]'] = requestParameters['pageSize'];
        }

        if (requestParameters['pageNumber'] != null) {
            queryParameters['page[number]'] = requestParameters['pageNumber'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['filterId'] != null) {
            queryParameters['filter[id][]'] = requestParameters['filterId'];
        }

        if (requestParameters['filterParentId'] != null) {
            queryParameters['filter[parentId]'] = requestParameters['filterParentId'];
        }

        if (requestParameters['filterTitle'] != null) {
            queryParameters['filter[title]'] = requestParameters['filterTitle'];
        }

        if (requestParameters['fieldsHubs'] != null) {
            queryParameters['fields[hubs]'] = requestParameters['fieldsHubs']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['include'] != null) {
            queryParameters['include'] = requestParameters['include']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/hubs`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HubsIndex200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Get all hubs
     */
    async hubsIndex(requestParameters: HubsIndexRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HubsIndex200Response> {
        const response = await this.hubsIndexRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * Show links
     */
    async hubsLinksRaw(requestParameters: HubsLinksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HubsLinks200Response>> {
        if (requestParameters['hub'] == null) {
            throw new runtime.RequiredError(
                'hub',
                'Required parameter "hub" was null or undefined when calling hubsLinks().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/hubs/{hub}/links`.replace(`{${"hub"}}`, encodeURIComponent(String(requestParameters['hub']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HubsLinks200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Show links
     */
    async hubsLinks(requestParameters: HubsLinksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HubsLinks200Response> {
        const response = await this.hubsLinksRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * Show links relation
     */
    async hubsLinksShowRaw(requestParameters: HubsLinksShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HubsLinksShow200Response>> {
        if (requestParameters['hub'] == null) {
            throw new runtime.RequiredError(
                'hub',
                'Required parameter "hub" was null or undefined when calling hubsLinksShow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/hubs/{hub}/relationships/links`.replace(`{${"hub"}}`, encodeURIComponent(String(requestParameters['hub']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HubsLinksShow200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Show links relation
     */
    async hubsLinksShow(requestParameters: HubsLinksShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HubsLinksShow200Response> {
        const response = await this.hubsLinksShowRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * Show one hub
     */
    async hubsShowRaw(requestParameters: HubsShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HubsShow200Response>> {
        if (requestParameters['hub'] == null) {
            throw new runtime.RequiredError(
                'hub',
                'Required parameter "hub" was null or undefined when calling hubsShow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/hubs/{hub}`.replace(`{${"hub"}}`, encodeURIComponent(String(requestParameters['hub']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HubsShow200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Show one hub
     */
    async hubsShow(requestParameters: HubsShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HubsShow200Response> {
        const response = await this.hubsShowRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const HubsIndexSortEnum = {
    Id: 'id',
    Id2: '-id',
    Title: 'title',
    Title2: '-title',
    SortTitle: 'sortTitle',
    SortTitle2: '-sortTitle',
    CreatedAt: 'createdAt',
    CreatedAt2: '-createdAt',
    UpdatedAt: 'updatedAt',
    UpdatedAt2: '-updatedAt',
    GamesCount: 'gamesCount',
    GamesCount2: '-gamesCount',
    LinkedHubsCount: 'linkedHubsCount',
    LinkedHubsCount2: '-linkedHubsCount'
} as const;
export type HubsIndexSortEnum = typeof HubsIndexSortEnum[keyof typeof HubsIndexSortEnum];
/**
 * @export
 */
export const HubsIndexFieldsHubsEnum = {
    Title: 'title',
    SortTitle: 'sortTitle',
    BadgeUrl: 'badgeUrl',
    HasMatureContent: 'hasMatureContent',
    GamesCount: 'gamesCount',
    LinkedHubsCount: 'linkedHubsCount',
    IsEventHub: 'isEventHub',
    CreatedAt: 'createdAt',
    UpdatedAt: 'updatedAt',
    Games: 'games',
    Links: 'links'
} as const;
export type HubsIndexFieldsHubsEnum = typeof HubsIndexFieldsHubsEnum[keyof typeof HubsIndexFieldsHubsEnum];
