/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AchievementsIndex400Response,
  LeaderboardsEntries200Response,
  LeaderboardsEntriesShow200Response,
  LeaderboardsIndex200Response,
  LeaderboardsShow200Response,
} from '../models/index';
import {
    AchievementsIndex400ResponseFromJSON,
    AchievementsIndex400ResponseToJSON,
    LeaderboardsEntries200ResponseFromJSON,
    LeaderboardsEntries200ResponseToJSON,
    LeaderboardsEntriesShow200ResponseFromJSON,
    LeaderboardsEntriesShow200ResponseToJSON,
    LeaderboardsIndex200ResponseFromJSON,
    LeaderboardsIndex200ResponseToJSON,
    LeaderboardsShow200ResponseFromJSON,
    LeaderboardsShow200ResponseToJSON,
} from '../models/index';

export interface LeaderboardsEntriesRequest {
    leaderboard: string;
}

export interface LeaderboardsEntriesShowRequest {
    leaderboard: string;
}

export interface LeaderboardsIndexRequest {
    pageSize?: number;
    pageNumber?: number;
    sort?: Array<LeaderboardsIndexSortEnum>;
    filterId?: Array<string>;
    filterGameId?: string;
    filterState?: boolean;
    fieldsLeaderboards?: Array<LeaderboardsIndexFieldsLeaderboardsEnum>;
    fieldsGames?: Array<LeaderboardsIndexFieldsGamesEnum>;
    fieldsUsers?: Array<LeaderboardsIndexFieldsUsersEnum>;
    fieldsLeaderboardEntries?: Array<LeaderboardsIndexFieldsLeaderboardEntriesEnum>;
    include?: Array<LeaderboardsIndexIncludeEnum>;
}

export interface LeaderboardsShowRequest {
    leaderboard: string;
}

/**
 * 
 */
export class LeaderboardsApi extends runtime.BaseAPI {

    /**
     * 
     * Show entries
     */
    async leaderboardsEntriesRaw(requestParameters: LeaderboardsEntriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LeaderboardsEntries200Response>> {
        if (requestParameters['leaderboard'] == null) {
            throw new runtime.RequiredError(
                'leaderboard',
                'Required parameter "leaderboard" was null or undefined when calling leaderboardsEntries().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/leaderboards/{leaderboard}/entries`.replace(`{${"leaderboard"}}`, encodeURIComponent(String(requestParameters['leaderboard']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LeaderboardsEntries200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Show entries
     */
    async leaderboardsEntries(requestParameters: LeaderboardsEntriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LeaderboardsEntries200Response> {
        const response = await this.leaderboardsEntriesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * Show entries relation
     */
    async leaderboardsEntriesShowRaw(requestParameters: LeaderboardsEntriesShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LeaderboardsEntriesShow200Response>> {
        if (requestParameters['leaderboard'] == null) {
            throw new runtime.RequiredError(
                'leaderboard',
                'Required parameter "leaderboard" was null or undefined when calling leaderboardsEntriesShow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/leaderboards/{leaderboard}/relationships/entries`.replace(`{${"leaderboard"}}`, encodeURIComponent(String(requestParameters['leaderboard']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LeaderboardsEntriesShow200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Show entries relation
     */
    async leaderboardsEntriesShow(requestParameters: LeaderboardsEntriesShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LeaderboardsEntriesShow200Response> {
        const response = await this.leaderboardsEntriesShowRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * Get all leaderboards
     */
    async leaderboardsIndexRaw(requestParameters: LeaderboardsIndexRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LeaderboardsIndex200Response>> {
        const queryParameters: any = {};

        if (requestParameters['pageSize'] != null) {
            queryParameters['page[size]'] = requestParameters['pageSize'];
        }

        if (requestParameters['pageNumber'] != null) {
            queryParameters['page[number]'] = requestParameters['pageNumber'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['filterId'] != null) {
            queryParameters['filter[id][]'] = requestParameters['filterId'];
        }

        if (requestParameters['filterGameId'] != null) {
            queryParameters['filter[gameId]'] = requestParameters['filterGameId'];
        }

        if (requestParameters['filterState'] != null) {
            queryParameters['filter[state]'] = requestParameters['filterState'];
        }

        if (requestParameters['fieldsLeaderboards'] != null) {
            queryParameters['fields[leaderboards]'] = requestParameters['fieldsLeaderboards']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['fieldsGames'] != null) {
            queryParameters['fields[games]'] = requestParameters['fieldsGames']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['fieldsUsers'] != null) {
            queryParameters['fields[users]'] = requestParameters['fieldsUsers']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['fieldsLeaderboardEntries'] != null) {
            queryParameters['fields[leaderboard-entries]'] = requestParameters['fieldsLeaderboardEntries']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['include'] != null) {
            queryParameters['include'] = requestParameters['include']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/leaderboards`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LeaderboardsIndex200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Get all leaderboards
     */
    async leaderboardsIndex(requestParameters: LeaderboardsIndexRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LeaderboardsIndex200Response> {
        const response = await this.leaderboardsIndexRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * Show one leaderboard
     */
    async leaderboardsShowRaw(requestParameters: LeaderboardsShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LeaderboardsShow200Response>> {
        if (requestParameters['leaderboard'] == null) {
            throw new runtime.RequiredError(
                'leaderboard',
                'Required parameter "leaderboard" was null or undefined when calling leaderboardsShow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/leaderboards/{leaderboard}`.replace(`{${"leaderboard"}}`, encodeURIComponent(String(requestParameters['leaderboard']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LeaderboardsShow200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Show one leaderboard
     */
    async leaderboardsShow(requestParameters: LeaderboardsShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LeaderboardsShow200Response> {
        const response = await this.leaderboardsShowRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const LeaderboardsIndexSortEnum = {
    Id: 'id',
    Id2: '-id',
    Title: 'title',
    Title2: '-title',
    OrderColumn: 'orderColumn',
    OrderColumn2: '-orderColumn',
    CreatedAt: 'createdAt',
    CreatedAt2: '-createdAt',
    UpdatedAt: 'updatedAt',
    UpdatedAt2: '-updatedAt'
} as const;
export type LeaderboardsIndexSortEnum = typeof LeaderboardsIndexSortEnum[keyof typeof LeaderboardsIndexSortEnum];
/**
 * @export
 */
export const LeaderboardsIndexFieldsLeaderboardsEnum = {
    Title: 'title',
    Description: 'description',
    Format: 'format',
    RankAsc: 'rankAsc',
    State: 'state',
    OrderColumn: 'orderColumn',
    CreatedAt: 'createdAt',
    UpdatedAt: 'updatedAt',
    Games: 'games',
    Developer: 'developer',
    Entries: 'entries'
} as const;
export type LeaderboardsIndexFieldsLeaderboardsEnum = typeof LeaderboardsIndexFieldsLeaderboardsEnum[keyof typeof LeaderboardsIndexFieldsLeaderboardsEnum];
/**
 * @export
 */
export const LeaderboardsIndexFieldsGamesEnum = {
    Title: 'title',
    SortTitle: 'sortTitle',
    BadgeUrl: 'badgeUrl',
    ImageBoxArtUrl: 'imageBoxArtUrl',
    ImageTitleUrl: 'imageTitleUrl',
    ImageIngameUrl: 'imageIngameUrl',
    ReleasedAt: 'releasedAt',
    ReleasedAtGranularity: 'releasedAtGranularity',
    PlayersTotal: 'playersTotal',
    PlayersHardcore: 'playersHardcore',
    AchievementsPublished: 'achievementsPublished',
    AchievementsUnpublished: 'achievementsUnpublished',
    PointsTotal: 'pointsTotal',
    PointsWeighted: 'pointsWeighted',
    TimesBeaten: 'timesBeaten',
    TimesBeatenHardcore: 'timesBeatenHardcore',
    MedianTimeToBeatMinutes: 'medianTimeToBeatMinutes',
    MedianTimeToBeatHardcoreMinutes: 'medianTimeToBeatHardcoreMinutes',
    System: 'system',
    AchievementSets: 'achievementSets',
    AchievementSetClaims: 'achievementSetClaims',
    Comments: 'comments',
    Hashes: 'hashes',
    Tickets: 'tickets'
} as const;
export type LeaderboardsIndexFieldsGamesEnum = typeof LeaderboardsIndexFieldsGamesEnum[keyof typeof LeaderboardsIndexFieldsGamesEnum];
/**
 * @export
 */
export const LeaderboardsIndexFieldsUsersEnum = {
    DisplayName: 'displayName',
    AvatarUrl: 'avatarUrl',
    Motto: 'motto',
    Points: 'points',
    PointsHardcore: 'pointsHardcore',
    PointsWeighted: 'pointsWeighted',
    YieldUnlocks: 'yieldUnlocks',
    YieldPoints: 'yieldPoints',
    JoinedAt: 'joinedAt',
    LastActivityAt: 'lastActivityAt',
    DeletedAt: 'deletedAt',
    IsUnranked: 'isUnranked',
    IsUserWallActive: 'isUserWallActive',
    RichPresence: 'richPresence',
    RichPresenceUpdatedAt: 'richPresenceUpdatedAt',
    VisibleRole: 'visibleRole',
    DisplayableRoles: 'displayableRoles',
    AchievementSetClaims: 'achievementSetClaims',
    PlayerAchievements: 'playerAchievements',
    PlayerAchievementSets: 'playerAchievementSets',
    PlayerGames: 'playerGames',
    Tickets: 'tickets',
    WallComments: 'wallComments',
    Awards: 'awards',
    Followers: 'followers',
    Following: 'following'
} as const;
export type LeaderboardsIndexFieldsUsersEnum = typeof LeaderboardsIndexFieldsUsersEnum[keyof typeof LeaderboardsIndexFieldsUsersEnum];
/**
 * @export
 */
export const LeaderboardsIndexFieldsLeaderboardEntriesEnum = {
    Score: 'score',
    Rank: 'rank',
    CreatedAt: 'createdAt',
    UpdatedAt: 'updatedAt',
    User: 'user',
    Leaderboard: 'leaderboard'
} as const;
export type LeaderboardsIndexFieldsLeaderboardEntriesEnum = typeof LeaderboardsIndexFieldsLeaderboardEntriesEnum[keyof typeof LeaderboardsIndexFieldsLeaderboardEntriesEnum];
/**
 * @export
 */
export const LeaderboardsIndexIncludeEnum = {
    Games: 'games',
    Developer: 'developer',
    Entries: 'entries'
} as const;
export type LeaderboardsIndexIncludeEnum = typeof LeaderboardsIndexIncludeEnum[keyof typeof LeaderboardsIndexIncludeEnum];
