/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AchievementsIndex400Response,
  SystemsIndex200Response,
  SystemsShow200Response,
} from '../models/index';
import {
    AchievementsIndex400ResponseFromJSON,
    AchievementsIndex400ResponseToJSON,
    SystemsIndex200ResponseFromJSON,
    SystemsIndex200ResponseToJSON,
    SystemsShow200ResponseFromJSON,
    SystemsShow200ResponseToJSON,
} from '../models/index';

export interface SystemsIndexRequest {
    pageSize?: number;
    pageNumber?: number;
    sort?: Array<SystemsIndexSortEnum>;
    filterId?: Array<string>;
    filterActive?: string;
    fieldsSystems?: Array<SystemsIndexFieldsSystemsEnum>;
    include?: Array<string>;
}

export interface SystemsShowRequest {
    system: string;
}

/**
 * 
 */
export class SystemsApi extends runtime.BaseAPI {

    /**
     * 
     * Get all systems
     */
    async systemsIndexRaw(requestParameters: SystemsIndexRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SystemsIndex200Response>> {
        const queryParameters: any = {};

        if (requestParameters['pageSize'] != null) {
            queryParameters['page[size]'] = requestParameters['pageSize'];
        }

        if (requestParameters['pageNumber'] != null) {
            queryParameters['page[number]'] = requestParameters['pageNumber'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['filterId'] != null) {
            queryParameters['filter[id][]'] = requestParameters['filterId'];
        }

        if (requestParameters['filterActive'] != null) {
            queryParameters['filter[active]'] = requestParameters['filterActive'];
        }

        if (requestParameters['fieldsSystems'] != null) {
            queryParameters['fields[systems]'] = requestParameters['fieldsSystems']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['include'] != null) {
            queryParameters['include'] = requestParameters['include']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/systems`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SystemsIndex200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Get all systems
     */
    async systemsIndex(requestParameters: SystemsIndexRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SystemsIndex200Response> {
        const response = await this.systemsIndexRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * Show one system
     */
    async systemsShowRaw(requestParameters: SystemsShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SystemsShow200Response>> {
        if (requestParameters['system'] == null) {
            throw new runtime.RequiredError(
                'system',
                'Required parameter "system" was null or undefined when calling systemsShow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/systems/{system}`.replace(`{${"system"}}`, encodeURIComponent(String(requestParameters['system']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SystemsShow200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Show one system
     */
    async systemsShow(requestParameters: SystemsShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SystemsShow200Response> {
        const response = await this.systemsShowRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const SystemsIndexSortEnum = {
    Id: 'id',
    Id2: '-id',
    Name: 'name',
    Name2: '-name',
    NameFull: 'nameFull',
    NameFull2: '-nameFull',
    NameShort: 'nameShort',
    NameShort2: '-nameShort'
} as const;
export type SystemsIndexSortEnum = typeof SystemsIndexSortEnum[keyof typeof SystemsIndexSortEnum];
/**
 * @export
 */
export const SystemsIndexFieldsSystemsEnum = {
    Name: 'name',
    NameFull: 'nameFull',
    NameShort: 'nameShort',
    Manufacturer: 'manufacturer',
    IconUrl: 'iconUrl',
    Active: 'active'
} as const;
export type SystemsIndexFieldsSystemsEnum = typeof SystemsIndexFieldsSystemsEnum[keyof typeof SystemsIndexFieldsSystemsEnum];
