/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AchievementsComments200Response,
  AchievementsIndex400Response,
  AchievementsPlayerAchievements200Response,
  AchievementsTickets200Response,
  GamesAchievementSetClaims200Response,
  UsersAchievementSetClaimsShow200Response,
  UsersAwards200Response,
  UsersAwardsShow200Response,
  UsersFollowers200Response,
  UsersFollowersShow200Response,
  UsersFollowingShow200Response,
  UsersIndex200Response,
  UsersPlayerAchievementSets200Response,
  UsersPlayerAchievementSetsShow200Response,
  UsersPlayerAchievementsShow200Response,
  UsersPlayerGames200Response,
  UsersPlayerGamesShow200Response,
  UsersShow200Response,
  UsersTicketsShow200Response,
  UsersWallCommentsShow200Response,
} from '../models/index';
import {
    AchievementsComments200ResponseFromJSON,
    AchievementsComments200ResponseToJSON,
    AchievementsIndex400ResponseFromJSON,
    AchievementsIndex400ResponseToJSON,
    AchievementsPlayerAchievements200ResponseFromJSON,
    AchievementsPlayerAchievements200ResponseToJSON,
    AchievementsTickets200ResponseFromJSON,
    AchievementsTickets200ResponseToJSON,
    GamesAchievementSetClaims200ResponseFromJSON,
    GamesAchievementSetClaims200ResponseToJSON,
    UsersAchievementSetClaimsShow200ResponseFromJSON,
    UsersAchievementSetClaimsShow200ResponseToJSON,
    UsersAwards200ResponseFromJSON,
    UsersAwards200ResponseToJSON,
    UsersAwardsShow200ResponseFromJSON,
    UsersAwardsShow200ResponseToJSON,
    UsersFollowers200ResponseFromJSON,
    UsersFollowers200ResponseToJSON,
    UsersFollowersShow200ResponseFromJSON,
    UsersFollowersShow200ResponseToJSON,
    UsersFollowingShow200ResponseFromJSON,
    UsersFollowingShow200ResponseToJSON,
    UsersIndex200ResponseFromJSON,
    UsersIndex200ResponseToJSON,
    UsersPlayerAchievementSets200ResponseFromJSON,
    UsersPlayerAchievementSets200ResponseToJSON,
    UsersPlayerAchievementSetsShow200ResponseFromJSON,
    UsersPlayerAchievementSetsShow200ResponseToJSON,
    UsersPlayerAchievementsShow200ResponseFromJSON,
    UsersPlayerAchievementsShow200ResponseToJSON,
    UsersPlayerGames200ResponseFromJSON,
    UsersPlayerGames200ResponseToJSON,
    UsersPlayerGamesShow200ResponseFromJSON,
    UsersPlayerGamesShow200ResponseToJSON,
    UsersShow200ResponseFromJSON,
    UsersShow200ResponseToJSON,
    UsersTicketsShow200ResponseFromJSON,
    UsersTicketsShow200ResponseToJSON,
    UsersWallCommentsShow200ResponseFromJSON,
    UsersWallCommentsShow200ResponseToJSON,
} from '../models/index';

export interface UsersAchievementSetClaimsRequest {
    user: string;
}

export interface UsersAchievementSetClaimsShowRequest {
    user: string;
}

export interface UsersAwardsRequest {
    user: string;
}

export interface UsersAwardsShowRequest {
    user: string;
}

export interface UsersFollowersRequest {
    user: string;
}

export interface UsersFollowersShowRequest {
    user: string;
}

export interface UsersFollowingRequest {
    user: string;
}

export interface UsersFollowingShowRequest {
    user: string;
}

export interface UsersIndexRequest {
    pageSize?: number;
    pageNumber?: number;
    sort?: Array<UsersIndexSortEnum>;
    filterRole?: boolean;
    fieldsUsers?: Array<UsersIndexFieldsUsersEnum>;
    include?: Array<string>;
}

export interface UsersPlayerAchievementSetsRequest {
    user: string;
}

export interface UsersPlayerAchievementSetsShowRequest {
    user: string;
}

export interface UsersPlayerAchievementsRequest {
    user: string;
}

export interface UsersPlayerAchievementsShowRequest {
    user: string;
}

export interface UsersPlayerGamesRequest {
    user: string;
}

export interface UsersPlayerGamesShowRequest {
    user: string;
}

export interface UsersShowRequest {
    user: string;
}

export interface UsersTicketsRequest {
    user: string;
}

export interface UsersTicketsShowRequest {
    user: string;
}

export interface UsersWallCommentsRequest {
    user: string;
}

export interface UsersWallCommentsShowRequest {
    user: string;
}

/**
 * 
 */
export class UsersApi extends runtime.BaseAPI {

    /**
     * 
     * Show achievementSetClaims
     */
    async usersAchievementSetClaimsRaw(requestParameters: UsersAchievementSetClaimsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GamesAchievementSetClaims200Response>> {
        if (requestParameters['user'] == null) {
            throw new runtime.RequiredError(
                'user',
                'Required parameter "user" was null or undefined when calling usersAchievementSetClaims().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/{user}/achievement-set-claims`.replace(`{${"user"}}`, encodeURIComponent(String(requestParameters['user']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GamesAchievementSetClaims200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Show achievementSetClaims
     */
    async usersAchievementSetClaims(requestParameters: UsersAchievementSetClaimsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GamesAchievementSetClaims200Response> {
        const response = await this.usersAchievementSetClaimsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * Show achievementSetClaims relation
     */
    async usersAchievementSetClaimsShowRaw(requestParameters: UsersAchievementSetClaimsShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UsersAchievementSetClaimsShow200Response>> {
        if (requestParameters['user'] == null) {
            throw new runtime.RequiredError(
                'user',
                'Required parameter "user" was null or undefined when calling usersAchievementSetClaimsShow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/{user}/relationships/achievement-set-claims`.replace(`{${"user"}}`, encodeURIComponent(String(requestParameters['user']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UsersAchievementSetClaimsShow200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Show achievementSetClaims relation
     */
    async usersAchievementSetClaimsShow(requestParameters: UsersAchievementSetClaimsShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UsersAchievementSetClaimsShow200Response> {
        const response = await this.usersAchievementSetClaimsShowRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * Show awards
     */
    async usersAwardsRaw(requestParameters: UsersAwardsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UsersAwards200Response>> {
        if (requestParameters['user'] == null) {
            throw new runtime.RequiredError(
                'user',
                'Required parameter "user" was null or undefined when calling usersAwards().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/{user}/awards`.replace(`{${"user"}}`, encodeURIComponent(String(requestParameters['user']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UsersAwards200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Show awards
     */
    async usersAwards(requestParameters: UsersAwardsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UsersAwards200Response> {
        const response = await this.usersAwardsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * Show awards relation
     */
    async usersAwardsShowRaw(requestParameters: UsersAwardsShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UsersAwardsShow200Response>> {
        if (requestParameters['user'] == null) {
            throw new runtime.RequiredError(
                'user',
                'Required parameter "user" was null or undefined when calling usersAwardsShow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/{user}/relationships/awards`.replace(`{${"user"}}`, encodeURIComponent(String(requestParameters['user']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UsersAwardsShow200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Show awards relation
     */
    async usersAwardsShow(requestParameters: UsersAwardsShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UsersAwardsShow200Response> {
        const response = await this.usersAwardsShowRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * Show followers
     */
    async usersFollowersRaw(requestParameters: UsersFollowersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UsersFollowers200Response>> {
        if (requestParameters['user'] == null) {
            throw new runtime.RequiredError(
                'user',
                'Required parameter "user" was null or undefined when calling usersFollowers().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/{user}/followers`.replace(`{${"user"}}`, encodeURIComponent(String(requestParameters['user']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UsersFollowers200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Show followers
     */
    async usersFollowers(requestParameters: UsersFollowersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UsersFollowers200Response> {
        const response = await this.usersFollowersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * Show followers relation
     */
    async usersFollowersShowRaw(requestParameters: UsersFollowersShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UsersFollowersShow200Response>> {
        if (requestParameters['user'] == null) {
            throw new runtime.RequiredError(
                'user',
                'Required parameter "user" was null or undefined when calling usersFollowersShow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/{user}/relationships/followers`.replace(`{${"user"}}`, encodeURIComponent(String(requestParameters['user']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UsersFollowersShow200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Show followers relation
     */
    async usersFollowersShow(requestParameters: UsersFollowersShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UsersFollowersShow200Response> {
        const response = await this.usersFollowersShowRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * Show following
     */
    async usersFollowingRaw(requestParameters: UsersFollowingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UsersFollowers200Response>> {
        if (requestParameters['user'] == null) {
            throw new runtime.RequiredError(
                'user',
                'Required parameter "user" was null or undefined when calling usersFollowing().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/{user}/following`.replace(`{${"user"}}`, encodeURIComponent(String(requestParameters['user']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UsersFollowers200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Show following
     */
    async usersFollowing(requestParameters: UsersFollowingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UsersFollowers200Response> {
        const response = await this.usersFollowingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * Show following relation
     */
    async usersFollowingShowRaw(requestParameters: UsersFollowingShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UsersFollowingShow200Response>> {
        if (requestParameters['user'] == null) {
            throw new runtime.RequiredError(
                'user',
                'Required parameter "user" was null or undefined when calling usersFollowingShow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/{user}/relationships/following`.replace(`{${"user"}}`, encodeURIComponent(String(requestParameters['user']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UsersFollowingShow200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Show following relation
     */
    async usersFollowingShow(requestParameters: UsersFollowingShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UsersFollowingShow200Response> {
        const response = await this.usersFollowingShowRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * Get all users
     */
    async usersIndexRaw(requestParameters: UsersIndexRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UsersIndex200Response>> {
        const queryParameters: any = {};

        if (requestParameters['pageSize'] != null) {
            queryParameters['page[size]'] = requestParameters['pageSize'];
        }

        if (requestParameters['pageNumber'] != null) {
            queryParameters['page[number]'] = requestParameters['pageNumber'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['filterRole'] != null) {
            queryParameters['filter[role]'] = requestParameters['filterRole'];
        }

        if (requestParameters['fieldsUsers'] != null) {
            queryParameters['fields[users]'] = requestParameters['fieldsUsers']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['include'] != null) {
            queryParameters['include'] = requestParameters['include']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UsersIndex200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Get all users
     */
    async usersIndex(requestParameters: UsersIndexRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UsersIndex200Response> {
        const response = await this.usersIndexRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * Show playerAchievementSets
     */
    async usersPlayerAchievementSetsRaw(requestParameters: UsersPlayerAchievementSetsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UsersPlayerAchievementSets200Response>> {
        if (requestParameters['user'] == null) {
            throw new runtime.RequiredError(
                'user',
                'Required parameter "user" was null or undefined when calling usersPlayerAchievementSets().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/{user}/player-achievement-sets`.replace(`{${"user"}}`, encodeURIComponent(String(requestParameters['user']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UsersPlayerAchievementSets200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Show playerAchievementSets
     */
    async usersPlayerAchievementSets(requestParameters: UsersPlayerAchievementSetsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UsersPlayerAchievementSets200Response> {
        const response = await this.usersPlayerAchievementSetsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * Show playerAchievementSets relation
     */
    async usersPlayerAchievementSetsShowRaw(requestParameters: UsersPlayerAchievementSetsShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UsersPlayerAchievementSetsShow200Response>> {
        if (requestParameters['user'] == null) {
            throw new runtime.RequiredError(
                'user',
                'Required parameter "user" was null or undefined when calling usersPlayerAchievementSetsShow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/{user}/relationships/player-achievement-sets`.replace(`{${"user"}}`, encodeURIComponent(String(requestParameters['user']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UsersPlayerAchievementSetsShow200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Show playerAchievementSets relation
     */
    async usersPlayerAchievementSetsShow(requestParameters: UsersPlayerAchievementSetsShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UsersPlayerAchievementSetsShow200Response> {
        const response = await this.usersPlayerAchievementSetsShowRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * Show playerAchievements
     */
    async usersPlayerAchievementsRaw(requestParameters: UsersPlayerAchievementsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AchievementsPlayerAchievements200Response>> {
        if (requestParameters['user'] == null) {
            throw new runtime.RequiredError(
                'user',
                'Required parameter "user" was null or undefined when calling usersPlayerAchievements().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/{user}/player-achievements`.replace(`{${"user"}}`, encodeURIComponent(String(requestParameters['user']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AchievementsPlayerAchievements200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Show playerAchievements
     */
    async usersPlayerAchievements(requestParameters: UsersPlayerAchievementsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AchievementsPlayerAchievements200Response> {
        const response = await this.usersPlayerAchievementsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * Show playerAchievements relation
     */
    async usersPlayerAchievementsShowRaw(requestParameters: UsersPlayerAchievementsShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UsersPlayerAchievementsShow200Response>> {
        if (requestParameters['user'] == null) {
            throw new runtime.RequiredError(
                'user',
                'Required parameter "user" was null or undefined when calling usersPlayerAchievementsShow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/{user}/relationships/player-achievements`.replace(`{${"user"}}`, encodeURIComponent(String(requestParameters['user']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UsersPlayerAchievementsShow200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Show playerAchievements relation
     */
    async usersPlayerAchievementsShow(requestParameters: UsersPlayerAchievementsShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UsersPlayerAchievementsShow200Response> {
        const response = await this.usersPlayerAchievementsShowRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * Show playerGames
     */
    async usersPlayerGamesRaw(requestParameters: UsersPlayerGamesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UsersPlayerGames200Response>> {
        if (requestParameters['user'] == null) {
            throw new runtime.RequiredError(
                'user',
                'Required parameter "user" was null or undefined when calling usersPlayerGames().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/{user}/player-games`.replace(`{${"user"}}`, encodeURIComponent(String(requestParameters['user']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UsersPlayerGames200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Show playerGames
     */
    async usersPlayerGames(requestParameters: UsersPlayerGamesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UsersPlayerGames200Response> {
        const response = await this.usersPlayerGamesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * Show playerGames relation
     */
    async usersPlayerGamesShowRaw(requestParameters: UsersPlayerGamesShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UsersPlayerGamesShow200Response>> {
        if (requestParameters['user'] == null) {
            throw new runtime.RequiredError(
                'user',
                'Required parameter "user" was null or undefined when calling usersPlayerGamesShow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/{user}/relationships/player-games`.replace(`{${"user"}}`, encodeURIComponent(String(requestParameters['user']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UsersPlayerGamesShow200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Show playerGames relation
     */
    async usersPlayerGamesShow(requestParameters: UsersPlayerGamesShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UsersPlayerGamesShow200Response> {
        const response = await this.usersPlayerGamesShowRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * Show one user
     */
    async usersShowRaw(requestParameters: UsersShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UsersShow200Response>> {
        if (requestParameters['user'] == null) {
            throw new runtime.RequiredError(
                'user',
                'Required parameter "user" was null or undefined when calling usersShow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/{user}`.replace(`{${"user"}}`, encodeURIComponent(String(requestParameters['user']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UsersShow200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Show one user
     */
    async usersShow(requestParameters: UsersShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UsersShow200Response> {
        const response = await this.usersShowRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * Show tickets
     */
    async usersTicketsRaw(requestParameters: UsersTicketsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AchievementsTickets200Response>> {
        if (requestParameters['user'] == null) {
            throw new runtime.RequiredError(
                'user',
                'Required parameter "user" was null or undefined when calling usersTickets().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/{user}/tickets`.replace(`{${"user"}}`, encodeURIComponent(String(requestParameters['user']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AchievementsTickets200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Show tickets
     */
    async usersTickets(requestParameters: UsersTicketsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AchievementsTickets200Response> {
        const response = await this.usersTicketsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * Show tickets relation
     */
    async usersTicketsShowRaw(requestParameters: UsersTicketsShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UsersTicketsShow200Response>> {
        if (requestParameters['user'] == null) {
            throw new runtime.RequiredError(
                'user',
                'Required parameter "user" was null or undefined when calling usersTicketsShow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/{user}/relationships/tickets`.replace(`{${"user"}}`, encodeURIComponent(String(requestParameters['user']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UsersTicketsShow200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Show tickets relation
     */
    async usersTicketsShow(requestParameters: UsersTicketsShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UsersTicketsShow200Response> {
        const response = await this.usersTicketsShowRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * Show wallComments
     */
    async usersWallCommentsRaw(requestParameters: UsersWallCommentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AchievementsComments200Response>> {
        if (requestParameters['user'] == null) {
            throw new runtime.RequiredError(
                'user',
                'Required parameter "user" was null or undefined when calling usersWallComments().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/{user}/wall-comments`.replace(`{${"user"}}`, encodeURIComponent(String(requestParameters['user']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AchievementsComments200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Show wallComments
     */
    async usersWallComments(requestParameters: UsersWallCommentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AchievementsComments200Response> {
        const response = await this.usersWallCommentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * Show wallComments relation
     */
    async usersWallCommentsShowRaw(requestParameters: UsersWallCommentsShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UsersWallCommentsShow200Response>> {
        if (requestParameters['user'] == null) {
            throw new runtime.RequiredError(
                'user',
                'Required parameter "user" was null or undefined when calling usersWallCommentsShow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/{user}/relationships/wall-comments`.replace(`{${"user"}}`, encodeURIComponent(String(requestParameters['user']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UsersWallCommentsShow200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Show wallComments relation
     */
    async usersWallCommentsShow(requestParameters: UsersWallCommentsShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UsersWallCommentsShow200Response> {
        const response = await this.usersWallCommentsShowRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const UsersIndexSortEnum = {
    Id: 'id',
    Id2: '-id',
    Points: 'points',
    Points2: '-points',
    PointsHardcore: 'pointsHardcore',
    PointsHardcore2: '-pointsHardcore',
    PointsWeighted: 'pointsWeighted',
    PointsWeighted2: '-pointsWeighted',
    YieldUnlocks: 'yieldUnlocks',
    YieldUnlocks2: '-yieldUnlocks',
    YieldPoints: 'yieldPoints',
    YieldPoints2: '-yieldPoints',
    JoinedAt: 'joinedAt',
    JoinedAt2: '-joinedAt',
    LastActivityAt: 'lastActivityAt',
    LastActivityAt2: '-lastActivityAt'
} as const;
export type UsersIndexSortEnum = typeof UsersIndexSortEnum[keyof typeof UsersIndexSortEnum];
/**
 * @export
 */
export const UsersIndexFieldsUsersEnum = {
    DisplayName: 'displayName',
    AvatarUrl: 'avatarUrl',
    Motto: 'motto',
    Points: 'points',
    PointsHardcore: 'pointsHardcore',
    PointsWeighted: 'pointsWeighted',
    YieldUnlocks: 'yieldUnlocks',
    YieldPoints: 'yieldPoints',
    JoinedAt: 'joinedAt',
    LastActivityAt: 'lastActivityAt',
    DeletedAt: 'deletedAt',
    IsUnranked: 'isUnranked',
    IsUserWallActive: 'isUserWallActive',
    RichPresence: 'richPresence',
    RichPresenceUpdatedAt: 'richPresenceUpdatedAt',
    VisibleRole: 'visibleRole',
    DisplayableRoles: 'displayableRoles',
    AchievementSetClaims: 'achievementSetClaims',
    PlayerAchievements: 'playerAchievements',
    PlayerAchievementSets: 'playerAchievementSets',
    PlayerGames: 'playerGames',
    Tickets: 'tickets',
    WallComments: 'wallComments',
    Awards: 'awards',
    Followers: 'followers',
    Following: 'following'
} as const;
export type UsersIndexFieldsUsersEnum = typeof UsersIndexFieldsUsersEnum[keyof typeof UsersIndexFieldsUsersEnum];
