/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AchievementsIndex200ResponseJsonapi } from './AchievementsIndex200ResponseJsonapi';
import {
    AchievementsIndex200ResponseJsonapiFromJSON,
    AchievementsIndex200ResponseJsonapiFromJSONTyped,
    AchievementsIndex200ResponseJsonapiToJSON,
} from './AchievementsIndex200ResponseJsonapi';
import type { ResourcesAchievementsRelationshipCommentsFetch } from './ResourcesAchievementsRelationshipCommentsFetch';
import {
    ResourcesAchievementsRelationshipCommentsFetchFromJSON,
    ResourcesAchievementsRelationshipCommentsFetchFromJSONTyped,
    ResourcesAchievementsRelationshipCommentsFetchToJSON,
} from './ResourcesAchievementsRelationshipCommentsFetch';

/**
 * 
 * @export
 * @interface AchievementsCommentsShow200Response
 */
export interface AchievementsCommentsShow200Response {
    /**
     * 
     * @type {AchievementsIndex200ResponseJsonapi}
     * @memberof AchievementsCommentsShow200Response
     */
    jsonapi: AchievementsIndex200ResponseJsonapi;
    /**
     * 
     * @type {Array<ResourcesAchievementsRelationshipCommentsFetch>}
     * @memberof AchievementsCommentsShow200Response
     */
    data: Array<ResourcesAchievementsRelationshipCommentsFetch>;
}

/**
 * Check if a given object implements the AchievementsCommentsShow200Response interface.
 */
export function instanceOfAchievementsCommentsShow200Response(value: object): value is AchievementsCommentsShow200Response {
    if (!('jsonapi' in value) || value['jsonapi'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function AchievementsCommentsShow200ResponseFromJSON(json: any): AchievementsCommentsShow200Response {
    return AchievementsCommentsShow200ResponseFromJSONTyped(json, false);
}

export function AchievementsCommentsShow200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AchievementsCommentsShow200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonapi': AchievementsIndex200ResponseJsonapiFromJSON(json['jsonapi']),
        'data': ((json['data'] as Array<any>).map(ResourcesAchievementsRelationshipCommentsFetchFromJSON)),
    };
}

export function AchievementsCommentsShow200ResponseToJSON(value?: AchievementsCommentsShow200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'jsonapi': AchievementsIndex200ResponseJsonapiToJSON(value['jsonapi']),
        'data': ((value['data'] as Array<any>).map(ResourcesAchievementsRelationshipCommentsFetchToJSON)),
    };
}

