/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AchievementsIndex200ResponseJsonapi } from './AchievementsIndex200ResponseJsonapi';
import {
    AchievementsIndex200ResponseJsonapiFromJSON,
    AchievementsIndex200ResponseJsonapiFromJSONTyped,
    AchievementsIndex200ResponseJsonapiToJSON,
} from './AchievementsIndex200ResponseJsonapi';
import type { ResourcesAchievementSetVersionsResourceFetch } from './ResourcesAchievementSetVersionsResourceFetch';
import {
    ResourcesAchievementSetVersionsResourceFetchFromJSON,
    ResourcesAchievementSetVersionsResourceFetchFromJSONTyped,
    ResourcesAchievementSetVersionsResourceFetchToJSON,
} from './ResourcesAchievementSetVersionsResourceFetch';

/**
 * 
 * @export
 * @interface AchievementSetsAchievementSetVersions200Response
 */
export interface AchievementSetsAchievementSetVersions200Response {
    /**
     * 
     * @type {AchievementsIndex200ResponseJsonapi}
     * @memberof AchievementSetsAchievementSetVersions200Response
     */
    jsonapi: AchievementsIndex200ResponseJsonapi;
    /**
     * 
     * @type {Array<ResourcesAchievementSetVersionsResourceFetch>}
     * @memberof AchievementSetsAchievementSetVersions200Response
     */
    data: Array<ResourcesAchievementSetVersionsResourceFetch>;
}

/**
 * Check if a given object implements the AchievementSetsAchievementSetVersions200Response interface.
 */
export function instanceOfAchievementSetsAchievementSetVersions200Response(value: object): value is AchievementSetsAchievementSetVersions200Response {
    if (!('jsonapi' in value) || value['jsonapi'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function AchievementSetsAchievementSetVersions200ResponseFromJSON(json: any): AchievementSetsAchievementSetVersions200Response {
    return AchievementSetsAchievementSetVersions200ResponseFromJSONTyped(json, false);
}

export function AchievementSetsAchievementSetVersions200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AchievementSetsAchievementSetVersions200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonapi': AchievementsIndex200ResponseJsonapiFromJSON(json['jsonapi']),
        'data': ((json['data'] as Array<any>).map(ResourcesAchievementSetVersionsResourceFetchFromJSON)),
    };
}

export function AchievementSetsAchievementSetVersions200ResponseToJSON(value?: AchievementSetsAchievementSetVersions200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'jsonapi': AchievementsIndex200ResponseJsonapiToJSON(value['jsonapi']),
        'data': ((value['data'] as Array<any>).map(ResourcesAchievementSetVersionsResourceFetchToJSON)),
    };
}

