/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AchievementsIndex200ResponseJsonapi } from './AchievementsIndex200ResponseJsonapi';
import {
    AchievementsIndex200ResponseJsonapiFromJSON,
    AchievementsIndex200ResponseJsonapiFromJSONTyped,
    AchievementsIndex200ResponseJsonapiToJSON,
} from './AchievementsIndex200ResponseJsonapi';
import type { ResourcesAchievementsRelationshipTicketsFetch } from './ResourcesAchievementsRelationshipTicketsFetch';
import {
    ResourcesAchievementsRelationshipTicketsFetchFromJSON,
    ResourcesAchievementsRelationshipTicketsFetchFromJSONTyped,
    ResourcesAchievementsRelationshipTicketsFetchToJSON,
} from './ResourcesAchievementsRelationshipTicketsFetch';

/**
 * 
 * @export
 * @interface AchievementsTicketsShow200Response
 */
export interface AchievementsTicketsShow200Response {
    /**
     * 
     * @type {AchievementsIndex200ResponseJsonapi}
     * @memberof AchievementsTicketsShow200Response
     */
    jsonapi: AchievementsIndex200ResponseJsonapi;
    /**
     * 
     * @type {Array<ResourcesAchievementsRelationshipTicketsFetch>}
     * @memberof AchievementsTicketsShow200Response
     */
    data: Array<ResourcesAchievementsRelationshipTicketsFetch>;
}

/**
 * Check if a given object implements the AchievementsTicketsShow200Response interface.
 */
export function instanceOfAchievementsTicketsShow200Response(value: object): value is AchievementsTicketsShow200Response {
    if (!('jsonapi' in value) || value['jsonapi'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function AchievementsTicketsShow200ResponseFromJSON(json: any): AchievementsTicketsShow200Response {
    return AchievementsTicketsShow200ResponseFromJSONTyped(json, false);
}

export function AchievementsTicketsShow200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AchievementsTicketsShow200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonapi': AchievementsIndex200ResponseJsonapiFromJSON(json['jsonapi']),
        'data': ((json['data'] as Array<any>).map(ResourcesAchievementsRelationshipTicketsFetchFromJSON)),
    };
}

export function AchievementsTicketsShow200ResponseToJSON(value?: AchievementsTicketsShow200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'jsonapi': AchievementsIndex200ResponseJsonapiToJSON(value['jsonapi']),
        'data': ((value['data'] as Array<any>).map(ResourcesAchievementsRelationshipTicketsFetchToJSON)),
    };
}

