/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AchievementSetClaimsLinks
 */
export interface AchievementSetClaimsLinks {
    /**
     * 
     * @type {string}
     * @memberof AchievementSetClaimsLinks
     */
    related?: string;
    /**
     * 
     * @type {string}
     * @memberof AchievementSetClaimsLinks
     */
    self?: string;
}

/**
 * Check if a given object implements the AchievementSetClaimsLinks interface.
 */
export function instanceOfAchievementSetClaimsLinks(value: object): value is AchievementSetClaimsLinks {
    return true;
}

export function AchievementSetClaimsLinksFromJSON(json: any): AchievementSetClaimsLinks {
    return AchievementSetClaimsLinksFromJSONTyped(json, false);
}

export function AchievementSetClaimsLinksFromJSONTyped(json: any, ignoreDiscriminator: boolean): AchievementSetClaimsLinks {
    if (json == null) {
        return json;
    }
    return {
        
        'related': json['related'] == null ? undefined : json['related'],
        'self': json['self'] == null ? undefined : json['self'],
    };
}

export function AchievementSetClaimsLinksToJSON(value?: AchievementSetClaimsLinks | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'related': value['related'],
        'self': value['self'],
    };
}

