/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AchievementSetVersionsLinks } from './AchievementSetVersionsLinks';
import {
    AchievementSetVersionsLinksFromJSON,
    AchievementSetVersionsLinksFromJSONTyped,
    AchievementSetVersionsLinksToJSON,
} from './AchievementSetVersionsLinks';

/**
 * May include a list of IDs of relevant items in the `data` field. To retrieve these listed items as well, add "achievementSetVersions" to the "include" query parameter; results will be found in `.included`.
 * @export
 * @interface AchievementSetVersions
 */
export interface AchievementSetVersions {
    /**
     * 
     * @type {AchievementSetVersionsLinks}
     * @memberof AchievementSetVersions
     */
    links?: AchievementSetVersionsLinks;
}

/**
 * Check if a given object implements the AchievementSetVersions interface.
 */
export function instanceOfAchievementSetVersions(value: object): value is AchievementSetVersions {
    return true;
}

export function AchievementSetVersionsFromJSON(json: any): AchievementSetVersions {
    return AchievementSetVersionsFromJSONTyped(json, false);
}

export function AchievementSetVersionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AchievementSetVersions {
    if (json == null) {
        return json;
    }
    return {
        
        'links': json['links'] == null ? undefined : AchievementSetVersionsLinksFromJSON(json['links']),
    };
}

export function AchievementSetVersionsToJSON(value?: AchievementSetVersions | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'links': AchievementSetVersionsLinksToJSON(value['links']),
    };
}

