/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HelperJsonapi } from './HelperJsonapi';
import {
    HelperJsonapiFromJSON,
    HelperJsonapiFromJSONTyped,
    HelperJsonapiToJSON,
} from './HelperJsonapi';

/**
 * 
 * @export
 * @interface AchievementsIndex400Response
 */
export interface AchievementsIndex400Response {
    /**
     * 
     * @type {HelperJsonapi}
     * @memberof AchievementsIndex400Response
     */
    helperJsonapi?: HelperJsonapi;
    /**
     * 
     * @type {Array<Error>}
     * @memberof AchievementsIndex400Response
     */
    helperErrors?: Array<Error>;
}

/**
 * Check if a given object implements the AchievementsIndex400Response interface.
 */
export function instanceOfAchievementsIndex400Response(value: object): value is AchievementsIndex400Response {
    return true;
}

export function AchievementsIndex400ResponseFromJSON(json: any): AchievementsIndex400Response {
    return AchievementsIndex400ResponseFromJSONTyped(json, false);
}

export function AchievementsIndex400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AchievementsIndex400Response {
    if (json == null) {
        return json;
    }
    return {
        
        'helperJsonapi': json['helper.jsonapi'] == null ? undefined : HelperJsonapiFromJSON(json['helper.jsonapi']),
        'helperErrors': json['helper.errors'] == null ? undefined : json['helper.errors'],
    };
}

export function AchievementsIndex400ResponseToJSON(value?: AchievementsIndex400Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'helper.jsonapi': HelperJsonapiToJSON(value['helperJsonapi']),
        'helper.errors': value['helperErrors'],
    };
}

