/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResourceAchievementSetVersionsFetch } from './ResourceAchievementSetVersionsFetch';
import {
    ResourceAchievementSetVersionsFetchFromJSON,
    ResourceAchievementSetVersionsFetchFromJSONTyped,
    ResourceAchievementSetVersionsFetchToJSON,
} from './ResourceAchievementSetVersionsFetch';
import type { ResourceGamesFetch } from './ResourceGamesFetch';
import {
    ResourceGamesFetchFromJSON,
    ResourceGamesFetchFromJSONTyped,
    ResourceGamesFetchToJSON,
} from './ResourceGamesFetch';
import type { ResourceAchievementSetVersionsFetchAttributes } from './ResourceAchievementSetVersionsFetchAttributes';
import {
    ResourceAchievementSetVersionsFetchAttributesFromJSON,
    ResourceAchievementSetVersionsFetchAttributesFromJSONTyped,
    ResourceAchievementSetVersionsFetchAttributesToJSON,
} from './ResourceAchievementSetVersionsFetchAttributes';
import type { ResourceAchievementSetVersionsFetchRelationships } from './ResourceAchievementSetVersionsFetchRelationships';
import {
    ResourceAchievementSetVersionsFetchRelationshipsFromJSON,
    ResourceAchievementSetVersionsFetchRelationshipsFromJSONTyped,
    ResourceAchievementSetVersionsFetchRelationshipsToJSON,
} from './ResourceAchievementSetVersionsFetchRelationships';

/**
 * 
 * @export
 * @interface AchievementSetsShow200ResponseIncludedInner
 */
export interface AchievementSetsShow200ResponseIncludedInner {
    /**
     * 
     * @type {string}
     * @memberof AchievementSetsShow200ResponseIncludedInner
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof AchievementSetsShow200ResponseIncludedInner
     */
    id: string;
    /**
     * 
     * @type {ResourceAchievementSetVersionsFetchAttributes}
     * @memberof AchievementSetsShow200ResponseIncludedInner
     */
    attributes: ResourceAchievementSetVersionsFetchAttributes;
    /**
     * 
     * @type {ResourceAchievementSetVersionsFetchRelationships}
     * @memberof AchievementSetsShow200ResponseIncludedInner
     */
    relationships?: ResourceAchievementSetVersionsFetchRelationships;
}

/**
 * Check if a given object implements the AchievementSetsShow200ResponseIncludedInner interface.
 */
export function instanceOfAchievementSetsShow200ResponseIncludedInner(value: object): value is AchievementSetsShow200ResponseIncludedInner {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('attributes' in value) || value['attributes'] === undefined) return false;
    return true;
}

export function AchievementSetsShow200ResponseIncludedInnerFromJSON(json: any): AchievementSetsShow200ResponseIncludedInner {
    return AchievementSetsShow200ResponseIncludedInnerFromJSONTyped(json, false);
}

export function AchievementSetsShow200ResponseIncludedInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AchievementSetsShow200ResponseIncludedInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': ResourceAchievementSetVersionsFetchAttributesFromJSON(json['attributes']),
        'relationships': json['relationships'] == null ? undefined : ResourceAchievementSetVersionsFetchRelationshipsFromJSON(json['relationships']),
    };
}

export function AchievementSetsShow200ResponseIncludedInnerToJSON(value?: AchievementSetsShow200ResponseIncludedInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'id': value['id'],
        'attributes': ResourceAchievementSetVersionsFetchAttributesToJSON(value['attributes']),
        'relationships': ResourceAchievementSetVersionsFetchRelationshipsToJSON(value['relationships']),
    };
}

