/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AchievementSetClaimsLinks } from './AchievementSetClaimsLinks';
import {
    AchievementSetClaimsLinksFromJSON,
    AchievementSetClaimsLinksFromJSONTyped,
    AchievementSetClaimsLinksToJSON,
} from './AchievementSetClaimsLinks';

/**
 * May include a list of IDs of relevant items in the `data` field. To retrieve these listed items as well, add "achievementSetClaims" to the "include" query parameter; results will be found in `.included`.
 * @export
 * @interface AchievementSetClaims
 */
export interface AchievementSetClaims {
    /**
     * 
     * @type {AchievementSetClaimsLinks}
     * @memberof AchievementSetClaims
     */
    links?: AchievementSetClaimsLinks;
}

/**
 * Check if a given object implements the AchievementSetClaims interface.
 */
export function instanceOfAchievementSetClaims(value: object): value is AchievementSetClaims {
    return true;
}

export function AchievementSetClaimsFromJSON(json: any): AchievementSetClaims {
    return AchievementSetClaimsFromJSONTyped(json, false);
}

export function AchievementSetClaimsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AchievementSetClaims {
    if (json == null) {
        return json;
    }
    return {
        
        'links': json['links'] == null ? undefined : AchievementSetClaimsLinksFromJSON(json['links']),
    };
}

export function AchievementSetClaimsToJSON(value?: AchievementSetClaims | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'links': AchievementSetClaimsLinksToJSON(value['links']),
    };
}

