/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AchievementsIndex200ResponseJsonapi } from './AchievementsIndex200ResponseJsonapi';
import {
    AchievementsIndex200ResponseJsonapiFromJSON,
    AchievementsIndex200ResponseJsonapiFromJSONTyped,
    AchievementsIndex200ResponseJsonapiToJSON,
} from './AchievementsIndex200ResponseJsonapi';
import type { ResourcesCommentsResourceFetch } from './ResourcesCommentsResourceFetch';
import {
    ResourcesCommentsResourceFetchFromJSON,
    ResourcesCommentsResourceFetchFromJSONTyped,
    ResourcesCommentsResourceFetchToJSON,
} from './ResourcesCommentsResourceFetch';

/**
 * 
 * @export
 * @interface AchievementsComments200Response
 */
export interface AchievementsComments200Response {
    /**
     * 
     * @type {AchievementsIndex200ResponseJsonapi}
     * @memberof AchievementsComments200Response
     */
    jsonapi: AchievementsIndex200ResponseJsonapi;
    /**
     * 
     * @type {Array<ResourcesCommentsResourceFetch>}
     * @memberof AchievementsComments200Response
     */
    data: Array<ResourcesCommentsResourceFetch>;
}

/**
 * Check if a given object implements the AchievementsComments200Response interface.
 */
export function instanceOfAchievementsComments200Response(value: object): value is AchievementsComments200Response {
    if (!('jsonapi' in value) || value['jsonapi'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function AchievementsComments200ResponseFromJSON(json: any): AchievementsComments200Response {
    return AchievementsComments200ResponseFromJSONTyped(json, false);
}

export function AchievementsComments200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AchievementsComments200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonapi': AchievementsIndex200ResponseJsonapiFromJSON(json['jsonapi']),
        'data': ((json['data'] as Array<any>).map(ResourcesCommentsResourceFetchFromJSON)),
    };
}

export function AchievementsComments200ResponseToJSON(value?: AchievementsComments200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'jsonapi': AchievementsIndex200ResponseJsonapiToJSON(value['jsonapi']),
        'data': ((value['data'] as Array<any>).map(ResourcesCommentsResourceFetchToJSON)),
    };
}

