/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AchievementSetClaims1Links
 */
export interface AchievementSetClaims1Links {
    /**
     * 
     * @type {string}
     * @memberof AchievementSetClaims1Links
     */
    related?: string;
    /**
     * 
     * @type {string}
     * @memberof AchievementSetClaims1Links
     */
    self?: string;
}

/**
 * Check if a given object implements the AchievementSetClaims1Links interface.
 */
export function instanceOfAchievementSetClaims1Links(value: object): value is AchievementSetClaims1Links {
    return true;
}

export function AchievementSetClaims1LinksFromJSON(json: any): AchievementSetClaims1Links {
    return AchievementSetClaims1LinksFromJSONTyped(json, false);
}

export function AchievementSetClaims1LinksFromJSONTyped(json: any, ignoreDiscriminator: boolean): AchievementSetClaims1Links {
    if (json == null) {
        return json;
    }
    return {
        
        'related': json['related'] == null ? undefined : json['related'],
        'self': json['self'] == null ? undefined : json['self'],
    };
}

export function AchievementSetClaims1LinksToJSON(value?: AchievementSetClaims1Links | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'related': value['related'],
        'self': value['self'],
    };
}

