/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AchievementLinks
 */
export interface AchievementLinks {
    /**
     * 
     * @type {string}
     * @memberof AchievementLinks
     */
    related?: string;
    /**
     * 
     * @type {string}
     * @memberof AchievementLinks
     */
    self?: string;
}

/**
 * Check if a given object implements the AchievementLinks interface.
 */
export function instanceOfAchievementLinks(value: object): value is AchievementLinks {
    return true;
}

export function AchievementLinksFromJSON(json: any): AchievementLinks {
    return AchievementLinksFromJSONTyped(json, false);
}

export function AchievementLinksFromJSONTyped(json: any, ignoreDiscriminator: boolean): AchievementLinks {
    if (json == null) {
        return json;
    }
    return {
        
        'related': json['related'] == null ? undefined : json['related'],
        'self': json['self'] == null ? undefined : json['self'],
    };
}

export function AchievementLinksToJSON(value?: AchievementLinks | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'related': value['related'],
        'self': value['self'],
    };
}

