/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AchievementsIndex200ResponseJsonapi } from './AchievementsIndex200ResponseJsonapi';
import {
    AchievementsIndex200ResponseJsonapiFromJSON,
    AchievementsIndex200ResponseJsonapiFromJSONTyped,
    AchievementsIndex200ResponseJsonapiToJSON,
} from './AchievementsIndex200ResponseJsonapi';
import type { ResourcesTicketsResourceFetch } from './ResourcesTicketsResourceFetch';
import {
    ResourcesTicketsResourceFetchFromJSON,
    ResourcesTicketsResourceFetchFromJSONTyped,
    ResourcesTicketsResourceFetchToJSON,
} from './ResourcesTicketsResourceFetch';

/**
 * 
 * @export
 * @interface AchievementsTickets200Response
 */
export interface AchievementsTickets200Response {
    /**
     * 
     * @type {AchievementsIndex200ResponseJsonapi}
     * @memberof AchievementsTickets200Response
     */
    jsonapi: AchievementsIndex200ResponseJsonapi;
    /**
     * 
     * @type {Array<ResourcesTicketsResourceFetch>}
     * @memberof AchievementsTickets200Response
     */
    data: Array<ResourcesTicketsResourceFetch>;
}

/**
 * Check if a given object implements the AchievementsTickets200Response interface.
 */
export function instanceOfAchievementsTickets200Response(value: object): value is AchievementsTickets200Response {
    if (!('jsonapi' in value) || value['jsonapi'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function AchievementsTickets200ResponseFromJSON(json: any): AchievementsTickets200Response {
    return AchievementsTickets200ResponseFromJSONTyped(json, false);
}

export function AchievementsTickets200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AchievementsTickets200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonapi': AchievementsIndex200ResponseJsonapiFromJSON(json['jsonapi']),
        'data': ((json['data'] as Array<any>).map(ResourcesTicketsResourceFetchFromJSON)),
    };
}

export function AchievementsTickets200ResponseToJSON(value?: AchievementsTickets200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'jsonapi': AchievementsIndex200ResponseJsonapiToJSON(value['jsonapi']),
        'data': ((value['data'] as Array<any>).map(ResourcesTicketsResourceFetchToJSON)),
    };
}

