/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AchievementsIndex200ResponseJsonapi } from './AchievementsIndex200ResponseJsonapi';
import {
    AchievementsIndex200ResponseJsonapiFromJSON,
    AchievementsIndex200ResponseJsonapiFromJSONTyped,
    AchievementsIndex200ResponseJsonapiToJSON,
} from './AchievementsIndex200ResponseJsonapi';
import type { ResourcesAchievementsResourceFetch } from './ResourcesAchievementsResourceFetch';
import {
    ResourcesAchievementsResourceFetchFromJSON,
    ResourcesAchievementsResourceFetchFromJSONTyped,
    ResourcesAchievementsResourceFetchToJSON,
} from './ResourcesAchievementsResourceFetch';
import type { AchievementsIndex200ResponseIncludedInner } from './AchievementsIndex200ResponseIncludedInner';
import {
    AchievementsIndex200ResponseIncludedInnerFromJSON,
    AchievementsIndex200ResponseIncludedInnerFromJSONTyped,
    AchievementsIndex200ResponseIncludedInnerToJSON,
} from './AchievementsIndex200ResponseIncludedInner';

/**
 * 
 * @export
 * @interface AchievementsShow200Response
 */
export interface AchievementsShow200Response {
    /**
     * 
     * @type {AchievementsIndex200ResponseJsonapi}
     * @memberof AchievementsShow200Response
     */
    jsonapi: AchievementsIndex200ResponseJsonapi;
    /**
     * 
     * @type {ResourcesAchievementsResourceFetch}
     * @memberof AchievementsShow200Response
     */
    data: ResourcesAchievementsResourceFetch;
    /**
     * 
     * @type {Array<AchievementsIndex200ResponseIncludedInner>}
     * @memberof AchievementsShow200Response
     */
    included?: Array<AchievementsIndex200ResponseIncludedInner>;
}

/**
 * Check if a given object implements the AchievementsShow200Response interface.
 */
export function instanceOfAchievementsShow200Response(value: object): value is AchievementsShow200Response {
    if (!('jsonapi' in value) || value['jsonapi'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function AchievementsShow200ResponseFromJSON(json: any): AchievementsShow200Response {
    return AchievementsShow200ResponseFromJSONTyped(json, false);
}

export function AchievementsShow200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AchievementsShow200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonapi': AchievementsIndex200ResponseJsonapiFromJSON(json['jsonapi']),
        'data': ResourcesAchievementsResourceFetchFromJSON(json['data']),
        'included': json['included'] == null ? undefined : ((json['included'] as Array<any>).map(AchievementsIndex200ResponseIncludedInnerFromJSON)),
    };
}

export function AchievementsShow200ResponseToJSON(value?: AchievementsShow200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'jsonapi': AchievementsIndex200ResponseJsonapiToJSON(value['jsonapi']),
        'data': ResourcesAchievementsResourceFetchToJSON(value['data']),
        'included': value['included'] == null ? undefined : ((value['included'] as Array<any>).map(AchievementsIndex200ResponseIncludedInnerToJSON)),
    };
}

