/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AchievementsIndex200ResponseJsonapi } from './AchievementsIndex200ResponseJsonapi';
import {
    AchievementsIndex200ResponseJsonapiFromJSON,
    AchievementsIndex200ResponseJsonapiFromJSONTyped,
    AchievementsIndex200ResponseJsonapiToJSON,
} from './AchievementsIndex200ResponseJsonapi';
import type { ResourcesAchievementsRelationshipPlayerAchievementsFetch } from './ResourcesAchievementsRelationshipPlayerAchievementsFetch';
import {
    ResourcesAchievementsRelationshipPlayerAchievementsFetchFromJSON,
    ResourcesAchievementsRelationshipPlayerAchievementsFetchFromJSONTyped,
    ResourcesAchievementsRelationshipPlayerAchievementsFetchToJSON,
} from './ResourcesAchievementsRelationshipPlayerAchievementsFetch';

/**
 * 
 * @export
 * @interface AchievementsPlayerAchievementsShow200Response
 */
export interface AchievementsPlayerAchievementsShow200Response {
    /**
     * 
     * @type {AchievementsIndex200ResponseJsonapi}
     * @memberof AchievementsPlayerAchievementsShow200Response
     */
    jsonapi: AchievementsIndex200ResponseJsonapi;
    /**
     * 
     * @type {Array<ResourcesAchievementsRelationshipPlayerAchievementsFetch>}
     * @memberof AchievementsPlayerAchievementsShow200Response
     */
    data: Array<ResourcesAchievementsRelationshipPlayerAchievementsFetch>;
}

/**
 * Check if a given object implements the AchievementsPlayerAchievementsShow200Response interface.
 */
export function instanceOfAchievementsPlayerAchievementsShow200Response(value: object): value is AchievementsPlayerAchievementsShow200Response {
    if (!('jsonapi' in value) || value['jsonapi'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function AchievementsPlayerAchievementsShow200ResponseFromJSON(json: any): AchievementsPlayerAchievementsShow200Response {
    return AchievementsPlayerAchievementsShow200ResponseFromJSONTyped(json, false);
}

export function AchievementsPlayerAchievementsShow200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AchievementsPlayerAchievementsShow200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonapi': AchievementsIndex200ResponseJsonapiFromJSON(json['jsonapi']),
        'data': ((json['data'] as Array<any>).map(ResourcesAchievementsRelationshipPlayerAchievementsFetchFromJSON)),
    };
}

export function AchievementsPlayerAchievementsShow200ResponseToJSON(value?: AchievementsPlayerAchievementsShow200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'jsonapi': AchievementsIndex200ResponseJsonapiToJSON(value['jsonapi']),
        'data': ((value['data'] as Array<any>).map(ResourcesAchievementsRelationshipPlayerAchievementsFetchToJSON)),
    };
}

