/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AchievementSetsLinks } from './AchievementSetsLinks';
import {
    AchievementSetsLinksFromJSON,
    AchievementSetsLinksFromJSONTyped,
    AchievementSetsLinksToJSON,
} from './AchievementSetsLinks';

/**
 * May include a list of IDs of relevant items in the `data` field. To retrieve these listed items as well, add "achievementSets" to the "include" query parameter; results will be found in `.included`.
 * @export
 * @interface AchievementSets
 */
export interface AchievementSets {
    /**
     * 
     * @type {AchievementSetsLinks}
     * @memberof AchievementSets
     */
    links?: AchievementSetsLinks;
}

/**
 * Check if a given object implements the AchievementSets interface.
 */
export function instanceOfAchievementSets(value: object): value is AchievementSets {
    return true;
}

export function AchievementSetsFromJSON(json: any): AchievementSets {
    return AchievementSetsFromJSONTyped(json, false);
}

export function AchievementSetsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AchievementSets {
    if (json == null) {
        return json;
    }
    return {
        
        'links': json['links'] == null ? undefined : AchievementSetsLinksFromJSON(json['links']),
    };
}

export function AchievementSetsToJSON(value?: AchievementSets | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'links': AchievementSetsLinksToJSON(value['links']),
    };
}

