/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResourceAchievementSetFetchAttributes } from './ResourceAchievementSetFetchAttributes';
import {
    ResourceAchievementSetFetchAttributesFromJSON,
    ResourceAchievementSetFetchAttributesFromJSONTyped,
    ResourceAchievementSetFetchAttributesToJSON,
} from './ResourceAchievementSetFetchAttributes';
import type { ResourceAchievementSetFetchRelationships } from './ResourceAchievementSetFetchRelationships';
import {
    ResourceAchievementSetFetchRelationshipsFromJSON,
    ResourceAchievementSetFetchRelationshipsFromJSONTyped,
    ResourceAchievementSetFetchRelationshipsToJSON,
} from './ResourceAchievementSetFetchRelationships';
import type { ResourceAchievementSetFetch } from './ResourceAchievementSetFetch';
import {
    ResourceAchievementSetFetchFromJSON,
    ResourceAchievementSetFetchFromJSONTyped,
    ResourceAchievementSetFetchToJSON,
} from './ResourceAchievementSetFetch';

/**
 * 
 * @export
 * @interface AchievementSetVersionsIndex200ResponseIncludedInner
 */
export interface AchievementSetVersionsIndex200ResponseIncludedInner {
    /**
     * 
     * @type {string}
     * @memberof AchievementSetVersionsIndex200ResponseIncludedInner
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof AchievementSetVersionsIndex200ResponseIncludedInner
     */
    id: string;
    /**
     * 
     * @type {ResourceAchievementSetFetchAttributes}
     * @memberof AchievementSetVersionsIndex200ResponseIncludedInner
     */
    attributes: ResourceAchievementSetFetchAttributes;
    /**
     * 
     * @type {ResourceAchievementSetFetchRelationships}
     * @memberof AchievementSetVersionsIndex200ResponseIncludedInner
     */
    relationships?: ResourceAchievementSetFetchRelationships;
}

/**
 * Check if a given object implements the AchievementSetVersionsIndex200ResponseIncludedInner interface.
 */
export function instanceOfAchievementSetVersionsIndex200ResponseIncludedInner(value: object): value is AchievementSetVersionsIndex200ResponseIncludedInner {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('attributes' in value) || value['attributes'] === undefined) return false;
    return true;
}

export function AchievementSetVersionsIndex200ResponseIncludedInnerFromJSON(json: any): AchievementSetVersionsIndex200ResponseIncludedInner {
    return AchievementSetVersionsIndex200ResponseIncludedInnerFromJSONTyped(json, false);
}

export function AchievementSetVersionsIndex200ResponseIncludedInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AchievementSetVersionsIndex200ResponseIncludedInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': ResourceAchievementSetFetchAttributesFromJSON(json['attributes']),
        'relationships': json['relationships'] == null ? undefined : ResourceAchievementSetFetchRelationshipsFromJSON(json['relationships']),
    };
}

export function AchievementSetVersionsIndex200ResponseIncludedInnerToJSON(value?: AchievementSetVersionsIndex200ResponseIncludedInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'id': value['id'],
        'attributes': ResourceAchievementSetFetchAttributesToJSON(value['attributes']),
        'relationships': ResourceAchievementSetFetchRelationshipsToJSON(value['relationships']),
    };
}

