/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Author1Links } from './Author1Links';
import {
    Author1LinksFromJSON,
    Author1LinksFromJSONTyped,
    Author1LinksToJSON,
} from './Author1Links';

/**
 * May include a list of IDs of relevant items in the `data` field. To retrieve these listed items as well, add "author" to the "include" query parameter; results will be found in `.included`.
 * @export
 * @interface Author1
 */
export interface Author1 {
    /**
     * 
     * @type {Author1Links}
     * @memberof Author1
     */
    links?: Author1Links;
}

/**
 * Check if a given object implements the Author1 interface.
 */
export function instanceOfAuthor1(value: object): value is Author1 {
    return true;
}

export function Author1FromJSON(json: any): Author1 {
    return Author1FromJSONTyped(json, false);
}

export function Author1FromJSONTyped(json: any, ignoreDiscriminator: boolean): Author1 {
    if (json == null) {
        return json;
    }
    return {
        
        'links': json['links'] == null ? undefined : Author1LinksFromJSON(json['links']),
    };
}

export function Author1ToJSON(value?: Author1 | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'links': Author1LinksToJSON(value['links']),
    };
}

