/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommentsLinks } from './CommentsLinks';
import {
    CommentsLinksFromJSON,
    CommentsLinksFromJSONTyped,
    CommentsLinksToJSON,
} from './CommentsLinks';

/**
 * May include a list of IDs of relevant items in the `data` field. To retrieve these listed items as well, add "comments" to the "include" query parameter; results will be found in `.included`.
 * @export
 * @interface Comments
 */
export interface Comments {
    /**
     * 
     * @type {CommentsLinks}
     * @memberof Comments
     */
    links?: CommentsLinks;
}

/**
 * Check if a given object implements the Comments interface.
 */
export function instanceOfComments(value: object): value is Comments {
    return true;
}

export function CommentsFromJSON(json: any): Comments {
    return CommentsFromJSONTyped(json, false);
}

export function CommentsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Comments {
    if (json == null) {
        return json;
    }
    return {
        
        'links': json['links'] == null ? undefined : CommentsLinksFromJSON(json['links']),
    };
}

export function CommentsToJSON(value?: Comments | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'links': CommentsLinksToJSON(value['links']),
    };
}

