/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommentsLinks
 */
export interface CommentsLinks {
    /**
     * 
     * @type {string}
     * @memberof CommentsLinks
     */
    related?: string;
    /**
     * 
     * @type {string}
     * @memberof CommentsLinks
     */
    self?: string;
}

/**
 * Check if a given object implements the CommentsLinks interface.
 */
export function instanceOfCommentsLinks(value: object): value is CommentsLinks {
    return true;
}

export function CommentsLinksFromJSON(json: any): CommentsLinks {
    return CommentsLinksFromJSONTyped(json, false);
}

export function CommentsLinksFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentsLinks {
    if (json == null) {
        return json;
    }
    return {
        
        'related': json['related'] == null ? undefined : json['related'],
        'self': json['self'] == null ? undefined : json['self'],
    };
}

export function CommentsLinksToJSON(value?: CommentsLinks | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'related': value['related'],
        'self': value['self'],
    };
}

