/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeveloperLinks
 */
export interface DeveloperLinks {
    /**
     * 
     * @type {string}
     * @memberof DeveloperLinks
     */
    related?: string;
    /**
     * 
     * @type {string}
     * @memberof DeveloperLinks
     */
    self?: string;
}

/**
 * Check if a given object implements the DeveloperLinks interface.
 */
export function instanceOfDeveloperLinks(value: object): value is DeveloperLinks {
    return true;
}

export function DeveloperLinksFromJSON(json: any): DeveloperLinks {
    return DeveloperLinksFromJSONTyped(json, false);
}

export function DeveloperLinksFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeveloperLinks {
    if (json == null) {
        return json;
    }
    return {
        
        'related': json['related'] == null ? undefined : json['related'],
        'self': json['self'] == null ? undefined : json['self'],
    };
}

export function DeveloperLinksToJSON(value?: DeveloperLinks | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'related': value['related'],
        'self': value['self'],
    };
}

