/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DeveloperLinks } from './DeveloperLinks';
import {
    DeveloperLinksFromJSON,
    DeveloperLinksFromJSONTyped,
    DeveloperLinksToJSON,
} from './DeveloperLinks';

/**
 * May include a list of IDs of relevant items in the `data` field. To retrieve these listed items as well, add "developer" to the "include" query parameter; results will be found in `.included`.
 * @export
 * @interface Developer
 */
export interface Developer {
    /**
     * 
     * @type {DeveloperLinks}
     * @memberof Developer
     */
    links?: DeveloperLinks;
}

/**
 * Check if a given object implements the Developer interface.
 */
export function instanceOfDeveloper(value: object): value is Developer {
    return true;
}

export function DeveloperFromJSON(json: any): Developer {
    return DeveloperFromJSONTyped(json, false);
}

export function DeveloperFromJSONTyped(json: any, ignoreDiscriminator: boolean): Developer {
    if (json == null) {
        return json;
    }
    return {
        
        'links': json['links'] == null ? undefined : DeveloperLinksFromJSON(json['links']),
    };
}

export function DeveloperToJSON(value?: Developer | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'links': DeveloperLinksToJSON(value['links']),
    };
}

