/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EntriesLinks
 */
export interface EntriesLinks {
    /**
     * 
     * @type {string}
     * @memberof EntriesLinks
     */
    related?: string;
    /**
     * 
     * @type {string}
     * @memberof EntriesLinks
     */
    self?: string;
}

/**
 * Check if a given object implements the EntriesLinks interface.
 */
export function instanceOfEntriesLinks(value: object): value is EntriesLinks {
    return true;
}

export function EntriesLinksFromJSON(json: any): EntriesLinks {
    return EntriesLinksFromJSONTyped(json, false);
}

export function EntriesLinksFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntriesLinks {
    if (json == null) {
        return json;
    }
    return {
        
        'related': json['related'] == null ? undefined : json['related'],
        'self': json['self'] == null ? undefined : json['self'],
    };
}

export function EntriesLinksToJSON(value?: EntriesLinks | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'related': value['related'],
        'self': value['self'],
    };
}

