/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResourceAwardsFetchAttributes } from './ResourceAwardsFetchAttributes';
import {
    ResourceAwardsFetchAttributesFromJSON,
    ResourceAwardsFetchAttributesFromJSONTyped,
    ResourceAwardsFetchAttributesToJSON,
} from './ResourceAwardsFetchAttributes';
import type { ResourceAwardsFetch } from './ResourceAwardsFetch';
import {
    ResourceAwardsFetchFromJSON,
    ResourceAwardsFetchFromJSONTyped,
    ResourceAwardsFetchToJSON,
} from './ResourceAwardsFetch';
import type { ResourceAwardsFetchRelationships } from './ResourceAwardsFetchRelationships';
import {
    ResourceAwardsFetchRelationshipsFromJSON,
    ResourceAwardsFetchRelationshipsFromJSONTyped,
    ResourceAwardsFetchRelationshipsToJSON,
} from './ResourceAwardsFetchRelationships';

/**
 * 
 * @export
 * @interface EventsIndex200ResponseIncludedInner
 */
export interface EventsIndex200ResponseIncludedInner {
    /**
     * 
     * @type {string}
     * @memberof EventsIndex200ResponseIncludedInner
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof EventsIndex200ResponseIncludedInner
     */
    id: string;
    /**
     * 
     * @type {ResourceAwardsFetchAttributes}
     * @memberof EventsIndex200ResponseIncludedInner
     */
    attributes: ResourceAwardsFetchAttributes;
    /**
     * 
     * @type {ResourceAwardsFetchRelationships}
     * @memberof EventsIndex200ResponseIncludedInner
     */
    relationships?: ResourceAwardsFetchRelationships;
}

/**
 * Check if a given object implements the EventsIndex200ResponseIncludedInner interface.
 */
export function instanceOfEventsIndex200ResponseIncludedInner(value: object): value is EventsIndex200ResponseIncludedInner {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('attributes' in value) || value['attributes'] === undefined) return false;
    return true;
}

export function EventsIndex200ResponseIncludedInnerFromJSON(json: any): EventsIndex200ResponseIncludedInner {
    return EventsIndex200ResponseIncludedInnerFromJSONTyped(json, false);
}

export function EventsIndex200ResponseIncludedInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventsIndex200ResponseIncludedInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': ResourceAwardsFetchAttributesFromJSON(json['attributes']),
        'relationships': json['relationships'] == null ? undefined : ResourceAwardsFetchRelationshipsFromJSON(json['relationships']),
    };
}

export function EventsIndex200ResponseIncludedInnerToJSON(value?: EventsIndex200ResponseIncludedInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'id': value['id'],
        'attributes': ResourceAwardsFetchAttributesToJSON(value['attributes']),
        'relationships': ResourceAwardsFetchRelationshipsToJSON(value['relationships']),
    };
}

