/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EventLinks } from './EventLinks';
import {
    EventLinksFromJSON,
    EventLinksFromJSONTyped,
    EventLinksToJSON,
} from './EventLinks';

/**
 * May include a list of IDs of relevant items in the `data` field. To retrieve these listed items as well, add "event" to the "include" query parameter; results will be found in `.included`.
 * @export
 * @interface Event
 */
export interface Event {
    /**
     * 
     * @type {EventLinks}
     * @memberof Event
     */
    links?: EventLinks;
}

/**
 * Check if a given object implements the Event interface.
 */
export function instanceOfEvent(value: object): value is Event {
    return true;
}

export function EventFromJSON(json: any): Event {
    return EventFromJSONTyped(json, false);
}

export function EventFromJSONTyped(json: any, ignoreDiscriminator: boolean): Event {
    if (json == null) {
        return json;
    }
    return {
        
        'links': json['links'] == null ? undefined : EventLinksFromJSON(json['links']),
    };
}

export function EventToJSON(value?: Event | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'links': EventLinksToJSON(value['links']),
    };
}

