/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FollowingLinks
 */
export interface FollowingLinks {
    /**
     * 
     * @type {string}
     * @memberof FollowingLinks
     */
    related?: string;
    /**
     * 
     * @type {string}
     * @memberof FollowingLinks
     */
    self?: string;
}

/**
 * Check if a given object implements the FollowingLinks interface.
 */
export function instanceOfFollowingLinks(value: object): value is FollowingLinks {
    return true;
}

export function FollowingLinksFromJSON(json: any): FollowingLinks {
    return FollowingLinksFromJSONTyped(json, false);
}

export function FollowingLinksFromJSONTyped(json: any, ignoreDiscriminator: boolean): FollowingLinks {
    if (json == null) {
        return json;
    }
    return {
        
        'related': json['related'] == null ? undefined : json['related'],
        'self': json['self'] == null ? undefined : json['self'],
    };
}

export function FollowingLinksToJSON(value?: FollowingLinks | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'related': value['related'],
        'self': value['self'],
    };
}

