/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AchievementsIndex200ResponseJsonapi } from './AchievementsIndex200ResponseJsonapi';
import {
    AchievementsIndex200ResponseJsonapiFromJSON,
    AchievementsIndex200ResponseJsonapiFromJSONTyped,
    AchievementsIndex200ResponseJsonapiToJSON,
} from './AchievementsIndex200ResponseJsonapi';
import type { ResourcesGamesRelationshipAchievementSetClaimsFetch } from './ResourcesGamesRelationshipAchievementSetClaimsFetch';
import {
    ResourcesGamesRelationshipAchievementSetClaimsFetchFromJSON,
    ResourcesGamesRelationshipAchievementSetClaimsFetchFromJSONTyped,
    ResourcesGamesRelationshipAchievementSetClaimsFetchToJSON,
} from './ResourcesGamesRelationshipAchievementSetClaimsFetch';

/**
 * 
 * @export
 * @interface GamesAchievementSetClaimsShow200Response
 */
export interface GamesAchievementSetClaimsShow200Response {
    /**
     * 
     * @type {AchievementsIndex200ResponseJsonapi}
     * @memberof GamesAchievementSetClaimsShow200Response
     */
    jsonapi: AchievementsIndex200ResponseJsonapi;
    /**
     * 
     * @type {Array<ResourcesGamesRelationshipAchievementSetClaimsFetch>}
     * @memberof GamesAchievementSetClaimsShow200Response
     */
    data: Array<ResourcesGamesRelationshipAchievementSetClaimsFetch>;
}

/**
 * Check if a given object implements the GamesAchievementSetClaimsShow200Response interface.
 */
export function instanceOfGamesAchievementSetClaimsShow200Response(value: object): value is GamesAchievementSetClaimsShow200Response {
    if (!('jsonapi' in value) || value['jsonapi'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GamesAchievementSetClaimsShow200ResponseFromJSON(json: any): GamesAchievementSetClaimsShow200Response {
    return GamesAchievementSetClaimsShow200ResponseFromJSONTyped(json, false);
}

export function GamesAchievementSetClaimsShow200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GamesAchievementSetClaimsShow200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonapi': AchievementsIndex200ResponseJsonapiFromJSON(json['jsonapi']),
        'data': ((json['data'] as Array<any>).map(ResourcesGamesRelationshipAchievementSetClaimsFetchFromJSON)),
    };
}

export function GamesAchievementSetClaimsShow200ResponseToJSON(value?: GamesAchievementSetClaimsShow200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'jsonapi': AchievementsIndex200ResponseJsonapiToJSON(value['jsonapi']),
        'data': ((value['data'] as Array<any>).map(ResourcesGamesRelationshipAchievementSetClaimsFetchToJSON)),
    };
}

