/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GamesLinks } from './GamesLinks';
import {
    GamesLinksFromJSON,
    GamesLinksFromJSONTyped,
    GamesLinksToJSON,
} from './GamesLinks';

/**
 * May include a list of IDs of relevant items in the `data` field. To retrieve these listed items as well, add "game" to the "include" query parameter; results will be found in `.included`.
 * @export
 * @interface Game
 */
export interface Game {
    /**
     * 
     * @type {GamesLinks}
     * @memberof Game
     */
    links?: GamesLinks;
}

/**
 * Check if a given object implements the Game interface.
 */
export function instanceOfGame(value: object): value is Game {
    return true;
}

export function GameFromJSON(json: any): Game {
    return GameFromJSONTyped(json, false);
}

export function GameFromJSONTyped(json: any, ignoreDiscriminator: boolean): Game {
    if (json == null) {
        return json;
    }
    return {
        
        'links': json['links'] == null ? undefined : GamesLinksFromJSON(json['links']),
    };
}

export function GameToJSON(value?: Game | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'links': GamesLinksToJSON(value['links']),
    };
}

