/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GamesLinks } from './GamesLinks';
import {
    GamesLinksFromJSON,
    GamesLinksFromJSONTyped,
    GamesLinksToJSON,
} from './GamesLinks';

/**
 * May include a list of IDs of relevant items in the `data` field. To retrieve these listed items as well, add "games" to the "include" query parameter; results will be found in `.included`.
 * @export
 * @interface Games
 */
export interface Games {
    /**
     * 
     * @type {GamesLinks}
     * @memberof Games
     */
    links?: GamesLinks;
}

/**
 * Check if a given object implements the Games interface.
 */
export function instanceOfGames(value: object): value is Games {
    return true;
}

export function GamesFromJSON(json: any): Games {
    return GamesFromJSONTyped(json, false);
}

export function GamesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Games {
    if (json == null) {
        return json;
    }
    return {
        
        'links': json['links'] == null ? undefined : GamesLinksFromJSON(json['links']),
    };
}

export function GamesToJSON(value?: Games | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'links': GamesLinksToJSON(value['links']),
    };
}

