/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AchievementsIndex200ResponseJsonapi } from './AchievementsIndex200ResponseJsonapi';
import {
    AchievementsIndex200ResponseJsonapiFromJSON,
    AchievementsIndex200ResponseJsonapiFromJSONTyped,
    AchievementsIndex200ResponseJsonapiToJSON,
} from './AchievementsIndex200ResponseJsonapi';
import type { ResourcesGamesResourceFetch } from './ResourcesGamesResourceFetch';
import {
    ResourcesGamesResourceFetchFromJSON,
    ResourcesGamesResourceFetchFromJSONTyped,
    ResourcesGamesResourceFetchToJSON,
} from './ResourcesGamesResourceFetch';
import type { GamesIndex200ResponseIncludedInner } from './GamesIndex200ResponseIncludedInner';
import {
    GamesIndex200ResponseIncludedInnerFromJSON,
    GamesIndex200ResponseIncludedInnerFromJSONTyped,
    GamesIndex200ResponseIncludedInnerToJSON,
} from './GamesIndex200ResponseIncludedInner';

/**
 * 
 * @export
 * @interface GamesIndex200Response
 */
export interface GamesIndex200Response {
    /**
     * 
     * @type {AchievementsIndex200ResponseJsonapi}
     * @memberof GamesIndex200Response
     */
    jsonapi: AchievementsIndex200ResponseJsonapi;
    /**
     * 
     * @type {Array<ResourcesGamesResourceFetch>}
     * @memberof GamesIndex200Response
     */
    data: Array<ResourcesGamesResourceFetch>;
    /**
     * 
     * @type {Array<GamesIndex200ResponseIncludedInner>}
     * @memberof GamesIndex200Response
     */
    included?: Array<GamesIndex200ResponseIncludedInner>;
}

/**
 * Check if a given object implements the GamesIndex200Response interface.
 */
export function instanceOfGamesIndex200Response(value: object): value is GamesIndex200Response {
    if (!('jsonapi' in value) || value['jsonapi'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GamesIndex200ResponseFromJSON(json: any): GamesIndex200Response {
    return GamesIndex200ResponseFromJSONTyped(json, false);
}

export function GamesIndex200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GamesIndex200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonapi': AchievementsIndex200ResponseJsonapiFromJSON(json['jsonapi']),
        'data': ((json['data'] as Array<any>).map(ResourcesGamesResourceFetchFromJSON)),
        'included': json['included'] == null ? undefined : ((json['included'] as Array<any>).map(GamesIndex200ResponseIncludedInnerFromJSON)),
    };
}

export function GamesIndex200ResponseToJSON(value?: GamesIndex200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'jsonapi': AchievementsIndex200ResponseJsonapiToJSON(value['jsonapi']),
        'data': ((value['data'] as Array<any>).map(ResourcesGamesResourceFetchToJSON)),
        'included': value['included'] == null ? undefined : ((value['included'] as Array<any>).map(GamesIndex200ResponseIncludedInnerToJSON)),
    };
}

