/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AchievementsIndex200ResponseJsonapi } from './AchievementsIndex200ResponseJsonapi';
import {
    AchievementsIndex200ResponseJsonapiFromJSON,
    AchievementsIndex200ResponseJsonapiFromJSONTyped,
    AchievementsIndex200ResponseJsonapiToJSON,
} from './AchievementsIndex200ResponseJsonapi';
import type { ResourcesGamesRelationshipHashesFetch } from './ResourcesGamesRelationshipHashesFetch';
import {
    ResourcesGamesRelationshipHashesFetchFromJSON,
    ResourcesGamesRelationshipHashesFetchFromJSONTyped,
    ResourcesGamesRelationshipHashesFetchToJSON,
} from './ResourcesGamesRelationshipHashesFetch';

/**
 * 
 * @export
 * @interface GamesHashesShow200Response
 */
export interface GamesHashesShow200Response {
    /**
     * 
     * @type {AchievementsIndex200ResponseJsonapi}
     * @memberof GamesHashesShow200Response
     */
    jsonapi: AchievementsIndex200ResponseJsonapi;
    /**
     * 
     * @type {Array<ResourcesGamesRelationshipHashesFetch>}
     * @memberof GamesHashesShow200Response
     */
    data: Array<ResourcesGamesRelationshipHashesFetch>;
}

/**
 * Check if a given object implements the GamesHashesShow200Response interface.
 */
export function instanceOfGamesHashesShow200Response(value: object): value is GamesHashesShow200Response {
    if (!('jsonapi' in value) || value['jsonapi'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GamesHashesShow200ResponseFromJSON(json: any): GamesHashesShow200Response {
    return GamesHashesShow200ResponseFromJSONTyped(json, false);
}

export function GamesHashesShow200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GamesHashesShow200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonapi': AchievementsIndex200ResponseJsonapiFromJSON(json['jsonapi']),
        'data': ((json['data'] as Array<any>).map(ResourcesGamesRelationshipHashesFetchFromJSON)),
    };
}

export function GamesHashesShow200ResponseToJSON(value?: GamesHashesShow200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'jsonapi': AchievementsIndex200ResponseJsonapiToJSON(value['jsonapi']),
        'data': ((value['data'] as Array<any>).map(ResourcesGamesRelationshipHashesFetchToJSON)),
    };
}

