/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GamesLinks
 */
export interface GamesLinks {
    /**
     * 
     * @type {string}
     * @memberof GamesLinks
     */
    related?: string;
    /**
     * 
     * @type {string}
     * @memberof GamesLinks
     */
    self?: string;
}

/**
 * Check if a given object implements the GamesLinks interface.
 */
export function instanceOfGamesLinks(value: object): value is GamesLinks {
    return true;
}

export function GamesLinksFromJSON(json: any): GamesLinks {
    return GamesLinksFromJSONTyped(json, false);
}

export function GamesLinksFromJSONTyped(json: any, ignoreDiscriminator: boolean): GamesLinks {
    if (json == null) {
        return json;
    }
    return {
        
        'related': json['related'] == null ? undefined : json['related'],
        'self': json['self'] == null ? undefined : json['self'],
    };
}

export function GamesLinksToJSON(value?: GamesLinks | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'related': value['related'],
        'self': value['self'],
    };
}

