/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AchievementsIndex200ResponseJsonapi } from './AchievementsIndex200ResponseJsonapi';
import {
    AchievementsIndex200ResponseJsonapiFromJSON,
    AchievementsIndex200ResponseJsonapiFromJSONTyped,
    AchievementsIndex200ResponseJsonapiToJSON,
} from './AchievementsIndex200ResponseJsonapi';
import type { ResourcesGamesRelationshipCommentsFetch } from './ResourcesGamesRelationshipCommentsFetch';
import {
    ResourcesGamesRelationshipCommentsFetchFromJSON,
    ResourcesGamesRelationshipCommentsFetchFromJSONTyped,
    ResourcesGamesRelationshipCommentsFetchToJSON,
} from './ResourcesGamesRelationshipCommentsFetch';

/**
 * 
 * @export
 * @interface GamesCommentsShow200Response
 */
export interface GamesCommentsShow200Response {
    /**
     * 
     * @type {AchievementsIndex200ResponseJsonapi}
     * @memberof GamesCommentsShow200Response
     */
    jsonapi: AchievementsIndex200ResponseJsonapi;
    /**
     * 
     * @type {Array<ResourcesGamesRelationshipCommentsFetch>}
     * @memberof GamesCommentsShow200Response
     */
    data: Array<ResourcesGamesRelationshipCommentsFetch>;
}

/**
 * Check if a given object implements the GamesCommentsShow200Response interface.
 */
export function instanceOfGamesCommentsShow200Response(value: object): value is GamesCommentsShow200Response {
    if (!('jsonapi' in value) || value['jsonapi'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GamesCommentsShow200ResponseFromJSON(json: any): GamesCommentsShow200Response {
    return GamesCommentsShow200ResponseFromJSONTyped(json, false);
}

export function GamesCommentsShow200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GamesCommentsShow200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonapi': AchievementsIndex200ResponseJsonapiFromJSON(json['jsonapi']),
        'data': ((json['data'] as Array<any>).map(ResourcesGamesRelationshipCommentsFetchFromJSON)),
    };
}

export function GamesCommentsShow200ResponseToJSON(value?: GamesCommentsShow200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'jsonapi': AchievementsIndex200ResponseJsonapiToJSON(value['jsonapi']),
        'data': ((value['data'] as Array<any>).map(ResourcesGamesRelationshipCommentsFetchToJSON)),
    };
}

