/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AchievementsIndex200ResponseJsonapi } from './AchievementsIndex200ResponseJsonapi';
import {
    AchievementsIndex200ResponseJsonapiFromJSON,
    AchievementsIndex200ResponseJsonapiFromJSONTyped,
    AchievementsIndex200ResponseJsonapiToJSON,
} from './AchievementsIndex200ResponseJsonapi';
import type { ResourcesAchievementSetClaimsResourceFetch } from './ResourcesAchievementSetClaimsResourceFetch';
import {
    ResourcesAchievementSetClaimsResourceFetchFromJSON,
    ResourcesAchievementSetClaimsResourceFetchFromJSONTyped,
    ResourcesAchievementSetClaimsResourceFetchToJSON,
} from './ResourcesAchievementSetClaimsResourceFetch';

/**
 * 
 * @export
 * @interface GamesAchievementSetClaims200Response
 */
export interface GamesAchievementSetClaims200Response {
    /**
     * 
     * @type {AchievementsIndex200ResponseJsonapi}
     * @memberof GamesAchievementSetClaims200Response
     */
    jsonapi: AchievementsIndex200ResponseJsonapi;
    /**
     * 
     * @type {Array<ResourcesAchievementSetClaimsResourceFetch>}
     * @memberof GamesAchievementSetClaims200Response
     */
    data: Array<ResourcesAchievementSetClaimsResourceFetch>;
}

/**
 * Check if a given object implements the GamesAchievementSetClaims200Response interface.
 */
export function instanceOfGamesAchievementSetClaims200Response(value: object): value is GamesAchievementSetClaims200Response {
    if (!('jsonapi' in value) || value['jsonapi'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GamesAchievementSetClaims200ResponseFromJSON(json: any): GamesAchievementSetClaims200Response {
    return GamesAchievementSetClaims200ResponseFromJSONTyped(json, false);
}

export function GamesAchievementSetClaims200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GamesAchievementSetClaims200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonapi': AchievementsIndex200ResponseJsonapiFromJSON(json['jsonapi']),
        'data': ((json['data'] as Array<any>).map(ResourcesAchievementSetClaimsResourceFetchFromJSON)),
    };
}

export function GamesAchievementSetClaims200ResponseToJSON(value?: GamesAchievementSetClaims200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'jsonapi': AchievementsIndex200ResponseJsonapiToJSON(value['jsonapi']),
        'data': ((value['data'] as Array<any>).map(ResourcesAchievementSetClaimsResourceFetchToJSON)),
    };
}

