/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AchievementsIndex200ResponseJsonapi } from './AchievementsIndex200ResponseJsonapi';
import {
    AchievementsIndex200ResponseJsonapiFromJSON,
    AchievementsIndex200ResponseJsonapiFromJSONTyped,
    AchievementsIndex200ResponseJsonapiToJSON,
} from './AchievementsIndex200ResponseJsonapi';
import type { ResourcesGameHashesResourceFetch } from './ResourcesGameHashesResourceFetch';
import {
    ResourcesGameHashesResourceFetchFromJSON,
    ResourcesGameHashesResourceFetchFromJSONTyped,
    ResourcesGameHashesResourceFetchToJSON,
} from './ResourcesGameHashesResourceFetch';

/**
 * 
 * @export
 * @interface GamesHashes200Response
 */
export interface GamesHashes200Response {
    /**
     * 
     * @type {AchievementsIndex200ResponseJsonapi}
     * @memberof GamesHashes200Response
     */
    jsonapi: AchievementsIndex200ResponseJsonapi;
    /**
     * 
     * @type {Array<ResourcesGameHashesResourceFetch>}
     * @memberof GamesHashes200Response
     */
    data: Array<ResourcesGameHashesResourceFetch>;
}

/**
 * Check if a given object implements the GamesHashes200Response interface.
 */
export function instanceOfGamesHashes200Response(value: object): value is GamesHashes200Response {
    if (!('jsonapi' in value) || value['jsonapi'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GamesHashes200ResponseFromJSON(json: any): GamesHashes200Response {
    return GamesHashes200ResponseFromJSONTyped(json, false);
}

export function GamesHashes200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GamesHashes200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonapi': AchievementsIndex200ResponseJsonapiFromJSON(json['jsonapi']),
        'data': ((json['data'] as Array<any>).map(ResourcesGameHashesResourceFetchFromJSON)),
    };
}

export function GamesHashes200ResponseToJSON(value?: GamesHashes200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'jsonapi': AchievementsIndex200ResponseJsonapiToJSON(value['jsonapi']),
        'data': ((value['data'] as Array<any>).map(ResourcesGameHashesResourceFetchToJSON)),
    };
}

