/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HashesLinks
 */
export interface HashesLinks {
    /**
     * 
     * @type {string}
     * @memberof HashesLinks
     */
    related?: string;
    /**
     * 
     * @type {string}
     * @memberof HashesLinks
     */
    self?: string;
}

/**
 * Check if a given object implements the HashesLinks interface.
 */
export function instanceOfHashesLinks(value: object): value is HashesLinks {
    return true;
}

export function HashesLinksFromJSON(json: any): HashesLinks {
    return HashesLinksFromJSONTyped(json, false);
}

export function HashesLinksFromJSONTyped(json: any, ignoreDiscriminator: boolean): HashesLinks {
    if (json == null) {
        return json;
    }
    return {
        
        'related': json['related'] == null ? undefined : json['related'],
        'self': json['self'] == null ? undefined : json['self'],
    };
}

export function HashesLinksToJSON(value?: HashesLinks | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'related': value['related'],
        'self': value['self'],
    };
}

