/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HashesLinks } from './HashesLinks';
import {
    HashesLinksFromJSON,
    HashesLinksFromJSONTyped,
    HashesLinksToJSON,
} from './HashesLinks';

/**
 * May include a list of IDs of relevant items in the `data` field. To retrieve these listed items as well, add "hashes" to the "include" query parameter; results will be found in `.included`.
 * @export
 * @interface Hashes
 */
export interface Hashes {
    /**
     * 
     * @type {HashesLinks}
     * @memberof Hashes
     */
    links?: HashesLinks;
}

/**
 * Check if a given object implements the Hashes interface.
 */
export function instanceOfHashes(value: object): value is Hashes {
    return true;
}

export function HashesFromJSON(json: any): Hashes {
    return HashesFromJSONTyped(json, false);
}

export function HashesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Hashes {
    if (json == null) {
        return json;
    }
    return {
        
        'links': json['links'] == null ? undefined : HashesLinksFromJSON(json['links']),
    };
}

export function HashesToJSON(value?: Hashes | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'links': HashesLinksToJSON(value['links']),
    };
}

