/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AchievementsIndex200ResponseJsonapi } from './AchievementsIndex200ResponseJsonapi';
import {
    AchievementsIndex200ResponseJsonapiFromJSON,
    AchievementsIndex200ResponseJsonapiFromJSONTyped,
    AchievementsIndex200ResponseJsonapiToJSON,
} from './AchievementsIndex200ResponseJsonapi';
import type { ResourcesHubsResourceFetch } from './ResourcesHubsResourceFetch';
import {
    ResourcesHubsResourceFetchFromJSON,
    ResourcesHubsResourceFetchFromJSONTyped,
    ResourcesHubsResourceFetchToJSON,
} from './ResourcesHubsResourceFetch';
import type { HubsIndex200ResponseIncludedInner } from './HubsIndex200ResponseIncludedInner';
import {
    HubsIndex200ResponseIncludedInnerFromJSON,
    HubsIndex200ResponseIncludedInnerFromJSONTyped,
    HubsIndex200ResponseIncludedInnerToJSON,
} from './HubsIndex200ResponseIncludedInner';

/**
 * 
 * @export
 * @interface HubsShow200Response
 */
export interface HubsShow200Response {
    /**
     * 
     * @type {AchievementsIndex200ResponseJsonapi}
     * @memberof HubsShow200Response
     */
    jsonapi: AchievementsIndex200ResponseJsonapi;
    /**
     * 
     * @type {ResourcesHubsResourceFetch}
     * @memberof HubsShow200Response
     */
    data: ResourcesHubsResourceFetch;
    /**
     * 
     * @type {Array<HubsIndex200ResponseIncludedInner>}
     * @memberof HubsShow200Response
     */
    included?: Array<HubsIndex200ResponseIncludedInner>;
}

/**
 * Check if a given object implements the HubsShow200Response interface.
 */
export function instanceOfHubsShow200Response(value: object): value is HubsShow200Response {
    if (!('jsonapi' in value) || value['jsonapi'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function HubsShow200ResponseFromJSON(json: any): HubsShow200Response {
    return HubsShow200ResponseFromJSONTyped(json, false);
}

export function HubsShow200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HubsShow200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonapi': AchievementsIndex200ResponseJsonapiFromJSON(json['jsonapi']),
        'data': ResourcesHubsResourceFetchFromJSON(json['data']),
        'included': json['included'] == null ? undefined : ((json['included'] as Array<any>).map(HubsIndex200ResponseIncludedInnerFromJSON)),
    };
}

export function HubsShow200ResponseToJSON(value?: HubsShow200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'jsonapi': AchievementsIndex200ResponseJsonapiToJSON(value['jsonapi']),
        'data': ResourcesHubsResourceFetchToJSON(value['data']),
        'included': value['included'] == null ? undefined : ((value['included'] as Array<any>).map(HubsIndex200ResponseIncludedInnerToJSON)),
    };
}

