/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResourceGamesFetchRelationships } from './ResourceGamesFetchRelationships';
import {
    ResourceGamesFetchRelationshipsFromJSON,
    ResourceGamesFetchRelationshipsFromJSONTyped,
    ResourceGamesFetchRelationshipsToJSON,
} from './ResourceGamesFetchRelationships';
import type { ResourceGamesFetch } from './ResourceGamesFetch';
import {
    ResourceGamesFetchFromJSON,
    ResourceGamesFetchFromJSONTyped,
    ResourceGamesFetchToJSON,
} from './ResourceGamesFetch';
import type { ResourceGamesFetchAttributes } from './ResourceGamesFetchAttributes';
import {
    ResourceGamesFetchAttributesFromJSON,
    ResourceGamesFetchAttributesFromJSONTyped,
    ResourceGamesFetchAttributesToJSON,
} from './ResourceGamesFetchAttributes';

/**
 * 
 * @export
 * @interface HubsIndex200ResponseIncludedInner
 */
export interface HubsIndex200ResponseIncludedInner {
    /**
     * 
     * @type {string}
     * @memberof HubsIndex200ResponseIncludedInner
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof HubsIndex200ResponseIncludedInner
     */
    id: string;
    /**
     * 
     * @type {ResourceGamesFetchAttributes}
     * @memberof HubsIndex200ResponseIncludedInner
     */
    attributes: ResourceGamesFetchAttributes;
    /**
     * 
     * @type {ResourceGamesFetchRelationships}
     * @memberof HubsIndex200ResponseIncludedInner
     */
    relationships?: ResourceGamesFetchRelationships;
}

/**
 * Check if a given object implements the HubsIndex200ResponseIncludedInner interface.
 */
export function instanceOfHubsIndex200ResponseIncludedInner(value: object): value is HubsIndex200ResponseIncludedInner {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('attributes' in value) || value['attributes'] === undefined) return false;
    return true;
}

export function HubsIndex200ResponseIncludedInnerFromJSON(json: any): HubsIndex200ResponseIncludedInner {
    return HubsIndex200ResponseIncludedInnerFromJSONTyped(json, false);
}

export function HubsIndex200ResponseIncludedInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): HubsIndex200ResponseIncludedInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': ResourceGamesFetchAttributesFromJSON(json['attributes']),
        'relationships': json['relationships'] == null ? undefined : ResourceGamesFetchRelationshipsFromJSON(json['relationships']),
    };
}

export function HubsIndex200ResponseIncludedInnerToJSON(value?: HubsIndex200ResponseIncludedInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'id': value['id'],
        'attributes': ResourceGamesFetchAttributesToJSON(value['attributes']),
        'relationships': ResourceGamesFetchRelationshipsToJSON(value['relationships']),
    };
}

