/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Leaderboard1Links } from './Leaderboard1Links';
import {
    Leaderboard1LinksFromJSON,
    Leaderboard1LinksFromJSONTyped,
    Leaderboard1LinksToJSON,
} from './Leaderboard1Links';

/**
 * May include a list of IDs of relevant items in the `data` field. To retrieve these listed items as well, add "leaderboard" to the "include" query parameter; results will be found in `.included`.
 * @export
 * @interface Leaderboard1
 */
export interface Leaderboard1 {
    /**
     * 
     * @type {Leaderboard1Links}
     * @memberof Leaderboard1
     */
    links?: Leaderboard1Links;
}

/**
 * Check if a given object implements the Leaderboard1 interface.
 */
export function instanceOfLeaderboard1(value: object): value is Leaderboard1 {
    return true;
}

export function Leaderboard1FromJSON(json: any): Leaderboard1 {
    return Leaderboard1FromJSONTyped(json, false);
}

export function Leaderboard1FromJSONTyped(json: any, ignoreDiscriminator: boolean): Leaderboard1 {
    if (json == null) {
        return json;
    }
    return {
        
        'links': json['links'] == null ? undefined : Leaderboard1LinksFromJSON(json['links']),
    };
}

export function Leaderboard1ToJSON(value?: Leaderboard1 | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'links': Leaderboard1LinksToJSON(value['links']),
    };
}

