/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResourceGamesFetch } from './ResourceGamesFetch';
import {
    ResourceGamesFetchFromJSON,
    ResourceGamesFetchFromJSONTyped,
    ResourceGamesFetchToJSON,
} from './ResourceGamesFetch';
import type { ResourceDeveloperFetch } from './ResourceDeveloperFetch';
import {
    ResourceDeveloperFetchFromJSON,
    ResourceDeveloperFetchFromJSONTyped,
    ResourceDeveloperFetchToJSON,
} from './ResourceDeveloperFetch';
import type { ResourceEntriesFetchAttributes } from './ResourceEntriesFetchAttributes';
import {
    ResourceEntriesFetchAttributesFromJSON,
    ResourceEntriesFetchAttributesFromJSONTyped,
    ResourceEntriesFetchAttributesToJSON,
} from './ResourceEntriesFetchAttributes';
import type { ResourceEntriesFetchRelationships } from './ResourceEntriesFetchRelationships';
import {
    ResourceEntriesFetchRelationshipsFromJSON,
    ResourceEntriesFetchRelationshipsFromJSONTyped,
    ResourceEntriesFetchRelationshipsToJSON,
} from './ResourceEntriesFetchRelationships';
import type { ResourceEntriesFetch } from './ResourceEntriesFetch';
import {
    ResourceEntriesFetchFromJSON,
    ResourceEntriesFetchFromJSONTyped,
    ResourceEntriesFetchToJSON,
} from './ResourceEntriesFetch';

/**
 * 
 * @export
 * @interface LeaderboardsIndex200ResponseIncludedInner
 */
export interface LeaderboardsIndex200ResponseIncludedInner {
    /**
     * 
     * @type {string}
     * @memberof LeaderboardsIndex200ResponseIncludedInner
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof LeaderboardsIndex200ResponseIncludedInner
     */
    id: string;
    /**
     * 
     * @type {ResourceEntriesFetchAttributes}
     * @memberof LeaderboardsIndex200ResponseIncludedInner
     */
    attributes: ResourceEntriesFetchAttributes;
    /**
     * 
     * @type {ResourceEntriesFetchRelationships}
     * @memberof LeaderboardsIndex200ResponseIncludedInner
     */
    relationships?: ResourceEntriesFetchRelationships;
}

/**
 * Check if a given object implements the LeaderboardsIndex200ResponseIncludedInner interface.
 */
export function instanceOfLeaderboardsIndex200ResponseIncludedInner(value: object): value is LeaderboardsIndex200ResponseIncludedInner {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('attributes' in value) || value['attributes'] === undefined) return false;
    return true;
}

export function LeaderboardsIndex200ResponseIncludedInnerFromJSON(json: any): LeaderboardsIndex200ResponseIncludedInner {
    return LeaderboardsIndex200ResponseIncludedInnerFromJSONTyped(json, false);
}

export function LeaderboardsIndex200ResponseIncludedInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): LeaderboardsIndex200ResponseIncludedInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': ResourceEntriesFetchAttributesFromJSON(json['attributes']),
        'relationships': json['relationships'] == null ? undefined : ResourceEntriesFetchRelationshipsFromJSON(json['relationships']),
    };
}

export function LeaderboardsIndex200ResponseIncludedInnerToJSON(value?: LeaderboardsIndex200ResponseIncludedInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'id': value['id'],
        'attributes': ResourceEntriesFetchAttributesToJSON(value['attributes']),
        'relationships': ResourceEntriesFetchRelationshipsToJSON(value['relationships']),
    };
}

