/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LeaderboardsIndex200ResponseIncludedInner } from './LeaderboardsIndex200ResponseIncludedInner';
import {
    LeaderboardsIndex200ResponseIncludedInnerFromJSON,
    LeaderboardsIndex200ResponseIncludedInnerFromJSONTyped,
    LeaderboardsIndex200ResponseIncludedInnerToJSON,
} from './LeaderboardsIndex200ResponseIncludedInner';
import type { AchievementsIndex200ResponseJsonapi } from './AchievementsIndex200ResponseJsonapi';
import {
    AchievementsIndex200ResponseJsonapiFromJSON,
    AchievementsIndex200ResponseJsonapiFromJSONTyped,
    AchievementsIndex200ResponseJsonapiToJSON,
} from './AchievementsIndex200ResponseJsonapi';
import type { ResourcesLeaderboardsResourceFetch } from './ResourcesLeaderboardsResourceFetch';
import {
    ResourcesLeaderboardsResourceFetchFromJSON,
    ResourcesLeaderboardsResourceFetchFromJSONTyped,
    ResourcesLeaderboardsResourceFetchToJSON,
} from './ResourcesLeaderboardsResourceFetch';

/**
 * 
 * @export
 * @interface LeaderboardsIndex200Response
 */
export interface LeaderboardsIndex200Response {
    /**
     * 
     * @type {AchievementsIndex200ResponseJsonapi}
     * @memberof LeaderboardsIndex200Response
     */
    jsonapi: AchievementsIndex200ResponseJsonapi;
    /**
     * 
     * @type {Array<ResourcesLeaderboardsResourceFetch>}
     * @memberof LeaderboardsIndex200Response
     */
    data: Array<ResourcesLeaderboardsResourceFetch>;
    /**
     * 
     * @type {Array<LeaderboardsIndex200ResponseIncludedInner>}
     * @memberof LeaderboardsIndex200Response
     */
    included?: Array<LeaderboardsIndex200ResponseIncludedInner>;
}

/**
 * Check if a given object implements the LeaderboardsIndex200Response interface.
 */
export function instanceOfLeaderboardsIndex200Response(value: object): value is LeaderboardsIndex200Response {
    if (!('jsonapi' in value) || value['jsonapi'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function LeaderboardsIndex200ResponseFromJSON(json: any): LeaderboardsIndex200Response {
    return LeaderboardsIndex200ResponseFromJSONTyped(json, false);
}

export function LeaderboardsIndex200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LeaderboardsIndex200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonapi': AchievementsIndex200ResponseJsonapiFromJSON(json['jsonapi']),
        'data': ((json['data'] as Array<any>).map(ResourcesLeaderboardsResourceFetchFromJSON)),
        'included': json['included'] == null ? undefined : ((json['included'] as Array<any>).map(LeaderboardsIndex200ResponseIncludedInnerFromJSON)),
    };
}

export function LeaderboardsIndex200ResponseToJSON(value?: LeaderboardsIndex200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'jsonapi': AchievementsIndex200ResponseJsonapiToJSON(value['jsonapi']),
        'data': ((value['data'] as Array<any>).map(ResourcesLeaderboardsResourceFetchToJSON)),
        'included': value['included'] == null ? undefined : ((value['included'] as Array<any>).map(LeaderboardsIndex200ResponseIncludedInnerToJSON)),
    };
}

