/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrorSource } from './ErrorSource';
import {
    ErrorSourceFromJSON,
    ErrorSourceFromJSONTyped,
    ErrorSourceToJSON,
} from './ErrorSource';

/**
 * 
 * @export
 * @interface ModelError
 */
export interface ModelError {
    /**
     * 
     * @type {string}
     * @memberof ModelError
     */
    detail?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelError
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof ModelError
     */
    title: string;
    /**
     * 
     * @type {ErrorSource}
     * @memberof ModelError
     */
    source?: ErrorSource;
}

/**
 * Check if a given object implements the ModelError interface.
 */
export function instanceOfModelError(value: object): value is ModelError {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function ModelErrorFromJSON(json: any): ModelError {
    return ModelErrorFromJSONTyped(json, false);
}

export function ModelErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelError {
    if (json == null) {
        return json;
    }
    return {
        
        'detail': json['detail'] == null ? undefined : json['detail'],
        'status': json['status'],
        'title': json['title'],
        'source': json['source'] == null ? undefined : ErrorSourceFromJSON(json['source']),
    };
}

export function ModelErrorToJSON(value?: ModelError | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'detail': value['detail'],
        'status': value['status'],
        'title': value['title'],
        'source': ErrorSourceToJSON(value['source']),
    };
}

