/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlayerAchievementSetsLinks } from './PlayerAchievementSetsLinks';
import {
    PlayerAchievementSetsLinksFromJSON,
    PlayerAchievementSetsLinksFromJSONTyped,
    PlayerAchievementSetsLinksToJSON,
} from './PlayerAchievementSetsLinks';

/**
 * May include a list of IDs of relevant items in the `data` field. To retrieve these listed items as well, add "playerAchievementSets" to the "include" query parameter; results will be found in `.included`.
 * @export
 * @interface PlayerAchievementSets
 */
export interface PlayerAchievementSets {
    /**
     * 
     * @type {PlayerAchievementSetsLinks}
     * @memberof PlayerAchievementSets
     */
    links?: PlayerAchievementSetsLinks;
}

/**
 * Check if a given object implements the PlayerAchievementSets interface.
 */
export function instanceOfPlayerAchievementSets(value: object): value is PlayerAchievementSets {
    return true;
}

export function PlayerAchievementSetsFromJSON(json: any): PlayerAchievementSets {
    return PlayerAchievementSetsFromJSONTyped(json, false);
}

export function PlayerAchievementSetsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayerAchievementSets {
    if (json == null) {
        return json;
    }
    return {
        
        'links': json['links'] == null ? undefined : PlayerAchievementSetsLinksFromJSON(json['links']),
    };
}

export function PlayerAchievementSetsToJSON(value?: PlayerAchievementSets | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'links': PlayerAchievementSetsLinksToJSON(value['links']),
    };
}

