/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlayerAchievements1Links } from './PlayerAchievements1Links';
import {
    PlayerAchievements1LinksFromJSON,
    PlayerAchievements1LinksFromJSONTyped,
    PlayerAchievements1LinksToJSON,
} from './PlayerAchievements1Links';

/**
 * May include a list of IDs of relevant items in the `data` field. To retrieve these listed items as well, add "playerAchievements" to the "include" query parameter; results will be found in `.included`.
 * @export
 * @interface PlayerAchievements1
 */
export interface PlayerAchievements1 {
    /**
     * 
     * @type {PlayerAchievements1Links}
     * @memberof PlayerAchievements1
     */
    links?: PlayerAchievements1Links;
}

/**
 * Check if a given object implements the PlayerAchievements1 interface.
 */
export function instanceOfPlayerAchievements1(value: object): value is PlayerAchievements1 {
    return true;
}

export function PlayerAchievements1FromJSON(json: any): PlayerAchievements1 {
    return PlayerAchievements1FromJSONTyped(json, false);
}

export function PlayerAchievements1FromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayerAchievements1 {
    if (json == null) {
        return json;
    }
    return {
        
        'links': json['links'] == null ? undefined : PlayerAchievements1LinksFromJSON(json['links']),
    };
}

export function PlayerAchievements1ToJSON(value?: PlayerAchievements1 | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'links': PlayerAchievements1LinksToJSON(value['links']),
    };
}

