/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlayerGamesLinks
 */
export interface PlayerGamesLinks {
    /**
     * 
     * @type {string}
     * @memberof PlayerGamesLinks
     */
    related?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerGamesLinks
     */
    self?: string;
}

/**
 * Check if a given object implements the PlayerGamesLinks interface.
 */
export function instanceOfPlayerGamesLinks(value: object): value is PlayerGamesLinks {
    return true;
}

export function PlayerGamesLinksFromJSON(json: any): PlayerGamesLinks {
    return PlayerGamesLinksFromJSONTyped(json, false);
}

export function PlayerGamesLinksFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayerGamesLinks {
    if (json == null) {
        return json;
    }
    return {
        
        'related': json['related'] == null ? undefined : json['related'],
        'self': json['self'] == null ? undefined : json['self'],
    };
}

export function PlayerGamesLinksToJSON(value?: PlayerGamesLinks | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'related': value['related'],
        'self': value['self'],
    };
}

