/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlayerAchievementSets1Links } from './PlayerAchievementSets1Links';
import {
    PlayerAchievementSets1LinksFromJSON,
    PlayerAchievementSets1LinksFromJSONTyped,
    PlayerAchievementSets1LinksToJSON,
} from './PlayerAchievementSets1Links';

/**
 * May include a list of IDs of relevant items in the `data` field. To retrieve these listed items as well, add "playerAchievementSets" to the "include" query parameter; results will be found in `.included`.
 * @export
 * @interface PlayerAchievementSets1
 */
export interface PlayerAchievementSets1 {
    /**
     * 
     * @type {PlayerAchievementSets1Links}
     * @memberof PlayerAchievementSets1
     */
    links?: PlayerAchievementSets1Links;
}

/**
 * Check if a given object implements the PlayerAchievementSets1 interface.
 */
export function instanceOfPlayerAchievementSets1(value: object): value is PlayerAchievementSets1 {
    return true;
}

export function PlayerAchievementSets1FromJSON(json: any): PlayerAchievementSets1 {
    return PlayerAchievementSets1FromJSONTyped(json, false);
}

export function PlayerAchievementSets1FromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayerAchievementSets1 {
    if (json == null) {
        return json;
    }
    return {
        
        'links': json['links'] == null ? undefined : PlayerAchievementSets1LinksFromJSON(json['links']),
    };
}

export function PlayerAchievementSets1ToJSON(value?: PlayerAchievementSets1 | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'links': PlayerAchievementSets1LinksToJSON(value['links']),
    };
}

