/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReporterLinks } from './ReporterLinks';
import {
    ReporterLinksFromJSON,
    ReporterLinksFromJSONTyped,
    ReporterLinksToJSON,
} from './ReporterLinks';

/**
 * May include a list of IDs of relevant items in the `data` field. To retrieve these listed items as well, add "reporter" to the "include" query parameter; results will be found in `.included`.
 * @export
 * @interface Reporter
 */
export interface Reporter {
    /**
     * 
     * @type {ReporterLinks}
     * @memberof Reporter
     */
    links?: ReporterLinks;
}

/**
 * Check if a given object implements the Reporter interface.
 */
export function instanceOfReporter(value: object): value is Reporter {
    return true;
}

export function ReporterFromJSON(json: any): Reporter {
    return ReporterFromJSONTyped(json, false);
}

export function ReporterFromJSONTyped(json: any, ignoreDiscriminator: boolean): Reporter {
    if (json == null) {
        return json;
    }
    return {
        
        'links': json['links'] == null ? undefined : ReporterLinksFromJSON(json['links']),
    };
}

export function ReporterToJSON(value?: Reporter | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'links': ReporterLinksToJSON(value['links']),
    };
}

