/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';
import type { Leaderboard1 } from './Leaderboard1';
import {
    Leaderboard1FromJSON,
    Leaderboard1FromJSONTyped,
    Leaderboard1ToJSON,
} from './Leaderboard1';

/**
 * 
 * @export
 * @interface ResourceEntriesFetchRelationships
 */
export interface ResourceEntriesFetchRelationships {
    /**
     * 
     * @type {User}
     * @memberof ResourceEntriesFetchRelationships
     */
    user?: User;
    /**
     * 
     * @type {Leaderboard1}
     * @memberof ResourceEntriesFetchRelationships
     */
    leaderboard?: Leaderboard1;
}

/**
 * Check if a given object implements the ResourceEntriesFetchRelationships interface.
 */
export function instanceOfResourceEntriesFetchRelationships(value: object): value is ResourceEntriesFetchRelationships {
    return true;
}

export function ResourceEntriesFetchRelationshipsFromJSON(json: any): ResourceEntriesFetchRelationships {
    return ResourceEntriesFetchRelationshipsFromJSONTyped(json, false);
}

export function ResourceEntriesFetchRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceEntriesFetchRelationships {
    if (json == null) {
        return json;
    }
    return {
        
        'user': json['user'] == null ? undefined : UserFromJSON(json['user']),
        'leaderboard': json['leaderboard'] == null ? undefined : Leaderboard1FromJSON(json['leaderboard']),
    };
}

export function ResourceEntriesFetchRelationshipsToJSON(value?: ResourceEntriesFetchRelationships | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'user': UserToJSON(value['user']),
        'leaderboard': Leaderboard1ToJSON(value['leaderboard']),
    };
}

