/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResourceAchievementSetVersionsFetchAttributes } from './ResourceAchievementSetVersionsFetchAttributes';
import {
    ResourceAchievementSetVersionsFetchAttributesFromJSON,
    ResourceAchievementSetVersionsFetchAttributesFromJSONTyped,
    ResourceAchievementSetVersionsFetchAttributesToJSON,
} from './ResourceAchievementSetVersionsFetchAttributes';
import type { ResourceAchievementSetVersionsFetchRelationships } from './ResourceAchievementSetVersionsFetchRelationships';
import {
    ResourceAchievementSetVersionsFetchRelationshipsFromJSON,
    ResourceAchievementSetVersionsFetchRelationshipsFromJSONTyped,
    ResourceAchievementSetVersionsFetchRelationshipsToJSON,
} from './ResourceAchievementSetVersionsFetchRelationships';

/**
 * 
 * @export
 * @interface ResourcesAchievementSetVersionsResourceFetch
 */
export interface ResourcesAchievementSetVersionsResourceFetch {
    /**
     * 
     * @type {string}
     * @memberof ResourcesAchievementSetVersionsResourceFetch
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof ResourcesAchievementSetVersionsResourceFetch
     */
    id: string;
    /**
     * 
     * @type {ResourceAchievementSetVersionsFetchAttributes}
     * @memberof ResourcesAchievementSetVersionsResourceFetch
     */
    attributes: ResourceAchievementSetVersionsFetchAttributes;
    /**
     * 
     * @type {ResourceAchievementSetVersionsFetchRelationships}
     * @memberof ResourcesAchievementSetVersionsResourceFetch
     */
    relationships?: ResourceAchievementSetVersionsFetchRelationships;
}

/**
 * Check if a given object implements the ResourcesAchievementSetVersionsResourceFetch interface.
 */
export function instanceOfResourcesAchievementSetVersionsResourceFetch(value: object): value is ResourcesAchievementSetVersionsResourceFetch {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('attributes' in value) || value['attributes'] === undefined) return false;
    return true;
}

export function ResourcesAchievementSetVersionsResourceFetchFromJSON(json: any): ResourcesAchievementSetVersionsResourceFetch {
    return ResourcesAchievementSetVersionsResourceFetchFromJSONTyped(json, false);
}

export function ResourcesAchievementSetVersionsResourceFetchFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourcesAchievementSetVersionsResourceFetch {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': ResourceAchievementSetVersionsFetchAttributesFromJSON(json['attributes']),
        'relationships': json['relationships'] == null ? undefined : ResourceAchievementSetVersionsFetchRelationshipsFromJSON(json['relationships']),
    };
}

export function ResourcesAchievementSetVersionsResourceFetchToJSON(value?: ResourcesAchievementSetVersionsResourceFetch | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'id': value['id'],
        'attributes': ResourceAchievementSetVersionsFetchAttributesToJSON(value['attributes']),
        'relationships': ResourceAchievementSetVersionsFetchRelationshipsToJSON(value['relationships']),
    };
}

