/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResourceLeaderboardFetchAttributes } from './ResourceLeaderboardFetchAttributes';
import {
    ResourceLeaderboardFetchAttributesFromJSON,
    ResourceLeaderboardFetchAttributesFromJSONTyped,
    ResourceLeaderboardFetchAttributesToJSON,
} from './ResourceLeaderboardFetchAttributes';
import type { ResourceLeaderboardFetchRelationships } from './ResourceLeaderboardFetchRelationships';
import {
    ResourceLeaderboardFetchRelationshipsFromJSON,
    ResourceLeaderboardFetchRelationshipsFromJSONTyped,
    ResourceLeaderboardFetchRelationshipsToJSON,
} from './ResourceLeaderboardFetchRelationships';

/**
 * 
 * @export
 * @interface ResourcesLeaderboardsResourceFetch
 */
export interface ResourcesLeaderboardsResourceFetch {
    /**
     * 
     * @type {string}
     * @memberof ResourcesLeaderboardsResourceFetch
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof ResourcesLeaderboardsResourceFetch
     */
    id: string;
    /**
     * 
     * @type {ResourceLeaderboardFetchAttributes}
     * @memberof ResourcesLeaderboardsResourceFetch
     */
    attributes: ResourceLeaderboardFetchAttributes;
    /**
     * 
     * @type {ResourceLeaderboardFetchRelationships}
     * @memberof ResourcesLeaderboardsResourceFetch
     */
    relationships?: ResourceLeaderboardFetchRelationships;
}

/**
 * Check if a given object implements the ResourcesLeaderboardsResourceFetch interface.
 */
export function instanceOfResourcesLeaderboardsResourceFetch(value: object): value is ResourcesLeaderboardsResourceFetch {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('attributes' in value) || value['attributes'] === undefined) return false;
    return true;
}

export function ResourcesLeaderboardsResourceFetchFromJSON(json: any): ResourcesLeaderboardsResourceFetch {
    return ResourcesLeaderboardsResourceFetchFromJSONTyped(json, false);
}

export function ResourcesLeaderboardsResourceFetchFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourcesLeaderboardsResourceFetch {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': ResourceLeaderboardFetchAttributesFromJSON(json['attributes']),
        'relationships': json['relationships'] == null ? undefined : ResourceLeaderboardFetchRelationshipsFromJSON(json['relationships']),
    };
}

export function ResourcesLeaderboardsResourceFetchToJSON(value?: ResourcesLeaderboardsResourceFetch | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'id': value['id'],
        'attributes': ResourceLeaderboardFetchAttributesToJSON(value['attributes']),
        'relationships': ResourceLeaderboardFetchRelationshipsToJSON(value['relationships']),
    };
}

