/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Event } from './Event';
import {
    EventFromJSON,
    EventFromJSONTyped,
    EventToJSON,
} from './Event';

/**
 * 
 * @export
 * @interface ResourceAwardsFetchRelationships
 */
export interface ResourceAwardsFetchRelationships {
    /**
     * 
     * @type {Event}
     * @memberof ResourceAwardsFetchRelationships
     */
    event?: Event;
}

/**
 * Check if a given object implements the ResourceAwardsFetchRelationships interface.
 */
export function instanceOfResourceAwardsFetchRelationships(value: object): value is ResourceAwardsFetchRelationships {
    return true;
}

export function ResourceAwardsFetchRelationshipsFromJSON(json: any): ResourceAwardsFetchRelationships {
    return ResourceAwardsFetchRelationshipsFromJSONTyped(json, false);
}

export function ResourceAwardsFetchRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceAwardsFetchRelationships {
    if (json == null) {
        return json;
    }
    return {
        
        'event': json['event'] == null ? undefined : EventFromJSON(json['event']),
    };
}

export function ResourceAwardsFetchRelationshipsToJSON(value?: ResourceAwardsFetchRelationships | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'event': EventToJSON(value['event']),
    };
}

