/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResourcesEventsResourceFetchAttributes
 */
export interface ResourcesEventsResourceFetchAttributes {
    /**
     * 
     * @type {string}
     * @memberof ResourcesEventsResourceFetchAttributes
     */
    readonly title?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourcesEventsResourceFetchAttributes
     */
    readonly sortTitle?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourcesEventsResourceFetchAttributes
     */
    readonly badgeUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourcesEventsResourceFetchAttributes
     */
    readonly state?: string;
    /**
     * 
     * @type {number}
     * @memberof ResourcesEventsResourceFetchAttributes
     */
    readonly playersTotal?: number;
    /**
     * 
     * @type {number}
     * @memberof ResourcesEventsResourceFetchAttributes
     */
    readonly achievementsPublished?: number;
    /**
     * 
     * @type {string}
     * @memberof ResourcesEventsResourceFetchAttributes
     */
    readonly activeFrom?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourcesEventsResourceFetchAttributes
     */
    readonly activeThrough?: string;
}

/**
 * Check if a given object implements the ResourcesEventsResourceFetchAttributes interface.
 */
export function instanceOfResourcesEventsResourceFetchAttributes(value: object): value is ResourcesEventsResourceFetchAttributes {
    return true;
}

export function ResourcesEventsResourceFetchAttributesFromJSON(json: any): ResourcesEventsResourceFetchAttributes {
    return ResourcesEventsResourceFetchAttributesFromJSONTyped(json, false);
}

export function ResourcesEventsResourceFetchAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourcesEventsResourceFetchAttributes {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'sortTitle': json['sortTitle'] == null ? undefined : json['sortTitle'],
        'badgeUrl': json['badgeUrl'] == null ? undefined : json['badgeUrl'],
        'state': json['state'] == null ? undefined : json['state'],
        'playersTotal': json['playersTotal'] == null ? undefined : json['playersTotal'],
        'achievementsPublished': json['achievementsPublished'] == null ? undefined : json['achievementsPublished'],
        'activeFrom': json['activeFrom'] == null ? undefined : json['activeFrom'],
        'activeThrough': json['activeThrough'] == null ? undefined : json['activeThrough'],
    };
}

export function ResourcesEventsResourceFetchAttributesToJSON(value?: Omit<ResourcesEventsResourceFetchAttributes, 'title'|'sortTitle'|'badgeUrl'|'state'|'playersTotal'|'achievementsPublished'|'activeFrom'|'activeThrough'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
    };
}

