/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResourceHashesFetchAttributes
 */
export interface ResourceHashesFetchAttributes {
    /**
     * 
     * @type {string}
     * @memberof ResourceHashesFetchAttributes
     */
    readonly raMd5?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceHashesFetchAttributes
     */
    readonly name?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceHashesFetchAttributes
     */
    readonly compatibility?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceHashesFetchAttributes
     */
    readonly patchUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceHashesFetchAttributes
     */
    readonly createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceHashesFetchAttributes
     */
    readonly updatedAt?: string;
}

/**
 * Check if a given object implements the ResourceHashesFetchAttributes interface.
 */
export function instanceOfResourceHashesFetchAttributes(value: object): value is ResourceHashesFetchAttributes {
    return true;
}

export function ResourceHashesFetchAttributesFromJSON(json: any): ResourceHashesFetchAttributes {
    return ResourceHashesFetchAttributesFromJSONTyped(json, false);
}

export function ResourceHashesFetchAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceHashesFetchAttributes {
    if (json == null) {
        return json;
    }
    return {
        
        'raMd5': json['raMd5'] == null ? undefined : json['raMd5'],
        'name': json['name'] == null ? undefined : json['name'],
        'compatibility': json['compatibility'] == null ? undefined : json['compatibility'],
        'patchUrl': json['patchUrl'] == null ? undefined : json['patchUrl'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
    };
}

export function ResourceHashesFetchAttributesToJSON(value?: Omit<ResourceHashesFetchAttributes, 'raMd5'|'name'|'compatibility'|'patchUrl'|'createdAt'|'updatedAt'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
    };
}

