/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResourceAwardsFetchAttributes } from './ResourceAwardsFetchAttributes';
import {
    ResourceAwardsFetchAttributesFromJSON,
    ResourceAwardsFetchAttributesFromJSONTyped,
    ResourceAwardsFetchAttributesToJSON,
} from './ResourceAwardsFetchAttributes';
import type { ResourceAwardsFetchRelationships } from './ResourceAwardsFetchRelationships';
import {
    ResourceAwardsFetchRelationshipsFromJSON,
    ResourceAwardsFetchRelationshipsFromJSONTyped,
    ResourceAwardsFetchRelationshipsToJSON,
} from './ResourceAwardsFetchRelationships';

/**
 * May not be present unless "awards" is in the "include" header. See `.data[].relationships.awards.data` for the lists of IDs which have been included here.
 * @export
 * @interface ResourceAwardsFetch
 */
export interface ResourceAwardsFetch {
    /**
     * 
     * @type {string}
     * @memberof ResourceAwardsFetch
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceAwardsFetch
     */
    id: string;
    /**
     * 
     * @type {ResourceAwardsFetchAttributes}
     * @memberof ResourceAwardsFetch
     */
    attributes: ResourceAwardsFetchAttributes;
    /**
     * 
     * @type {ResourceAwardsFetchRelationships}
     * @memberof ResourceAwardsFetch
     */
    relationships?: ResourceAwardsFetchRelationships;
}

/**
 * Check if a given object implements the ResourceAwardsFetch interface.
 */
export function instanceOfResourceAwardsFetch(value: object): value is ResourceAwardsFetch {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('attributes' in value) || value['attributes'] === undefined) return false;
    return true;
}

export function ResourceAwardsFetchFromJSON(json: any): ResourceAwardsFetch {
    return ResourceAwardsFetchFromJSONTyped(json, false);
}

export function ResourceAwardsFetchFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceAwardsFetch {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': ResourceAwardsFetchAttributesFromJSON(json['attributes']),
        'relationships': json['relationships'] == null ? undefined : ResourceAwardsFetchRelationshipsFromJSON(json['relationships']),
    };
}

export function ResourceAwardsFetchToJSON(value?: ResourceAwardsFetch | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'id': value['id'],
        'attributes': ResourceAwardsFetchAttributesToJSON(value['attributes']),
        'relationships': ResourceAwardsFetchRelationshipsToJSON(value['relationships']),
    };
}

