/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResolverLinks
 */
export interface ResolverLinks {
    /**
     * 
     * @type {string}
     * @memberof ResolverLinks
     */
    related?: string;
    /**
     * 
     * @type {string}
     * @memberof ResolverLinks
     */
    self?: string;
}

/**
 * Check if a given object implements the ResolverLinks interface.
 */
export function instanceOfResolverLinks(value: object): value is ResolverLinks {
    return true;
}

export function ResolverLinksFromJSON(json: any): ResolverLinks {
    return ResolverLinksFromJSONTyped(json, false);
}

export function ResolverLinksFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResolverLinks {
    if (json == null) {
        return json;
    }
    return {
        
        'related': json['related'] == null ? undefined : json['related'],
        'self': json['self'] == null ? undefined : json['self'],
    };
}

export function ResolverLinksToJSON(value?: ResolverLinks | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'related': value['related'],
        'self': value['self'],
    };
}

