/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Games } from './Games';
import {
    GamesFromJSON,
    GamesFromJSONTyped,
    GamesToJSON,
} from './Games';
import type { AchievementSetVersions } from './AchievementSetVersions';
import {
    AchievementSetVersionsFromJSON,
    AchievementSetVersionsFromJSONTyped,
    AchievementSetVersionsToJSON,
} from './AchievementSetVersions';

/**
 * 
 * @export
 * @interface ResourceAchievementSetFetchRelationships
 */
export interface ResourceAchievementSetFetchRelationships {
    /**
     * 
     * @type {Games}
     * @memberof ResourceAchievementSetFetchRelationships
     */
    games?: Games;
    /**
     * 
     * @type {AchievementSetVersions}
     * @memberof ResourceAchievementSetFetchRelationships
     */
    achievementSetVersions?: AchievementSetVersions;
}

/**
 * Check if a given object implements the ResourceAchievementSetFetchRelationships interface.
 */
export function instanceOfResourceAchievementSetFetchRelationships(value: object): value is ResourceAchievementSetFetchRelationships {
    return true;
}

export function ResourceAchievementSetFetchRelationshipsFromJSON(json: any): ResourceAchievementSetFetchRelationships {
    return ResourceAchievementSetFetchRelationshipsFromJSONTyped(json, false);
}

export function ResourceAchievementSetFetchRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceAchievementSetFetchRelationships {
    if (json == null) {
        return json;
    }
    return {
        
        'games': json['games'] == null ? undefined : GamesFromJSON(json['games']),
        'achievementSetVersions': json['achievementSetVersions'] == null ? undefined : AchievementSetVersionsFromJSON(json['achievementSetVersions']),
    };
}

export function ResourceAchievementSetFetchRelationshipsToJSON(value?: ResourceAchievementSetFetchRelationships | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'games': GamesToJSON(value['games']),
        'achievementSetVersions': AchievementSetVersionsToJSON(value['achievementSetVersions']),
    };
}

