/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResourceAchievementSetFetchAttributes } from './ResourceAchievementSetFetchAttributes';
import {
    ResourceAchievementSetFetchAttributesFromJSON,
    ResourceAchievementSetFetchAttributesFromJSONTyped,
    ResourceAchievementSetFetchAttributesToJSON,
} from './ResourceAchievementSetFetchAttributes';
import type { ResourceAchievementSetFetchRelationships } from './ResourceAchievementSetFetchRelationships';
import {
    ResourceAchievementSetFetchRelationshipsFromJSON,
    ResourceAchievementSetFetchRelationshipsFromJSONTyped,
    ResourceAchievementSetFetchRelationshipsToJSON,
} from './ResourceAchievementSetFetchRelationships';

/**
 * May not be present unless "achievementSets" is in the "include" header. See `.data[].relationships.achievementSets.data` for the lists of IDs which have been included here.
 * @export
 * @interface ResourceAchievementSetsFetch
 */
export interface ResourceAchievementSetsFetch {
    /**
     * 
     * @type {string}
     * @memberof ResourceAchievementSetsFetch
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceAchievementSetsFetch
     */
    id: string;
    /**
     * 
     * @type {ResourceAchievementSetFetchAttributes}
     * @memberof ResourceAchievementSetsFetch
     */
    attributes: ResourceAchievementSetFetchAttributes;
    /**
     * 
     * @type {ResourceAchievementSetFetchRelationships}
     * @memberof ResourceAchievementSetsFetch
     */
    relationships?: ResourceAchievementSetFetchRelationships;
}

/**
 * Check if a given object implements the ResourceAchievementSetsFetch interface.
 */
export function instanceOfResourceAchievementSetsFetch(value: object): value is ResourceAchievementSetsFetch {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('attributes' in value) || value['attributes'] === undefined) return false;
    return true;
}

export function ResourceAchievementSetsFetchFromJSON(json: any): ResourceAchievementSetsFetch {
    return ResourceAchievementSetsFetchFromJSONTyped(json, false);
}

export function ResourceAchievementSetsFetchFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceAchievementSetsFetch {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': ResourceAchievementSetFetchAttributesFromJSON(json['attributes']),
        'relationships': json['relationships'] == null ? undefined : ResourceAchievementSetFetchRelationshipsFromJSON(json['relationships']),
    };
}

export function ResourceAchievementSetsFetchToJSON(value?: ResourceAchievementSetsFetch | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'id': value['id'],
        'attributes': ResourceAchievementSetFetchAttributesToJSON(value['attributes']),
        'relationships': ResourceAchievementSetFetchRelationshipsToJSON(value['relationships']),
    };
}

