/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResourceGamesFetchRelationships } from './ResourceGamesFetchRelationships';
import {
    ResourceGamesFetchRelationshipsFromJSON,
    ResourceGamesFetchRelationshipsFromJSONTyped,
    ResourceGamesFetchRelationshipsToJSON,
} from './ResourceGamesFetchRelationships';
import type { ResourceGamesFetchAttributes } from './ResourceGamesFetchAttributes';
import {
    ResourceGamesFetchAttributesFromJSON,
    ResourceGamesFetchAttributesFromJSONTyped,
    ResourceGamesFetchAttributesToJSON,
} from './ResourceGamesFetchAttributes';

/**
 * May not be present unless "games" is in the "include" header. See `.data[].relationships.games.data` for the lists of IDs which have been included here.
 * @export
 * @interface ResourceGamesFetch
 */
export interface ResourceGamesFetch {
    /**
     * 
     * @type {string}
     * @memberof ResourceGamesFetch
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceGamesFetch
     */
    id: string;
    /**
     * 
     * @type {ResourceGamesFetchAttributes}
     * @memberof ResourceGamesFetch
     */
    attributes: ResourceGamesFetchAttributes;
    /**
     * 
     * @type {ResourceGamesFetchRelationships}
     * @memberof ResourceGamesFetch
     */
    relationships?: ResourceGamesFetchRelationships;
}

/**
 * Check if a given object implements the ResourceGamesFetch interface.
 */
export function instanceOfResourceGamesFetch(value: object): value is ResourceGamesFetch {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('attributes' in value) || value['attributes'] === undefined) return false;
    return true;
}

export function ResourceGamesFetchFromJSON(json: any): ResourceGamesFetch {
    return ResourceGamesFetchFromJSONTyped(json, false);
}

export function ResourceGamesFetchFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceGamesFetch {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': ResourceGamesFetchAttributesFromJSON(json['attributes']),
        'relationships': json['relationships'] == null ? undefined : ResourceGamesFetchRelationshipsFromJSON(json['relationships']),
    };
}

export function ResourceGamesFetchToJSON(value?: ResourceGamesFetch | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'id': value['id'],
        'attributes': ResourceGamesFetchAttributesToJSON(value['attributes']),
        'relationships': ResourceGamesFetchRelationshipsToJSON(value['relationships']),
    };
}

