/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResourcesHubsResourceFetchAttributes
 */
export interface ResourcesHubsResourceFetchAttributes {
    /**
     * 
     * @type {string}
     * @memberof ResourcesHubsResourceFetchAttributes
     */
    readonly title?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourcesHubsResourceFetchAttributes
     */
    readonly sortTitle?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourcesHubsResourceFetchAttributes
     */
    readonly badgeUrl?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ResourcesHubsResourceFetchAttributes
     */
    readonly hasMatureContent?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ResourcesHubsResourceFetchAttributes
     */
    readonly gamesCount?: number;
    /**
     * 
     * @type {number}
     * @memberof ResourcesHubsResourceFetchAttributes
     */
    readonly linkedHubsCount?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ResourcesHubsResourceFetchAttributes
     */
    readonly isEventHub?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ResourcesHubsResourceFetchAttributes
     */
    readonly createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourcesHubsResourceFetchAttributes
     */
    readonly updatedAt?: string;
}

/**
 * Check if a given object implements the ResourcesHubsResourceFetchAttributes interface.
 */
export function instanceOfResourcesHubsResourceFetchAttributes(value: object): value is ResourcesHubsResourceFetchAttributes {
    return true;
}

export function ResourcesHubsResourceFetchAttributesFromJSON(json: any): ResourcesHubsResourceFetchAttributes {
    return ResourcesHubsResourceFetchAttributesFromJSONTyped(json, false);
}

export function ResourcesHubsResourceFetchAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourcesHubsResourceFetchAttributes {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'sortTitle': json['sortTitle'] == null ? undefined : json['sortTitle'],
        'badgeUrl': json['badgeUrl'] == null ? undefined : json['badgeUrl'],
        'hasMatureContent': json['hasMatureContent'] == null ? undefined : json['hasMatureContent'],
        'gamesCount': json['gamesCount'] == null ? undefined : json['gamesCount'],
        'linkedHubsCount': json['linkedHubsCount'] == null ? undefined : json['linkedHubsCount'],
        'isEventHub': json['isEventHub'] == null ? undefined : json['isEventHub'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
    };
}

export function ResourcesHubsResourceFetchAttributesToJSON(value?: Omit<ResourcesHubsResourceFetchAttributes, 'title'|'sortTitle'|'badgeUrl'|'hasMatureContent'|'gamesCount'|'linkedHubsCount'|'isEventHub'|'createdAt'|'updatedAt'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
    };
}

