/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResourceAchievementFetchAttributes
 */
export interface ResourceAchievementFetchAttributes {
    /**
     * 
     * @type {string}
     * @memberof ResourceAchievementFetchAttributes
     */
    readonly title?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceAchievementFetchAttributes
     */
    readonly description?: string;
    /**
     * 
     * @type {number}
     * @memberof ResourceAchievementFetchAttributes
     */
    readonly points?: number;
    /**
     * 
     * @type {number}
     * @memberof ResourceAchievementFetchAttributes
     */
    readonly pointsWeighted?: number;
    /**
     * 
     * @type {string}
     * @memberof ResourceAchievementFetchAttributes
     */
    readonly badgeUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceAchievementFetchAttributes
     */
    readonly badgeLockedUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceAchievementFetchAttributes
     */
    readonly type?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceAchievementFetchAttributes
     */
    readonly state?: string;
    /**
     * 
     * @type {number}
     * @memberof ResourceAchievementFetchAttributes
     */
    readonly orderColumn?: number;
    /**
     * 
     * @type {number}
     * @memberof ResourceAchievementFetchAttributes
     */
    readonly unlocksTotal?: number;
    /**
     * 
     * @type {number}
     * @memberof ResourceAchievementFetchAttributes
     */
    readonly unlocksHardcore?: number;
    /**
     * 
     * @type {number}
     * @memberof ResourceAchievementFetchAttributes
     */
    readonly unlockPercentage?: number;
    /**
     * 
     * @type {number}
     * @memberof ResourceAchievementFetchAttributes
     */
    readonly unlockHardcorePercentage?: number;
    /**
     * 
     * @type {string}
     * @memberof ResourceAchievementFetchAttributes
     */
    readonly createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceAchievementFetchAttributes
     */
    readonly modifiedAt?: string;
}

/**
 * Check if a given object implements the ResourceAchievementFetchAttributes interface.
 */
export function instanceOfResourceAchievementFetchAttributes(value: object): value is ResourceAchievementFetchAttributes {
    return true;
}

export function ResourceAchievementFetchAttributesFromJSON(json: any): ResourceAchievementFetchAttributes {
    return ResourceAchievementFetchAttributesFromJSONTyped(json, false);
}

export function ResourceAchievementFetchAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceAchievementFetchAttributes {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'points': json['points'] == null ? undefined : json['points'],
        'pointsWeighted': json['pointsWeighted'] == null ? undefined : json['pointsWeighted'],
        'badgeUrl': json['badgeUrl'] == null ? undefined : json['badgeUrl'],
        'badgeLockedUrl': json['badgeLockedUrl'] == null ? undefined : json['badgeLockedUrl'],
        'type': json['type'] == null ? undefined : json['type'],
        'state': json['state'] == null ? undefined : json['state'],
        'orderColumn': json['orderColumn'] == null ? undefined : json['orderColumn'],
        'unlocksTotal': json['unlocksTotal'] == null ? undefined : json['unlocksTotal'],
        'unlocksHardcore': json['unlocksHardcore'] == null ? undefined : json['unlocksHardcore'],
        'unlockPercentage': json['unlockPercentage'] == null ? undefined : json['unlockPercentage'],
        'unlockHardcorePercentage': json['unlockHardcorePercentage'] == null ? undefined : json['unlockHardcorePercentage'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'modifiedAt': json['modifiedAt'] == null ? undefined : json['modifiedAt'],
    };
}

export function ResourceAchievementFetchAttributesToJSON(value?: Omit<ResourceAchievementFetchAttributes, 'title'|'description'|'points'|'pointsWeighted'|'badgeUrl'|'badgeLockedUrl'|'type'|'state'|'orderColumn'|'unlocksTotal'|'unlocksHardcore'|'unlockPercentage'|'unlockHardcorePercentage'|'createdAt'|'modifiedAt'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
    };
}

