/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResourceFollowersFetchRelationships } from './ResourceFollowersFetchRelationships';
import {
    ResourceFollowersFetchRelationshipsFromJSON,
    ResourceFollowersFetchRelationshipsFromJSONTyped,
    ResourceFollowersFetchRelationshipsToJSON,
} from './ResourceFollowersFetchRelationships';
import type { ResourceFollowersFetchAttributes } from './ResourceFollowersFetchAttributes';
import {
    ResourceFollowersFetchAttributesFromJSON,
    ResourceFollowersFetchAttributesFromJSONTyped,
    ResourceFollowersFetchAttributesToJSON,
} from './ResourceFollowersFetchAttributes';

/**
 * 
 * @export
 * @interface ResourcesUserFollowsResourceFetch
 */
export interface ResourcesUserFollowsResourceFetch {
    /**
     * 
     * @type {string}
     * @memberof ResourcesUserFollowsResourceFetch
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof ResourcesUserFollowsResourceFetch
     */
    id: string;
    /**
     * 
     * @type {ResourceFollowersFetchAttributes}
     * @memberof ResourcesUserFollowsResourceFetch
     */
    attributes: ResourceFollowersFetchAttributes;
    /**
     * 
     * @type {ResourceFollowersFetchRelationships}
     * @memberof ResourcesUserFollowsResourceFetch
     */
    relationships?: ResourceFollowersFetchRelationships;
}

/**
 * Check if a given object implements the ResourcesUserFollowsResourceFetch interface.
 */
export function instanceOfResourcesUserFollowsResourceFetch(value: object): value is ResourcesUserFollowsResourceFetch {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('attributes' in value) || value['attributes'] === undefined) return false;
    return true;
}

export function ResourcesUserFollowsResourceFetchFromJSON(json: any): ResourcesUserFollowsResourceFetch {
    return ResourcesUserFollowsResourceFetchFromJSONTyped(json, false);
}

export function ResourcesUserFollowsResourceFetchFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourcesUserFollowsResourceFetch {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': ResourceFollowersFetchAttributesFromJSON(json['attributes']),
        'relationships': json['relationships'] == null ? undefined : ResourceFollowersFetchRelationshipsFromJSON(json['relationships']),
    };
}

export function ResourcesUserFollowsResourceFetchToJSON(value?: ResourcesUserFollowsResourceFetch | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'id': value['id'],
        'attributes': ResourceFollowersFetchAttributesToJSON(value['attributes']),
        'relationships': ResourceFollowersFetchRelationshipsToJSON(value['relationships']),
    };
}

