/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResourcesUsersRelationshipTicketsFetch
 */
export interface ResourcesUsersRelationshipTicketsFetch {
    /**
     * 
     * @type {string}
     * @memberof ResourcesUsersRelationshipTicketsFetch
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof ResourcesUsersRelationshipTicketsFetch
     */
    id: string;
}

/**
 * Check if a given object implements the ResourcesUsersRelationshipTicketsFetch interface.
 */
export function instanceOfResourcesUsersRelationshipTicketsFetch(value: object): value is ResourcesUsersRelationshipTicketsFetch {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ResourcesUsersRelationshipTicketsFetchFromJSON(json: any): ResourcesUsersRelationshipTicketsFetch {
    return ResourcesUsersRelationshipTicketsFetchFromJSONTyped(json, false);
}

export function ResourcesUsersRelationshipTicketsFetchFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourcesUsersRelationshipTicketsFetch {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
    };
}

export function ResourcesUsersRelationshipTicketsFetchToJSON(value?: ResourcesUsersRelationshipTicketsFetch | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'id': value['id'],
    };
}

