/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResourceEntriesFetchAttributes } from './ResourceEntriesFetchAttributes';
import {
    ResourceEntriesFetchAttributesFromJSON,
    ResourceEntriesFetchAttributesFromJSONTyped,
    ResourceEntriesFetchAttributesToJSON,
} from './ResourceEntriesFetchAttributes';
import type { ResourceEntriesFetchRelationships } from './ResourceEntriesFetchRelationships';
import {
    ResourceEntriesFetchRelationshipsFromJSON,
    ResourceEntriesFetchRelationshipsFromJSONTyped,
    ResourceEntriesFetchRelationshipsToJSON,
} from './ResourceEntriesFetchRelationships';

/**
 * May not be present unless "entries" is in the "include" header. See `.data[].relationships.entries.data` for the lists of IDs which have been included here.
 * @export
 * @interface ResourceEntriesFetch
 */
export interface ResourceEntriesFetch {
    /**
     * 
     * @type {string}
     * @memberof ResourceEntriesFetch
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceEntriesFetch
     */
    id: string;
    /**
     * 
     * @type {ResourceEntriesFetchAttributes}
     * @memberof ResourceEntriesFetch
     */
    attributes: ResourceEntriesFetchAttributes;
    /**
     * 
     * @type {ResourceEntriesFetchRelationships}
     * @memberof ResourceEntriesFetch
     */
    relationships?: ResourceEntriesFetchRelationships;
}

/**
 * Check if a given object implements the ResourceEntriesFetch interface.
 */
export function instanceOfResourceEntriesFetch(value: object): value is ResourceEntriesFetch {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('attributes' in value) || value['attributes'] === undefined) return false;
    return true;
}

export function ResourceEntriesFetchFromJSON(json: any): ResourceEntriesFetch {
    return ResourceEntriesFetchFromJSONTyped(json, false);
}

export function ResourceEntriesFetchFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceEntriesFetch {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': ResourceEntriesFetchAttributesFromJSON(json['attributes']),
        'relationships': json['relationships'] == null ? undefined : ResourceEntriesFetchRelationshipsFromJSON(json['relationships']),
    };
}

export function ResourceEntriesFetchToJSON(value?: ResourceEntriesFetch | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'id': value['id'],
        'attributes': ResourceEntriesFetchAttributesToJSON(value['attributes']),
        'relationships': ResourceEntriesFetchRelationshipsToJSON(value['relationships']),
    };
}

