/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AchievementSet } from './AchievementSet';
import {
    AchievementSetFromJSON,
    AchievementSetFromJSONTyped,
    AchievementSetToJSON,
} from './AchievementSet';

/**
 * 
 * @export
 * @interface ResourceAchievementSetVersionsFetchRelationships
 */
export interface ResourceAchievementSetVersionsFetchRelationships {
    /**
     * 
     * @type {AchievementSet}
     * @memberof ResourceAchievementSetVersionsFetchRelationships
     */
    achievementSet?: AchievementSet;
}

/**
 * Check if a given object implements the ResourceAchievementSetVersionsFetchRelationships interface.
 */
export function instanceOfResourceAchievementSetVersionsFetchRelationships(value: object): value is ResourceAchievementSetVersionsFetchRelationships {
    return true;
}

export function ResourceAchievementSetVersionsFetchRelationshipsFromJSON(json: any): ResourceAchievementSetVersionsFetchRelationships {
    return ResourceAchievementSetVersionsFetchRelationshipsFromJSONTyped(json, false);
}

export function ResourceAchievementSetVersionsFetchRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceAchievementSetVersionsFetchRelationships {
    if (json == null) {
        return json;
    }
    return {
        
        'achievementSet': json['achievementSet'] == null ? undefined : AchievementSetFromJSON(json['achievementSet']),
    };
}

export function ResourceAchievementSetVersionsFetchRelationshipsToJSON(value?: ResourceAchievementSetVersionsFetchRelationships | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'achievementSet': AchievementSetToJSON(value['achievementSet']),
    };
}

