/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User1 } from './User1';
import {
    User1FromJSON,
    User1FromJSONTyped,
    User1ToJSON,
} from './User1';

/**
 * 
 * @export
 * @interface ResourceFollowersFetchRelationships
 */
export interface ResourceFollowersFetchRelationships {
    /**
     * 
     * @type {User1}
     * @memberof ResourceFollowersFetchRelationships
     */
    user?: User1;
}

/**
 * Check if a given object implements the ResourceFollowersFetchRelationships interface.
 */
export function instanceOfResourceFollowersFetchRelationships(value: object): value is ResourceFollowersFetchRelationships {
    return true;
}

export function ResourceFollowersFetchRelationshipsFromJSON(json: any): ResourceFollowersFetchRelationships {
    return ResourceFollowersFetchRelationshipsFromJSONTyped(json, false);
}

export function ResourceFollowersFetchRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceFollowersFetchRelationships {
    if (json == null) {
        return json;
    }
    return {
        
        'user': json['user'] == null ? undefined : User1FromJSON(json['user']),
    };
}

export function ResourceFollowersFetchRelationshipsToJSON(value?: ResourceFollowersFetchRelationships | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'user': User1ToJSON(value['user']),
    };
}

