/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResourcesUsersRelationshipPlayerGamesFetch
 */
export interface ResourcesUsersRelationshipPlayerGamesFetch {
    /**
     * 
     * @type {string}
     * @memberof ResourcesUsersRelationshipPlayerGamesFetch
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof ResourcesUsersRelationshipPlayerGamesFetch
     */
    id: string;
}

/**
 * Check if a given object implements the ResourcesUsersRelationshipPlayerGamesFetch interface.
 */
export function instanceOfResourcesUsersRelationshipPlayerGamesFetch(value: object): value is ResourcesUsersRelationshipPlayerGamesFetch {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ResourcesUsersRelationshipPlayerGamesFetchFromJSON(json: any): ResourcesUsersRelationshipPlayerGamesFetch {
    return ResourcesUsersRelationshipPlayerGamesFetchFromJSONTyped(json, false);
}

export function ResourcesUsersRelationshipPlayerGamesFetchFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourcesUsersRelationshipPlayerGamesFetch {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
    };
}

export function ResourcesUsersRelationshipPlayerGamesFetchToJSON(value?: ResourcesUsersRelationshipPlayerGamesFetch | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'id': value['id'],
    };
}

