/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResourcesAchievementsRelationshipPlayerAchievementsFetch
 */
export interface ResourcesAchievementsRelationshipPlayerAchievementsFetch {
    /**
     * 
     * @type {string}
     * @memberof ResourcesAchievementsRelationshipPlayerAchievementsFetch
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof ResourcesAchievementsRelationshipPlayerAchievementsFetch
     */
    id: string;
}

/**
 * Check if a given object implements the ResourcesAchievementsRelationshipPlayerAchievementsFetch interface.
 */
export function instanceOfResourcesAchievementsRelationshipPlayerAchievementsFetch(value: object): value is ResourcesAchievementsRelationshipPlayerAchievementsFetch {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ResourcesAchievementsRelationshipPlayerAchievementsFetchFromJSON(json: any): ResourcesAchievementsRelationshipPlayerAchievementsFetch {
    return ResourcesAchievementsRelationshipPlayerAchievementsFetchFromJSONTyped(json, false);
}

export function ResourcesAchievementsRelationshipPlayerAchievementsFetchFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourcesAchievementsRelationshipPlayerAchievementsFetch {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
    };
}

export function ResourcesAchievementsRelationshipPlayerAchievementsFetchToJSON(value?: ResourcesAchievementsRelationshipPlayerAchievementsFetch | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'id': value['id'],
    };
}

