/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResourceCommentsFetchRelationships } from './ResourceCommentsFetchRelationships';
import {
    ResourceCommentsFetchRelationshipsFromJSON,
    ResourceCommentsFetchRelationshipsFromJSONTyped,
    ResourceCommentsFetchRelationshipsToJSON,
} from './ResourceCommentsFetchRelationships';
import type { ResourceCommentsFetchAttributes } from './ResourceCommentsFetchAttributes';
import {
    ResourceCommentsFetchAttributesFromJSON,
    ResourceCommentsFetchAttributesFromJSONTyped,
    ResourceCommentsFetchAttributesToJSON,
} from './ResourceCommentsFetchAttributes';

/**
 * 
 * @export
 * @interface ResourcesCommentsResourceFetch
 */
export interface ResourcesCommentsResourceFetch {
    /**
     * 
     * @type {string}
     * @memberof ResourcesCommentsResourceFetch
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof ResourcesCommentsResourceFetch
     */
    id: string;
    /**
     * 
     * @type {ResourceCommentsFetchAttributes}
     * @memberof ResourcesCommentsResourceFetch
     */
    attributes: ResourceCommentsFetchAttributes;
    /**
     * 
     * @type {ResourceCommentsFetchRelationships}
     * @memberof ResourcesCommentsResourceFetch
     */
    relationships?: ResourceCommentsFetchRelationships;
}

/**
 * Check if a given object implements the ResourcesCommentsResourceFetch interface.
 */
export function instanceOfResourcesCommentsResourceFetch(value: object): value is ResourcesCommentsResourceFetch {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('attributes' in value) || value['attributes'] === undefined) return false;
    return true;
}

export function ResourcesCommentsResourceFetchFromJSON(json: any): ResourcesCommentsResourceFetch {
    return ResourcesCommentsResourceFetchFromJSONTyped(json, false);
}

export function ResourcesCommentsResourceFetchFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourcesCommentsResourceFetch {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': ResourceCommentsFetchAttributesFromJSON(json['attributes']),
        'relationships': json['relationships'] == null ? undefined : ResourceCommentsFetchRelationshipsFromJSON(json['relationships']),
    };
}

export function ResourcesCommentsResourceFetchToJSON(value?: ResourcesCommentsResourceFetch | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'id': value['id'],
        'attributes': ResourceCommentsFetchAttributesToJSON(value['attributes']),
        'relationships': ResourceCommentsFetchRelationshipsToJSON(value['relationships']),
    };
}

