/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResourceAwardsFetch1Attributes
 */
export interface ResourceAwardsFetch1Attributes {
    /**
     * 
     * @type {string}
     * @memberof ResourceAwardsFetch1Attributes
     */
    readonly awardedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceAwardsFetch1Attributes
     */
    readonly kind?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceAwardsFetch1Attributes
     */
    readonly title?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceAwardsFetch1Attributes
     */
    readonly badgeUrl?: string;
    /**
     * 
     * @type {number}
     * @memberof ResourceAwardsFetch1Attributes
     */
    readonly displayOrder?: number;
    /**
     * 
     * @type {object}
     * @memberof ResourceAwardsFetch1Attributes
     */
    readonly context?: object;
}

/**
 * Check if a given object implements the ResourceAwardsFetch1Attributes interface.
 */
export function instanceOfResourceAwardsFetch1Attributes(value: object): value is ResourceAwardsFetch1Attributes {
    return true;
}

export function ResourceAwardsFetch1AttributesFromJSON(json: any): ResourceAwardsFetch1Attributes {
    return ResourceAwardsFetch1AttributesFromJSONTyped(json, false);
}

export function ResourceAwardsFetch1AttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceAwardsFetch1Attributes {
    if (json == null) {
        return json;
    }
    return {
        
        'awardedAt': json['awardedAt'] == null ? undefined : json['awardedAt'],
        'kind': json['kind'] == null ? undefined : json['kind'],
        'title': json['title'] == null ? undefined : json['title'],
        'badgeUrl': json['badgeUrl'] == null ? undefined : json['badgeUrl'],
        'displayOrder': json['displayOrder'] == null ? undefined : json['displayOrder'],
        'context': json['context'] == null ? undefined : json['context'],
    };
}

export function ResourceAwardsFetch1AttributesToJSON(value?: Omit<ResourceAwardsFetch1Attributes, 'awardedAt'|'kind'|'title'|'badgeUrl'|'displayOrder'|'context'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
    };
}

