/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResourcesGamesRelationshipTicketsFetch
 */
export interface ResourcesGamesRelationshipTicketsFetch {
    /**
     * 
     * @type {string}
     * @memberof ResourcesGamesRelationshipTicketsFetch
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof ResourcesGamesRelationshipTicketsFetch
     */
    id: string;
}

/**
 * Check if a given object implements the ResourcesGamesRelationshipTicketsFetch interface.
 */
export function instanceOfResourcesGamesRelationshipTicketsFetch(value: object): value is ResourcesGamesRelationshipTicketsFetch {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ResourcesGamesRelationshipTicketsFetchFromJSON(json: any): ResourcesGamesRelationshipTicketsFetch {
    return ResourcesGamesRelationshipTicketsFetchFromJSONTyped(json, false);
}

export function ResourcesGamesRelationshipTicketsFetchFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourcesGamesRelationshipTicketsFetch {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
    };
}

export function ResourcesGamesRelationshipTicketsFetchToJSON(value?: ResourcesGamesRelationshipTicketsFetch | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'id': value['id'],
    };
}

