/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResourcesAchievementsRelationshipCommentsFetch
 */
export interface ResourcesAchievementsRelationshipCommentsFetch {
    /**
     * 
     * @type {string}
     * @memberof ResourcesAchievementsRelationshipCommentsFetch
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof ResourcesAchievementsRelationshipCommentsFetch
     */
    id: string;
}

/**
 * Check if a given object implements the ResourcesAchievementsRelationshipCommentsFetch interface.
 */
export function instanceOfResourcesAchievementsRelationshipCommentsFetch(value: object): value is ResourcesAchievementsRelationshipCommentsFetch {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ResourcesAchievementsRelationshipCommentsFetchFromJSON(json: any): ResourcesAchievementsRelationshipCommentsFetch {
    return ResourcesAchievementsRelationshipCommentsFetchFromJSONTyped(json, false);
}

export function ResourcesAchievementsRelationshipCommentsFetchFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourcesAchievementsRelationshipCommentsFetch {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
    };
}

export function ResourcesAchievementsRelationshipCommentsFetchToJSON(value?: ResourcesAchievementsRelationshipCommentsFetch | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'id': value['id'],
    };
}

