/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResourceDeveloperFetchAttributes } from './ResourceDeveloperFetchAttributes';
import {
    ResourceDeveloperFetchAttributesFromJSON,
    ResourceDeveloperFetchAttributesFromJSONTyped,
    ResourceDeveloperFetchAttributesToJSON,
} from './ResourceDeveloperFetchAttributes';
import type { ResourceDeveloperFetchRelationships } from './ResourceDeveloperFetchRelationships';
import {
    ResourceDeveloperFetchRelationshipsFromJSON,
    ResourceDeveloperFetchRelationshipsFromJSONTyped,
    ResourceDeveloperFetchRelationshipsToJSON,
} from './ResourceDeveloperFetchRelationships';

/**
 * May not be present unless "reporter" is in the "include" header. See `.data[].relationships.reporter.data` for the lists of IDs which have been included here.
 * @export
 * @interface ResourceReporterFetch
 */
export interface ResourceReporterFetch {
    /**
     * 
     * @type {string}
     * @memberof ResourceReporterFetch
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceReporterFetch
     */
    id: string;
    /**
     * 
     * @type {ResourceDeveloperFetchAttributes}
     * @memberof ResourceReporterFetch
     */
    attributes: ResourceDeveloperFetchAttributes;
    /**
     * 
     * @type {ResourceDeveloperFetchRelationships}
     * @memberof ResourceReporterFetch
     */
    relationships?: ResourceDeveloperFetchRelationships;
}

/**
 * Check if a given object implements the ResourceReporterFetch interface.
 */
export function instanceOfResourceReporterFetch(value: object): value is ResourceReporterFetch {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('attributes' in value) || value['attributes'] === undefined) return false;
    return true;
}

export function ResourceReporterFetchFromJSON(json: any): ResourceReporterFetch {
    return ResourceReporterFetchFromJSONTyped(json, false);
}

export function ResourceReporterFetchFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceReporterFetch {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': ResourceDeveloperFetchAttributesFromJSON(json['attributes']),
        'relationships': json['relationships'] == null ? undefined : ResourceDeveloperFetchRelationshipsFromJSON(json['relationships']),
    };
}

export function ResourceReporterFetchToJSON(value?: ResourceReporterFetch | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'id': value['id'],
        'attributes': ResourceDeveloperFetchAttributesToJSON(value['attributes']),
        'relationships': ResourceDeveloperFetchRelationshipsToJSON(value['relationships']),
    };
}

