/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResourcePlayerAchievementsFetchAttributes } from './ResourcePlayerAchievementsFetchAttributes';
import {
    ResourcePlayerAchievementsFetchAttributesFromJSON,
    ResourcePlayerAchievementsFetchAttributesFromJSONTyped,
    ResourcePlayerAchievementsFetchAttributesToJSON,
} from './ResourcePlayerAchievementsFetchAttributes';
import type { ResourcePlayerAchievementsFetchRelationships } from './ResourcePlayerAchievementsFetchRelationships';
import {
    ResourcePlayerAchievementsFetchRelationshipsFromJSON,
    ResourcePlayerAchievementsFetchRelationshipsFromJSONTyped,
    ResourcePlayerAchievementsFetchRelationshipsToJSON,
} from './ResourcePlayerAchievementsFetchRelationships';

/**
 * May not be present unless "playerAchievements" is in the "include" header. See `.data[].relationships.playerAchievements.data` for the lists of IDs which have been included here.
 * @export
 * @interface ResourcePlayerAchievementsFetch
 */
export interface ResourcePlayerAchievementsFetch {
    /**
     * 
     * @type {string}
     * @memberof ResourcePlayerAchievementsFetch
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof ResourcePlayerAchievementsFetch
     */
    id: string;
    /**
     * 
     * @type {ResourcePlayerAchievementsFetchAttributes}
     * @memberof ResourcePlayerAchievementsFetch
     */
    attributes: ResourcePlayerAchievementsFetchAttributes;
    /**
     * 
     * @type {ResourcePlayerAchievementsFetchRelationships}
     * @memberof ResourcePlayerAchievementsFetch
     */
    relationships?: ResourcePlayerAchievementsFetchRelationships;
}

/**
 * Check if a given object implements the ResourcePlayerAchievementsFetch interface.
 */
export function instanceOfResourcePlayerAchievementsFetch(value: object): value is ResourcePlayerAchievementsFetch {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('attributes' in value) || value['attributes'] === undefined) return false;
    return true;
}

export function ResourcePlayerAchievementsFetchFromJSON(json: any): ResourcePlayerAchievementsFetch {
    return ResourcePlayerAchievementsFetchFromJSONTyped(json, false);
}

export function ResourcePlayerAchievementsFetchFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourcePlayerAchievementsFetch {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': ResourcePlayerAchievementsFetchAttributesFromJSON(json['attributes']),
        'relationships': json['relationships'] == null ? undefined : ResourcePlayerAchievementsFetchRelationshipsFromJSON(json['relationships']),
    };
}

export function ResourcePlayerAchievementsFetchToJSON(value?: ResourcePlayerAchievementsFetch | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'id': value['id'],
        'attributes': ResourcePlayerAchievementsFetchAttributesToJSON(value['attributes']),
        'relationships': ResourcePlayerAchievementsFetchRelationshipsToJSON(value['relationships']),
    };
}

