/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResourcesGamesRelationshipAchievementSetClaimsFetch
 */
export interface ResourcesGamesRelationshipAchievementSetClaimsFetch {
    /**
     * 
     * @type {string}
     * @memberof ResourcesGamesRelationshipAchievementSetClaimsFetch
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof ResourcesGamesRelationshipAchievementSetClaimsFetch
     */
    id: string;
}

/**
 * Check if a given object implements the ResourcesGamesRelationshipAchievementSetClaimsFetch interface.
 */
export function instanceOfResourcesGamesRelationshipAchievementSetClaimsFetch(value: object): value is ResourcesGamesRelationshipAchievementSetClaimsFetch {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ResourcesGamesRelationshipAchievementSetClaimsFetchFromJSON(json: any): ResourcesGamesRelationshipAchievementSetClaimsFetch {
    return ResourcesGamesRelationshipAchievementSetClaimsFetchFromJSONTyped(json, false);
}

export function ResourcesGamesRelationshipAchievementSetClaimsFetchFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourcesGamesRelationshipAchievementSetClaimsFetch {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
    };
}

export function ResourcesGamesRelationshipAchievementSetClaimsFetchToJSON(value?: ResourcesGamesRelationshipAchievementSetClaimsFetch | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'id': value['id'],
    };
}

