/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResourcesAchievementSetsRelationshipAchievementSetVersionsFetch
 */
export interface ResourcesAchievementSetsRelationshipAchievementSetVersionsFetch {
    /**
     * 
     * @type {string}
     * @memberof ResourcesAchievementSetsRelationshipAchievementSetVersionsFetch
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof ResourcesAchievementSetsRelationshipAchievementSetVersionsFetch
     */
    id: string;
}

/**
 * Check if a given object implements the ResourcesAchievementSetsRelationshipAchievementSetVersionsFetch interface.
 */
export function instanceOfResourcesAchievementSetsRelationshipAchievementSetVersionsFetch(value: object): value is ResourcesAchievementSetsRelationshipAchievementSetVersionsFetch {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ResourcesAchievementSetsRelationshipAchievementSetVersionsFetchFromJSON(json: any): ResourcesAchievementSetsRelationshipAchievementSetVersionsFetch {
    return ResourcesAchievementSetsRelationshipAchievementSetVersionsFetchFromJSONTyped(json, false);
}

export function ResourcesAchievementSetsRelationshipAchievementSetVersionsFetchFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourcesAchievementSetsRelationshipAchievementSetVersionsFetch {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
    };
}

export function ResourcesAchievementSetsRelationshipAchievementSetVersionsFetchToJSON(value?: ResourcesAchievementSetsRelationshipAchievementSetVersionsFetch | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'id': value['id'],
    };
}

