/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResourcePlayerGamesFetchAttributes
 */
export interface ResourcePlayerGamesFetchAttributes {
    /**
     * 
     * @type {string}
     * @memberof ResourcePlayerGamesFetchAttributes
     */
    readonly lastPlayedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourcePlayerGamesFetchAttributes
     */
    readonly firstUnlockAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourcePlayerGamesFetchAttributes
     */
    readonly lastUnlockAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourcePlayerGamesFetchAttributes
     */
    readonly lastUnlockHardcoreAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourcePlayerGamesFetchAttributes
     */
    readonly beatenAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourcePlayerGamesFetchAttributes
     */
    readonly beatenHardcoreAt?: string;
    /**
     * 
     * @type {number}
     * @memberof ResourcePlayerGamesFetchAttributes
     */
    readonly playtimeTotalSeconds?: number;
    /**
     * 
     * @type {number}
     * @memberof ResourcePlayerGamesFetchAttributes
     */
    readonly timeToBeatSeconds?: number;
    /**
     * 
     * @type {number}
     * @memberof ResourcePlayerGamesFetchAttributes
     */
    readonly timeToBeatHardcoreSeconds?: number;
}

/**
 * Check if a given object implements the ResourcePlayerGamesFetchAttributes interface.
 */
export function instanceOfResourcePlayerGamesFetchAttributes(value: object): value is ResourcePlayerGamesFetchAttributes {
    return true;
}

export function ResourcePlayerGamesFetchAttributesFromJSON(json: any): ResourcePlayerGamesFetchAttributes {
    return ResourcePlayerGamesFetchAttributesFromJSONTyped(json, false);
}

export function ResourcePlayerGamesFetchAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourcePlayerGamesFetchAttributes {
    if (json == null) {
        return json;
    }
    return {
        
        'lastPlayedAt': json['lastPlayedAt'] == null ? undefined : json['lastPlayedAt'],
        'firstUnlockAt': json['firstUnlockAt'] == null ? undefined : json['firstUnlockAt'],
        'lastUnlockAt': json['lastUnlockAt'] == null ? undefined : json['lastUnlockAt'],
        'lastUnlockHardcoreAt': json['lastUnlockHardcoreAt'] == null ? undefined : json['lastUnlockHardcoreAt'],
        'beatenAt': json['beatenAt'] == null ? undefined : json['beatenAt'],
        'beatenHardcoreAt': json['beatenHardcoreAt'] == null ? undefined : json['beatenHardcoreAt'],
        'playtimeTotalSeconds': json['playtimeTotalSeconds'] == null ? undefined : json['playtimeTotalSeconds'],
        'timeToBeatSeconds': json['timeToBeatSeconds'] == null ? undefined : json['timeToBeatSeconds'],
        'timeToBeatHardcoreSeconds': json['timeToBeatHardcoreSeconds'] == null ? undefined : json['timeToBeatHardcoreSeconds'],
    };
}

export function ResourcePlayerGamesFetchAttributesToJSON(value?: Omit<ResourcePlayerGamesFetchAttributes, 'lastPlayedAt'|'firstUnlockAt'|'lastUnlockAt'|'lastUnlockHardcoreAt'|'beatenAt'|'beatenHardcoreAt'|'playtimeTotalSeconds'|'timeToBeatSeconds'|'timeToBeatHardcoreSeconds'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
    };
}

