/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResourceSystemFetchAttributes } from './ResourceSystemFetchAttributes';
import {
    ResourceSystemFetchAttributesFromJSON,
    ResourceSystemFetchAttributesFromJSONTyped,
    ResourceSystemFetchAttributesToJSON,
} from './ResourceSystemFetchAttributes';

/**
 * May not be present unless "system" is in the "include" header. See `.data[].relationships.system.data` for the lists of IDs which have been included here.
 * @export
 * @interface ResourceSystemFetch
 */
export interface ResourceSystemFetch {
    /**
     * 
     * @type {string}
     * @memberof ResourceSystemFetch
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceSystemFetch
     */
    id: string;
    /**
     * 
     * @type {ResourceSystemFetchAttributes}
     * @memberof ResourceSystemFetch
     */
    attributes: ResourceSystemFetchAttributes;
}

/**
 * Check if a given object implements the ResourceSystemFetch interface.
 */
export function instanceOfResourceSystemFetch(value: object): value is ResourceSystemFetch {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('attributes' in value) || value['attributes'] === undefined) return false;
    return true;
}

export function ResourceSystemFetchFromJSON(json: any): ResourceSystemFetch {
    return ResourceSystemFetchFromJSONTyped(json, false);
}

export function ResourceSystemFetchFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceSystemFetch {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': ResourceSystemFetchAttributesFromJSON(json['attributes']),
    };
}

export function ResourceSystemFetchToJSON(value?: ResourceSystemFetch | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'id': value['id'],
        'attributes': ResourceSystemFetchAttributesToJSON(value['attributes']),
    };
}

