/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Awards } from './Awards';
import {
    AwardsFromJSON,
    AwardsFromJSONTyped,
    AwardsToJSON,
} from './Awards';
import type { PlayerAchievements } from './PlayerAchievements';
import {
    PlayerAchievementsFromJSON,
    PlayerAchievementsFromJSONTyped,
    PlayerAchievementsToJSON,
} from './PlayerAchievements';
import type { PlayerGames } from './PlayerGames';
import {
    PlayerGamesFromJSON,
    PlayerGamesFromJSONTyped,
    PlayerGamesToJSON,
} from './PlayerGames';
import type { PlayerAchievementSets } from './PlayerAchievementSets';
import {
    PlayerAchievementSetsFromJSON,
    PlayerAchievementSetsFromJSONTyped,
    PlayerAchievementSetsToJSON,
} from './PlayerAchievementSets';
import type { Following } from './Following';
import {
    FollowingFromJSON,
    FollowingFromJSONTyped,
    FollowingToJSON,
} from './Following';
import type { Tickets } from './Tickets';
import {
    TicketsFromJSON,
    TicketsFromJSONTyped,
    TicketsToJSON,
} from './Tickets';
import type { Followers } from './Followers';
import {
    FollowersFromJSON,
    FollowersFromJSONTyped,
    FollowersToJSON,
} from './Followers';
import type { WallComments } from './WallComments';
import {
    WallCommentsFromJSON,
    WallCommentsFromJSONTyped,
    WallCommentsToJSON,
} from './WallComments';
import type { AchievementSetClaims } from './AchievementSetClaims';
import {
    AchievementSetClaimsFromJSON,
    AchievementSetClaimsFromJSONTyped,
    AchievementSetClaimsToJSON,
} from './AchievementSetClaims';

/**
 * 
 * @export
 * @interface ResourceDeveloperFetchRelationships
 */
export interface ResourceDeveloperFetchRelationships {
    /**
     * 
     * @type {AchievementSetClaims}
     * @memberof ResourceDeveloperFetchRelationships
     */
    achievementSetClaims?: AchievementSetClaims;
    /**
     * 
     * @type {PlayerAchievements}
     * @memberof ResourceDeveloperFetchRelationships
     */
    playerAchievements?: PlayerAchievements;
    /**
     * 
     * @type {PlayerAchievementSets}
     * @memberof ResourceDeveloperFetchRelationships
     */
    playerAchievementSets?: PlayerAchievementSets;
    /**
     * 
     * @type {PlayerGames}
     * @memberof ResourceDeveloperFetchRelationships
     */
    playerGames?: PlayerGames;
    /**
     * 
     * @type {Tickets}
     * @memberof ResourceDeveloperFetchRelationships
     */
    tickets?: Tickets;
    /**
     * 
     * @type {WallComments}
     * @memberof ResourceDeveloperFetchRelationships
     */
    wallComments?: WallComments;
    /**
     * 
     * @type {Awards}
     * @memberof ResourceDeveloperFetchRelationships
     */
    awards?: Awards;
    /**
     * 
     * @type {Followers}
     * @memberof ResourceDeveloperFetchRelationships
     */
    followers?: Followers;
    /**
     * 
     * @type {Following}
     * @memberof ResourceDeveloperFetchRelationships
     */
    following?: Following;
}

/**
 * Check if a given object implements the ResourceDeveloperFetchRelationships interface.
 */
export function instanceOfResourceDeveloperFetchRelationships(value: object): value is ResourceDeveloperFetchRelationships {
    return true;
}

export function ResourceDeveloperFetchRelationshipsFromJSON(json: any): ResourceDeveloperFetchRelationships {
    return ResourceDeveloperFetchRelationshipsFromJSONTyped(json, false);
}

export function ResourceDeveloperFetchRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceDeveloperFetchRelationships {
    if (json == null) {
        return json;
    }
    return {
        
        'achievementSetClaims': json['achievementSetClaims'] == null ? undefined : AchievementSetClaimsFromJSON(json['achievementSetClaims']),
        'playerAchievements': json['playerAchievements'] == null ? undefined : PlayerAchievementsFromJSON(json['playerAchievements']),
        'playerAchievementSets': json['playerAchievementSets'] == null ? undefined : PlayerAchievementSetsFromJSON(json['playerAchievementSets']),
        'playerGames': json['playerGames'] == null ? undefined : PlayerGamesFromJSON(json['playerGames']),
        'tickets': json['tickets'] == null ? undefined : TicketsFromJSON(json['tickets']),
        'wallComments': json['wallComments'] == null ? undefined : WallCommentsFromJSON(json['wallComments']),
        'awards': json['awards'] == null ? undefined : AwardsFromJSON(json['awards']),
        'followers': json['followers'] == null ? undefined : FollowersFromJSON(json['followers']),
        'following': json['following'] == null ? undefined : FollowingFromJSON(json['following']),
    };
}

export function ResourceDeveloperFetchRelationshipsToJSON(value?: ResourceDeveloperFetchRelationships | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'achievementSetClaims': AchievementSetClaimsToJSON(value['achievementSetClaims']),
        'playerAchievements': PlayerAchievementsToJSON(value['playerAchievements']),
        'playerAchievementSets': PlayerAchievementSetsToJSON(value['playerAchievementSets']),
        'playerGames': PlayerGamesToJSON(value['playerGames']),
        'tickets': TicketsToJSON(value['tickets']),
        'wallComments': WallCommentsToJSON(value['wallComments']),
        'awards': AwardsToJSON(value['awards']),
        'followers': FollowersToJSON(value['followers']),
        'following': FollowingToJSON(value['following']),
    };
}

