/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Game } from './Game';
import {
    GameFromJSON,
    GameFromJSONTyped,
    GameToJSON,
} from './Game';
import type { AchievementSets } from './AchievementSets';
import {
    AchievementSetsFromJSON,
    AchievementSetsFromJSONTyped,
    AchievementSetsToJSON,
} from './AchievementSets';
import type { PlayerAchievementSets1 } from './PlayerAchievementSets1';
import {
    PlayerAchievementSets1FromJSON,
    PlayerAchievementSets1FromJSONTyped,
    PlayerAchievementSets1ToJSON,
} from './PlayerAchievementSets1';

/**
 * 
 * @export
 * @interface ResourcePlayerGamesFetchRelationships
 */
export interface ResourcePlayerGamesFetchRelationships {
    /**
     * 
     * @type {AchievementSets}
     * @memberof ResourcePlayerGamesFetchRelationships
     */
    achievementSets?: AchievementSets;
    /**
     * 
     * @type {Game}
     * @memberof ResourcePlayerGamesFetchRelationships
     */
    game?: Game;
    /**
     * 
     * @type {PlayerAchievementSets1}
     * @memberof ResourcePlayerGamesFetchRelationships
     */
    playerAchievementSets?: PlayerAchievementSets1;
}

/**
 * Check if a given object implements the ResourcePlayerGamesFetchRelationships interface.
 */
export function instanceOfResourcePlayerGamesFetchRelationships(value: object): value is ResourcePlayerGamesFetchRelationships {
    return true;
}

export function ResourcePlayerGamesFetchRelationshipsFromJSON(json: any): ResourcePlayerGamesFetchRelationships {
    return ResourcePlayerGamesFetchRelationshipsFromJSONTyped(json, false);
}

export function ResourcePlayerGamesFetchRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourcePlayerGamesFetchRelationships {
    if (json == null) {
        return json;
    }
    return {
        
        'achievementSets': json['achievementSets'] == null ? undefined : AchievementSetsFromJSON(json['achievementSets']),
        'game': json['game'] == null ? undefined : GameFromJSON(json['game']),
        'playerAchievementSets': json['playerAchievementSets'] == null ? undefined : PlayerAchievementSets1FromJSON(json['playerAchievementSets']),
    };
}

export function ResourcePlayerGamesFetchRelationshipsToJSON(value?: ResourcePlayerGamesFetchRelationships | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'achievementSets': AchievementSetsToJSON(value['achievementSets']),
        'game': GameToJSON(value['game']),
        'playerAchievementSets': PlayerAchievementSets1ToJSON(value['playerAchievementSets']),
    };
}

