/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResourceAchievementFetchAttributes } from './ResourceAchievementFetchAttributes';
import {
    ResourceAchievementFetchAttributesFromJSON,
    ResourceAchievementFetchAttributesFromJSONTyped,
    ResourceAchievementFetchAttributesToJSON,
} from './ResourceAchievementFetchAttributes';
import type { ResourceAchievementFetchRelationships } from './ResourceAchievementFetchRelationships';
import {
    ResourceAchievementFetchRelationshipsFromJSON,
    ResourceAchievementFetchRelationshipsFromJSONTyped,
    ResourceAchievementFetchRelationshipsToJSON,
} from './ResourceAchievementFetchRelationships';

/**
 * 
 * @export
 * @interface ResourcesAchievementsResourceFetch
 */
export interface ResourcesAchievementsResourceFetch {
    /**
     * 
     * @type {string}
     * @memberof ResourcesAchievementsResourceFetch
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof ResourcesAchievementsResourceFetch
     */
    id: string;
    /**
     * 
     * @type {ResourceAchievementFetchAttributes}
     * @memberof ResourcesAchievementsResourceFetch
     */
    attributes: ResourceAchievementFetchAttributes;
    /**
     * 
     * @type {ResourceAchievementFetchRelationships}
     * @memberof ResourcesAchievementsResourceFetch
     */
    relationships?: ResourceAchievementFetchRelationships;
}

/**
 * Check if a given object implements the ResourcesAchievementsResourceFetch interface.
 */
export function instanceOfResourcesAchievementsResourceFetch(value: object): value is ResourcesAchievementsResourceFetch {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('attributes' in value) || value['attributes'] === undefined) return false;
    return true;
}

export function ResourcesAchievementsResourceFetchFromJSON(json: any): ResourcesAchievementsResourceFetch {
    return ResourcesAchievementsResourceFetchFromJSONTyped(json, false);
}

export function ResourcesAchievementsResourceFetchFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourcesAchievementsResourceFetch {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': ResourceAchievementFetchAttributesFromJSON(json['attributes']),
        'relationships': json['relationships'] == null ? undefined : ResourceAchievementFetchRelationshipsFromJSON(json['relationships']),
    };
}

export function ResourcesAchievementsResourceFetchToJSON(value?: ResourcesAchievementsResourceFetch | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'id': value['id'],
        'attributes': ResourceAchievementFetchAttributesToJSON(value['attributes']),
        'relationships': ResourceAchievementFetchRelationshipsToJSON(value['relationships']),
    };
}

