/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResourcesAchievementsRelationshipTicketsFetch
 */
export interface ResourcesAchievementsRelationshipTicketsFetch {
    /**
     * 
     * @type {string}
     * @memberof ResourcesAchievementsRelationshipTicketsFetch
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof ResourcesAchievementsRelationshipTicketsFetch
     */
    id: string;
}

/**
 * Check if a given object implements the ResourcesAchievementsRelationshipTicketsFetch interface.
 */
export function instanceOfResourcesAchievementsRelationshipTicketsFetch(value: object): value is ResourcesAchievementsRelationshipTicketsFetch {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ResourcesAchievementsRelationshipTicketsFetchFromJSON(json: any): ResourcesAchievementsRelationshipTicketsFetch {
    return ResourcesAchievementsRelationshipTicketsFetchFromJSONTyped(json, false);
}

export function ResourcesAchievementsRelationshipTicketsFetchFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourcesAchievementsRelationshipTicketsFetch {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
    };
}

export function ResourcesAchievementsRelationshipTicketsFetchToJSON(value?: ResourcesAchievementsRelationshipTicketsFetch | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'id': value['id'],
    };
}

