/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResourceTicketsFetchAttributes
 */
export interface ResourceTicketsFetchAttributes {
    /**
     * 
     * @type {string}
     * @memberof ResourceTicketsFetchAttributes
     */
    readonly state?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceTicketsFetchAttributes
     */
    readonly type?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceTicketsFetchAttributes
     */
    readonly body?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ResourceTicketsFetchAttributes
     */
    readonly hardcore?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ResourceTicketsFetchAttributes
     */
    readonly reportedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceTicketsFetchAttributes
     */
    readonly resolvedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceTicketsFetchAttributes
     */
    readonly ticketableType?: string;
    /**
     * 
     * @type {number}
     * @memberof ResourceTicketsFetchAttributes
     */
    readonly ticketableId?: number;
    /**
     * 
     * @type {string}
     * @memberof ResourceTicketsFetchAttributes
     */
    readonly gameIconUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceTicketsFetchAttributes
     */
    readonly systemName?: string;
}

/**
 * Check if a given object implements the ResourceTicketsFetchAttributes interface.
 */
export function instanceOfResourceTicketsFetchAttributes(value: object): value is ResourceTicketsFetchAttributes {
    return true;
}

export function ResourceTicketsFetchAttributesFromJSON(json: any): ResourceTicketsFetchAttributes {
    return ResourceTicketsFetchAttributesFromJSONTyped(json, false);
}

export function ResourceTicketsFetchAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceTicketsFetchAttributes {
    if (json == null) {
        return json;
    }
    return {
        
        'state': json['state'] == null ? undefined : json['state'],
        'type': json['type'] == null ? undefined : json['type'],
        'body': json['body'] == null ? undefined : json['body'],
        'hardcore': json['hardcore'] == null ? undefined : json['hardcore'],
        'reportedAt': json['reportedAt'] == null ? undefined : json['reportedAt'],
        'resolvedAt': json['resolvedAt'] == null ? undefined : json['resolvedAt'],
        'ticketableType': json['ticketableType'] == null ? undefined : json['ticketableType'],
        'ticketableId': json['ticketableId'] == null ? undefined : json['ticketableId'],
        'gameIconUrl': json['gameIconUrl'] == null ? undefined : json['gameIconUrl'],
        'systemName': json['systemName'] == null ? undefined : json['systemName'],
    };
}

export function ResourceTicketsFetchAttributesToJSON(value?: Omit<ResourceTicketsFetchAttributes, 'state'|'type'|'body'|'hardcore'|'reportedAt'|'resolvedAt'|'ticketableType'|'ticketableId'|'gameIconUrl'|'systemName'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
    };
}

