/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResourceDeveloperFetchAttributes
 */
export interface ResourceDeveloperFetchAttributes {
    /**
     * 
     * @type {string}
     * @memberof ResourceDeveloperFetchAttributes
     */
    readonly displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceDeveloperFetchAttributes
     */
    readonly avatarUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceDeveloperFetchAttributes
     */
    readonly motto?: string;
    /**
     * 
     * @type {number}
     * @memberof ResourceDeveloperFetchAttributes
     */
    readonly points?: number;
    /**
     * 
     * @type {number}
     * @memberof ResourceDeveloperFetchAttributes
     */
    readonly pointsHardcore?: number;
    /**
     * 
     * @type {number}
     * @memberof ResourceDeveloperFetchAttributes
     */
    readonly pointsWeighted?: number;
    /**
     * 
     * @type {number}
     * @memberof ResourceDeveloperFetchAttributes
     */
    readonly yieldUnlocks?: number;
    /**
     * 
     * @type {number}
     * @memberof ResourceDeveloperFetchAttributes
     */
    readonly yieldPoints?: number;
    /**
     * 
     * @type {string}
     * @memberof ResourceDeveloperFetchAttributes
     */
    readonly joinedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceDeveloperFetchAttributes
     */
    readonly lastActivityAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceDeveloperFetchAttributes
     */
    readonly deletedAt?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ResourceDeveloperFetchAttributes
     */
    readonly isUnranked?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ResourceDeveloperFetchAttributes
     */
    readonly isUserWallActive?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ResourceDeveloperFetchAttributes
     */
    readonly richPresence?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceDeveloperFetchAttributes
     */
    readonly richPresenceUpdatedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceDeveloperFetchAttributes
     */
    readonly visibleRole?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ResourceDeveloperFetchAttributes
     */
    readonly displayableRoles?: Array<string>;
}

/**
 * Check if a given object implements the ResourceDeveloperFetchAttributes interface.
 */
export function instanceOfResourceDeveloperFetchAttributes(value: object): value is ResourceDeveloperFetchAttributes {
    return true;
}

export function ResourceDeveloperFetchAttributesFromJSON(json: any): ResourceDeveloperFetchAttributes {
    return ResourceDeveloperFetchAttributesFromJSONTyped(json, false);
}

export function ResourceDeveloperFetchAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceDeveloperFetchAttributes {
    if (json == null) {
        return json;
    }
    return {
        
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
        'avatarUrl': json['avatarUrl'] == null ? undefined : json['avatarUrl'],
        'motto': json['motto'] == null ? undefined : json['motto'],
        'points': json['points'] == null ? undefined : json['points'],
        'pointsHardcore': json['pointsHardcore'] == null ? undefined : json['pointsHardcore'],
        'pointsWeighted': json['pointsWeighted'] == null ? undefined : json['pointsWeighted'],
        'yieldUnlocks': json['yieldUnlocks'] == null ? undefined : json['yieldUnlocks'],
        'yieldPoints': json['yieldPoints'] == null ? undefined : json['yieldPoints'],
        'joinedAt': json['joinedAt'] == null ? undefined : json['joinedAt'],
        'lastActivityAt': json['lastActivityAt'] == null ? undefined : json['lastActivityAt'],
        'deletedAt': json['deletedAt'] == null ? undefined : json['deletedAt'],
        'isUnranked': json['isUnranked'] == null ? undefined : json['isUnranked'],
        'isUserWallActive': json['isUserWallActive'] == null ? undefined : json['isUserWallActive'],
        'richPresence': json['richPresence'] == null ? undefined : json['richPresence'],
        'richPresenceUpdatedAt': json['richPresenceUpdatedAt'] == null ? undefined : json['richPresenceUpdatedAt'],
        'visibleRole': json['visibleRole'] == null ? undefined : json['visibleRole'],
        'displayableRoles': json['displayableRoles'] == null ? undefined : json['displayableRoles'],
    };
}

export function ResourceDeveloperFetchAttributesToJSON(value?: Omit<ResourceDeveloperFetchAttributes, 'displayName'|'avatarUrl'|'motto'|'points'|'pointsHardcore'|'pointsWeighted'|'yieldUnlocks'|'yieldPoints'|'joinedAt'|'lastActivityAt'|'deletedAt'|'isUnranked'|'isUserWallActive'|'richPresence'|'richPresenceUpdatedAt'|'visibleRole'|'displayableRoles'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
    };
}

