/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResourcesUsersRelationshipAchievementSetClaimsFetch
 */
export interface ResourcesUsersRelationshipAchievementSetClaimsFetch {
    /**
     * 
     * @type {string}
     * @memberof ResourcesUsersRelationshipAchievementSetClaimsFetch
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof ResourcesUsersRelationshipAchievementSetClaimsFetch
     */
    id: string;
}

/**
 * Check if a given object implements the ResourcesUsersRelationshipAchievementSetClaimsFetch interface.
 */
export function instanceOfResourcesUsersRelationshipAchievementSetClaimsFetch(value: object): value is ResourcesUsersRelationshipAchievementSetClaimsFetch {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ResourcesUsersRelationshipAchievementSetClaimsFetchFromJSON(json: any): ResourcesUsersRelationshipAchievementSetClaimsFetch {
    return ResourcesUsersRelationshipAchievementSetClaimsFetchFromJSONTyped(json, false);
}

export function ResourcesUsersRelationshipAchievementSetClaimsFetchFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourcesUsersRelationshipAchievementSetClaimsFetch {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
    };
}

export function ResourcesUsersRelationshipAchievementSetClaimsFetchToJSON(value?: ResourcesUsersRelationshipAchievementSetClaimsFetch | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'id': value['id'],
    };
}

