/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResourcesUsersRelationshipPlayerAchievementSetsFetch
 */
export interface ResourcesUsersRelationshipPlayerAchievementSetsFetch {
    /**
     * 
     * @type {string}
     * @memberof ResourcesUsersRelationshipPlayerAchievementSetsFetch
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof ResourcesUsersRelationshipPlayerAchievementSetsFetch
     */
    id: string;
}

/**
 * Check if a given object implements the ResourcesUsersRelationshipPlayerAchievementSetsFetch interface.
 */
export function instanceOfResourcesUsersRelationshipPlayerAchievementSetsFetch(value: object): value is ResourcesUsersRelationshipPlayerAchievementSetsFetch {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ResourcesUsersRelationshipPlayerAchievementSetsFetchFromJSON(json: any): ResourcesUsersRelationshipPlayerAchievementSetsFetch {
    return ResourcesUsersRelationshipPlayerAchievementSetsFetchFromJSONTyped(json, false);
}

export function ResourcesUsersRelationshipPlayerAchievementSetsFetchFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourcesUsersRelationshipPlayerAchievementSetsFetch {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
    };
}

export function ResourcesUsersRelationshipPlayerAchievementSetsFetchToJSON(value?: ResourcesUsersRelationshipPlayerAchievementSetsFetch | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'id': value['id'],
    };
}

