/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResourceAwardsFetch1Relationships } from './ResourceAwardsFetch1Relationships';
import {
    ResourceAwardsFetch1RelationshipsFromJSON,
    ResourceAwardsFetch1RelationshipsFromJSONTyped,
    ResourceAwardsFetch1RelationshipsToJSON,
} from './ResourceAwardsFetch1Relationships';
import type { ResourceAwardsFetch1Attributes } from './ResourceAwardsFetch1Attributes';
import {
    ResourceAwardsFetch1AttributesFromJSON,
    ResourceAwardsFetch1AttributesFromJSONTyped,
    ResourceAwardsFetch1AttributesToJSON,
} from './ResourceAwardsFetch1Attributes';

/**
 * May not be present unless "awards" is in the "include" header. See `.data[].relationships.awards.data` for the lists of IDs which have been included here.
 * @export
 * @interface ResourceAwardsFetch1
 */
export interface ResourceAwardsFetch1 {
    /**
     * 
     * @type {string}
     * @memberof ResourceAwardsFetch1
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceAwardsFetch1
     */
    id: string;
    /**
     * 
     * @type {ResourceAwardsFetch1Attributes}
     * @memberof ResourceAwardsFetch1
     */
    attributes: ResourceAwardsFetch1Attributes;
    /**
     * 
     * @type {ResourceAwardsFetch1Relationships}
     * @memberof ResourceAwardsFetch1
     */
    relationships?: ResourceAwardsFetch1Relationships;
}

/**
 * Check if a given object implements the ResourceAwardsFetch1 interface.
 */
export function instanceOfResourceAwardsFetch1(value: object): value is ResourceAwardsFetch1 {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('attributes' in value) || value['attributes'] === undefined) return false;
    return true;
}

export function ResourceAwardsFetch1FromJSON(json: any): ResourceAwardsFetch1 {
    return ResourceAwardsFetch1FromJSONTyped(json, false);
}

export function ResourceAwardsFetch1FromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceAwardsFetch1 {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': ResourceAwardsFetch1AttributesFromJSON(json['attributes']),
        'relationships': json['relationships'] == null ? undefined : ResourceAwardsFetch1RelationshipsFromJSON(json['relationships']),
    };
}

export function ResourceAwardsFetch1ToJSON(value?: ResourceAwardsFetch1 | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'id': value['id'],
        'attributes': ResourceAwardsFetch1AttributesToJSON(value['attributes']),
        'relationships': ResourceAwardsFetch1RelationshipsToJSON(value['relationships']),
    };
}

