/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Achievement1 } from './Achievement1';
import {
    Achievement1FromJSON,
    Achievement1FromJSONTyped,
    Achievement1ToJSON,
} from './Achievement1';
import type { Leaderboard } from './Leaderboard';
import {
    LeaderboardFromJSON,
    LeaderboardFromJSONTyped,
    LeaderboardToJSON,
} from './Leaderboard';
import type { Resolver } from './Resolver';
import {
    ResolverFromJSON,
    ResolverFromJSONTyped,
    ResolverToJSON,
} from './Resolver';
import type { Reporter } from './Reporter';
import {
    ReporterFromJSON,
    ReporterFromJSONTyped,
    ReporterToJSON,
} from './Reporter';
import type { Author1 } from './Author1';
import {
    Author1FromJSON,
    Author1FromJSONTyped,
    Author1ToJSON,
} from './Author1';

/**
 * 
 * @export
 * @interface ResourceTicketsFetchRelationships
 */
export interface ResourceTicketsFetchRelationships {
    /**
     * 
     * @type {Achievement1}
     * @memberof ResourceTicketsFetchRelationships
     */
    achievement?: Achievement1;
    /**
     * 
     * @type {Leaderboard}
     * @memberof ResourceTicketsFetchRelationships
     */
    leaderboard?: Leaderboard;
    /**
     * 
     * @type {Reporter}
     * @memberof ResourceTicketsFetchRelationships
     */
    reporter?: Reporter;
    /**
     * 
     * @type {Resolver}
     * @memberof ResourceTicketsFetchRelationships
     */
    resolver?: Resolver;
    /**
     * 
     * @type {Author1}
     * @memberof ResourceTicketsFetchRelationships
     */
    author?: Author1;
}

/**
 * Check if a given object implements the ResourceTicketsFetchRelationships interface.
 */
export function instanceOfResourceTicketsFetchRelationships(value: object): value is ResourceTicketsFetchRelationships {
    return true;
}

export function ResourceTicketsFetchRelationshipsFromJSON(json: any): ResourceTicketsFetchRelationships {
    return ResourceTicketsFetchRelationshipsFromJSONTyped(json, false);
}

export function ResourceTicketsFetchRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceTicketsFetchRelationships {
    if (json == null) {
        return json;
    }
    return {
        
        'achievement': json['achievement'] == null ? undefined : Achievement1FromJSON(json['achievement']),
        'leaderboard': json['leaderboard'] == null ? undefined : LeaderboardFromJSON(json['leaderboard']),
        'reporter': json['reporter'] == null ? undefined : ReporterFromJSON(json['reporter']),
        'resolver': json['resolver'] == null ? undefined : ResolverFromJSON(json['resolver']),
        'author': json['author'] == null ? undefined : Author1FromJSON(json['author']),
    };
}

export function ResourceTicketsFetchRelationshipsToJSON(value?: ResourceTicketsFetchRelationships | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'achievement': Achievement1ToJSON(value['achievement']),
        'leaderboard': LeaderboardToJSON(value['leaderboard']),
        'reporter': ReporterToJSON(value['reporter']),
        'resolver': ResolverToJSON(value['resolver']),
        'author': Author1ToJSON(value['author']),
    };
}

