/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Games } from './Games';
import {
    GamesFromJSON,
    GamesFromJSONTyped,
    GamesToJSON,
} from './Games';
import type { Links } from './Links';
import {
    LinksFromJSON,
    LinksFromJSONTyped,
    LinksToJSON,
} from './Links';

/**
 * 
 * @export
 * @interface ResourcesHubsResourceFetchRelationships
 */
export interface ResourcesHubsResourceFetchRelationships {
    /**
     * 
     * @type {Games}
     * @memberof ResourcesHubsResourceFetchRelationships
     */
    games?: Games;
    /**
     * 
     * @type {Links}
     * @memberof ResourcesHubsResourceFetchRelationships
     */
    links?: Links;
}

/**
 * Check if a given object implements the ResourcesHubsResourceFetchRelationships interface.
 */
export function instanceOfResourcesHubsResourceFetchRelationships(value: object): value is ResourcesHubsResourceFetchRelationships {
    return true;
}

export function ResourcesHubsResourceFetchRelationshipsFromJSON(json: any): ResourcesHubsResourceFetchRelationships {
    return ResourcesHubsResourceFetchRelationshipsFromJSONTyped(json, false);
}

export function ResourcesHubsResourceFetchRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourcesHubsResourceFetchRelationships {
    if (json == null) {
        return json;
    }
    return {
        
        'games': json['games'] == null ? undefined : GamesFromJSON(json['games']),
        'links': json['links'] == null ? undefined : LinksFromJSON(json['links']),
    };
}

export function ResourcesHubsResourceFetchRelationshipsToJSON(value?: ResourcesHubsResourceFetchRelationships | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'games': GamesToJSON(value['games']),
        'links': LinksToJSON(value['links']),
    };
}

