/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResourcePlayerGamesFetchAttributes } from './ResourcePlayerGamesFetchAttributes';
import {
    ResourcePlayerGamesFetchAttributesFromJSON,
    ResourcePlayerGamesFetchAttributesFromJSONTyped,
    ResourcePlayerGamesFetchAttributesToJSON,
} from './ResourcePlayerGamesFetchAttributes';
import type { ResourcePlayerGamesFetchRelationships } from './ResourcePlayerGamesFetchRelationships';
import {
    ResourcePlayerGamesFetchRelationshipsFromJSON,
    ResourcePlayerGamesFetchRelationshipsFromJSONTyped,
    ResourcePlayerGamesFetchRelationshipsToJSON,
} from './ResourcePlayerGamesFetchRelationships';

/**
 * May not be present unless "playerGames" is in the "include" header. See `.data[].relationships.playerGames.data` for the lists of IDs which have been included here.
 * @export
 * @interface ResourcePlayerGamesFetch
 */
export interface ResourcePlayerGamesFetch {
    /**
     * 
     * @type {string}
     * @memberof ResourcePlayerGamesFetch
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof ResourcePlayerGamesFetch
     */
    id: string;
    /**
     * 
     * @type {ResourcePlayerGamesFetchAttributes}
     * @memberof ResourcePlayerGamesFetch
     */
    attributes: ResourcePlayerGamesFetchAttributes;
    /**
     * 
     * @type {ResourcePlayerGamesFetchRelationships}
     * @memberof ResourcePlayerGamesFetch
     */
    relationships?: ResourcePlayerGamesFetchRelationships;
}

/**
 * Check if a given object implements the ResourcePlayerGamesFetch interface.
 */
export function instanceOfResourcePlayerGamesFetch(value: object): value is ResourcePlayerGamesFetch {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('attributes' in value) || value['attributes'] === undefined) return false;
    return true;
}

export function ResourcePlayerGamesFetchFromJSON(json: any): ResourcePlayerGamesFetch {
    return ResourcePlayerGamesFetchFromJSONTyped(json, false);
}

export function ResourcePlayerGamesFetchFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourcePlayerGamesFetch {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': ResourcePlayerGamesFetchAttributesFromJSON(json['attributes']),
        'relationships': json['relationships'] == null ? undefined : ResourcePlayerGamesFetchRelationshipsFromJSON(json['relationships']),
    };
}

export function ResourcePlayerGamesFetchToJSON(value?: ResourcePlayerGamesFetch | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'id': value['id'],
        'attributes': ResourcePlayerGamesFetchAttributesToJSON(value['attributes']),
        'relationships': ResourcePlayerGamesFetchRelationshipsToJSON(value['relationships']),
    };
}

