/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Comments } from './Comments';
import {
    CommentsFromJSON,
    CommentsFromJSONTyped,
    CommentsToJSON,
} from './Comments';
import type { AchievementSet } from './AchievementSet';
import {
    AchievementSetFromJSON,
    AchievementSetFromJSONTyped,
    AchievementSetToJSON,
} from './AchievementSet';
import type { Games } from './Games';
import {
    GamesFromJSON,
    GamesFromJSONTyped,
    GamesToJSON,
} from './Games';
import type { Developer } from './Developer';
import {
    DeveloperFromJSON,
    DeveloperFromJSONTyped,
    DeveloperToJSON,
} from './Developer';
import type { PlayerAchievements1 } from './PlayerAchievements1';
import {
    PlayerAchievements1FromJSON,
    PlayerAchievements1FromJSONTyped,
    PlayerAchievements1ToJSON,
} from './PlayerAchievements1';
import type { Tickets1 } from './Tickets1';
import {
    Tickets1FromJSON,
    Tickets1FromJSONTyped,
    Tickets1ToJSON,
} from './Tickets1';

/**
 * 
 * @export
 * @interface ResourceAchievementFetchRelationships
 */
export interface ResourceAchievementFetchRelationships {
    /**
     * 
     * @type {Developer}
     * @memberof ResourceAchievementFetchRelationships
     */
    developer?: Developer;
    /**
     * 
     * @type {AchievementSet}
     * @memberof ResourceAchievementFetchRelationships
     */
    achievementSet?: AchievementSet;
    /**
     * 
     * @type {Comments}
     * @memberof ResourceAchievementFetchRelationships
     */
    comments?: Comments;
    /**
     * 
     * @type {Games}
     * @memberof ResourceAchievementFetchRelationships
     */
    games?: Games;
    /**
     * 
     * @type {PlayerAchievements1}
     * @memberof ResourceAchievementFetchRelationships
     */
    playerAchievements?: PlayerAchievements1;
    /**
     * 
     * @type {Tickets1}
     * @memberof ResourceAchievementFetchRelationships
     */
    tickets?: Tickets1;
}

/**
 * Check if a given object implements the ResourceAchievementFetchRelationships interface.
 */
export function instanceOfResourceAchievementFetchRelationships(value: object): value is ResourceAchievementFetchRelationships {
    return true;
}

export function ResourceAchievementFetchRelationshipsFromJSON(json: any): ResourceAchievementFetchRelationships {
    return ResourceAchievementFetchRelationshipsFromJSONTyped(json, false);
}

export function ResourceAchievementFetchRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceAchievementFetchRelationships {
    if (json == null) {
        return json;
    }
    return {
        
        'developer': json['developer'] == null ? undefined : DeveloperFromJSON(json['developer']),
        'achievementSet': json['achievementSet'] == null ? undefined : AchievementSetFromJSON(json['achievementSet']),
        'comments': json['comments'] == null ? undefined : CommentsFromJSON(json['comments']),
        'games': json['games'] == null ? undefined : GamesFromJSON(json['games']),
        'playerAchievements': json['playerAchievements'] == null ? undefined : PlayerAchievements1FromJSON(json['playerAchievements']),
        'tickets': json['tickets'] == null ? undefined : Tickets1FromJSON(json['tickets']),
    };
}

export function ResourceAchievementFetchRelationshipsToJSON(value?: ResourceAchievementFetchRelationships | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'developer': DeveloperToJSON(value['developer']),
        'achievementSet': AchievementSetToJSON(value['achievementSet']),
        'comments': CommentsToJSON(value['comments']),
        'games': GamesToJSON(value['games']),
        'playerAchievements': PlayerAchievements1ToJSON(value['playerAchievements']),
        'tickets': Tickets1ToJSON(value['tickets']),
    };
}

