/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Author } from './Author';
import {
    AuthorFromJSON,
    AuthorFromJSONTyped,
    AuthorToJSON,
} from './Author';

/**
 * 
 * @export
 * @interface ResourceCommentsFetchRelationships
 */
export interface ResourceCommentsFetchRelationships {
    /**
     * 
     * @type {Author}
     * @memberof ResourceCommentsFetchRelationships
     */
    author?: Author;
}

/**
 * Check if a given object implements the ResourceCommentsFetchRelationships interface.
 */
export function instanceOfResourceCommentsFetchRelationships(value: object): value is ResourceCommentsFetchRelationships {
    return true;
}

export function ResourceCommentsFetchRelationshipsFromJSON(json: any): ResourceCommentsFetchRelationships {
    return ResourceCommentsFetchRelationshipsFromJSONTyped(json, false);
}

export function ResourceCommentsFetchRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceCommentsFetchRelationships {
    if (json == null) {
        return json;
    }
    return {
        
        'author': json['author'] == null ? undefined : AuthorFromJSON(json['author']),
    };
}

export function ResourceCommentsFetchRelationshipsToJSON(value?: ResourceCommentsFetchRelationships | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'author': AuthorToJSON(value['author']),
    };
}

