/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResourceEntriesFetchAttributes } from './ResourceEntriesFetchAttributes';
import {
    ResourceEntriesFetchAttributesFromJSON,
    ResourceEntriesFetchAttributesFromJSONTyped,
    ResourceEntriesFetchAttributesToJSON,
} from './ResourceEntriesFetchAttributes';
import type { ResourceEntriesFetchRelationships } from './ResourceEntriesFetchRelationships';
import {
    ResourceEntriesFetchRelationshipsFromJSON,
    ResourceEntriesFetchRelationshipsFromJSONTyped,
    ResourceEntriesFetchRelationshipsToJSON,
} from './ResourceEntriesFetchRelationships';

/**
 * 
 * @export
 * @interface ResourcesLeaderboardEntriesResourceFetch
 */
export interface ResourcesLeaderboardEntriesResourceFetch {
    /**
     * 
     * @type {string}
     * @memberof ResourcesLeaderboardEntriesResourceFetch
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof ResourcesLeaderboardEntriesResourceFetch
     */
    id: string;
    /**
     * 
     * @type {ResourceEntriesFetchAttributes}
     * @memberof ResourcesLeaderboardEntriesResourceFetch
     */
    attributes: ResourceEntriesFetchAttributes;
    /**
     * 
     * @type {ResourceEntriesFetchRelationships}
     * @memberof ResourcesLeaderboardEntriesResourceFetch
     */
    relationships?: ResourceEntriesFetchRelationships;
}

/**
 * Check if a given object implements the ResourcesLeaderboardEntriesResourceFetch interface.
 */
export function instanceOfResourcesLeaderboardEntriesResourceFetch(value: object): value is ResourcesLeaderboardEntriesResourceFetch {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('attributes' in value) || value['attributes'] === undefined) return false;
    return true;
}

export function ResourcesLeaderboardEntriesResourceFetchFromJSON(json: any): ResourcesLeaderboardEntriesResourceFetch {
    return ResourcesLeaderboardEntriesResourceFetchFromJSONTyped(json, false);
}

export function ResourcesLeaderboardEntriesResourceFetchFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourcesLeaderboardEntriesResourceFetch {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': ResourceEntriesFetchAttributesFromJSON(json['attributes']),
        'relationships': json['relationships'] == null ? undefined : ResourceEntriesFetchRelationshipsFromJSON(json['relationships']),
    };
}

export function ResourcesLeaderboardEntriesResourceFetchToJSON(value?: ResourcesLeaderboardEntriesResourceFetch | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'id': value['id'],
        'attributes': ResourceEntriesFetchAttributesToJSON(value['attributes']),
        'relationships': ResourceEntriesFetchRelationshipsToJSON(value['relationships']),
    };
}

