/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResourcesUsersRelationshipAwardsFetch
 */
export interface ResourcesUsersRelationshipAwardsFetch {
    /**
     * 
     * @type {string}
     * @memberof ResourcesUsersRelationshipAwardsFetch
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof ResourcesUsersRelationshipAwardsFetch
     */
    id: string;
}

/**
 * Check if a given object implements the ResourcesUsersRelationshipAwardsFetch interface.
 */
export function instanceOfResourcesUsersRelationshipAwardsFetch(value: object): value is ResourcesUsersRelationshipAwardsFetch {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ResourcesUsersRelationshipAwardsFetchFromJSON(json: any): ResourcesUsersRelationshipAwardsFetch {
    return ResourcesUsersRelationshipAwardsFetchFromJSONTyped(json, false);
}

export function ResourcesUsersRelationshipAwardsFetchFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourcesUsersRelationshipAwardsFetch {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
    };
}

export function ResourcesUsersRelationshipAwardsFetchToJSON(value?: ResourcesUsersRelationshipAwardsFetch | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'id': value['id'],
    };
}

