/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResourceAwardsFetch1Relationships } from './ResourceAwardsFetch1Relationships';
import {
    ResourceAwardsFetch1RelationshipsFromJSON,
    ResourceAwardsFetch1RelationshipsFromJSONTyped,
    ResourceAwardsFetch1RelationshipsToJSON,
} from './ResourceAwardsFetch1Relationships';
import type { ResourceAwardsFetch1Attributes } from './ResourceAwardsFetch1Attributes';
import {
    ResourceAwardsFetch1AttributesFromJSON,
    ResourceAwardsFetch1AttributesFromJSONTyped,
    ResourceAwardsFetch1AttributesToJSON,
} from './ResourceAwardsFetch1Attributes';

/**
 * 
 * @export
 * @interface ResourcesUserAwardsResourceFetch
 */
export interface ResourcesUserAwardsResourceFetch {
    /**
     * 
     * @type {string}
     * @memberof ResourcesUserAwardsResourceFetch
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof ResourcesUserAwardsResourceFetch
     */
    id: string;
    /**
     * 
     * @type {ResourceAwardsFetch1Attributes}
     * @memberof ResourcesUserAwardsResourceFetch
     */
    attributes: ResourceAwardsFetch1Attributes;
    /**
     * 
     * @type {ResourceAwardsFetch1Relationships}
     * @memberof ResourcesUserAwardsResourceFetch
     */
    relationships?: ResourceAwardsFetch1Relationships;
}

/**
 * Check if a given object implements the ResourcesUserAwardsResourceFetch interface.
 */
export function instanceOfResourcesUserAwardsResourceFetch(value: object): value is ResourcesUserAwardsResourceFetch {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('attributes' in value) || value['attributes'] === undefined) return false;
    return true;
}

export function ResourcesUserAwardsResourceFetchFromJSON(json: any): ResourcesUserAwardsResourceFetch {
    return ResourcesUserAwardsResourceFetchFromJSONTyped(json, false);
}

export function ResourcesUserAwardsResourceFetchFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourcesUserAwardsResourceFetch {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': ResourceAwardsFetch1AttributesFromJSON(json['attributes']),
        'relationships': json['relationships'] == null ? undefined : ResourceAwardsFetch1RelationshipsFromJSON(json['relationships']),
    };
}

export function ResourcesUserAwardsResourceFetchToJSON(value?: ResourcesUserAwardsResourceFetch | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'id': value['id'],
        'attributes': ResourceAwardsFetch1AttributesToJSON(value['attributes']),
        'relationships': ResourceAwardsFetch1RelationshipsToJSON(value['relationships']),
    };
}

