/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Game } from './Game';
import {
    GameFromJSON,
    GameFromJSONTyped,
    GameToJSON,
} from './Game';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';
import type { Achievement } from './Achievement';
import {
    AchievementFromJSON,
    AchievementFromJSONTyped,
    AchievementToJSON,
} from './Achievement';

/**
 * 
 * @export
 * @interface ResourcePlayerAchievementsFetchRelationships
 */
export interface ResourcePlayerAchievementsFetchRelationships {
    /**
     * 
     * @type {Achievement}
     * @memberof ResourcePlayerAchievementsFetchRelationships
     */
    achievement?: Achievement;
    /**
     * 
     * @type {User}
     * @memberof ResourcePlayerAchievementsFetchRelationships
     */
    user?: User;
    /**
     * 
     * @type {Game}
     * @memberof ResourcePlayerAchievementsFetchRelationships
     */
    game?: Game;
}

/**
 * Check if a given object implements the ResourcePlayerAchievementsFetchRelationships interface.
 */
export function instanceOfResourcePlayerAchievementsFetchRelationships(value: object): value is ResourcePlayerAchievementsFetchRelationships {
    return true;
}

export function ResourcePlayerAchievementsFetchRelationshipsFromJSON(json: any): ResourcePlayerAchievementsFetchRelationships {
    return ResourcePlayerAchievementsFetchRelationshipsFromJSONTyped(json, false);
}

export function ResourcePlayerAchievementsFetchRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourcePlayerAchievementsFetchRelationships {
    if (json == null) {
        return json;
    }
    return {
        
        'achievement': json['achievement'] == null ? undefined : AchievementFromJSON(json['achievement']),
        'user': json['user'] == null ? undefined : UserFromJSON(json['user']),
        'game': json['game'] == null ? undefined : GameFromJSON(json['game']),
    };
}

export function ResourcePlayerAchievementsFetchRelationshipsToJSON(value?: ResourcePlayerAchievementsFetchRelationships | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'achievement': AchievementToJSON(value['achievement']),
        'user': UserToJSON(value['user']),
        'game': GameToJSON(value['game']),
    };
}

