/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResourceTicketsFetchRelationships } from './ResourceTicketsFetchRelationships';
import {
    ResourceTicketsFetchRelationshipsFromJSON,
    ResourceTicketsFetchRelationshipsFromJSONTyped,
    ResourceTicketsFetchRelationshipsToJSON,
} from './ResourceTicketsFetchRelationships';
import type { ResourceTicketsFetchAttributes } from './ResourceTicketsFetchAttributes';
import {
    ResourceTicketsFetchAttributesFromJSON,
    ResourceTicketsFetchAttributesFromJSONTyped,
    ResourceTicketsFetchAttributesToJSON,
} from './ResourceTicketsFetchAttributes';

/**
 * 
 * @export
 * @interface ResourcesTicketsResourceFetch
 */
export interface ResourcesTicketsResourceFetch {
    /**
     * 
     * @type {string}
     * @memberof ResourcesTicketsResourceFetch
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof ResourcesTicketsResourceFetch
     */
    id: string;
    /**
     * 
     * @type {ResourceTicketsFetchAttributes}
     * @memberof ResourcesTicketsResourceFetch
     */
    attributes: ResourceTicketsFetchAttributes;
    /**
     * 
     * @type {ResourceTicketsFetchRelationships}
     * @memberof ResourcesTicketsResourceFetch
     */
    relationships?: ResourceTicketsFetchRelationships;
}

/**
 * Check if a given object implements the ResourcesTicketsResourceFetch interface.
 */
export function instanceOfResourcesTicketsResourceFetch(value: object): value is ResourcesTicketsResourceFetch {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('attributes' in value) || value['attributes'] === undefined) return false;
    return true;
}

export function ResourcesTicketsResourceFetchFromJSON(json: any): ResourcesTicketsResourceFetch {
    return ResourcesTicketsResourceFetchFromJSONTyped(json, false);
}

export function ResourcesTicketsResourceFetchFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourcesTicketsResourceFetch {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': ResourceTicketsFetchAttributesFromJSON(json['attributes']),
        'relationships': json['relationships'] == null ? undefined : ResourceTicketsFetchRelationshipsFromJSON(json['relationships']),
    };
}

export function ResourcesTicketsResourceFetchToJSON(value?: ResourcesTicketsResourceFetch | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'id': value['id'],
        'attributes': ResourceTicketsFetchAttributesToJSON(value['attributes']),
        'relationships': ResourceTicketsFetchRelationshipsToJSON(value['relationships']),
    };
}

