/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResourcesHubsResourceFetchAttributes } from './ResourcesHubsResourceFetchAttributes';
import {
    ResourcesHubsResourceFetchAttributesFromJSON,
    ResourcesHubsResourceFetchAttributesFromJSONTyped,
    ResourcesHubsResourceFetchAttributesToJSON,
} from './ResourcesHubsResourceFetchAttributes';
import type { ResourcesHubsResourceFetchRelationships } from './ResourcesHubsResourceFetchRelationships';
import {
    ResourcesHubsResourceFetchRelationshipsFromJSON,
    ResourcesHubsResourceFetchRelationshipsFromJSONTyped,
    ResourcesHubsResourceFetchRelationshipsToJSON,
} from './ResourcesHubsResourceFetchRelationships';

/**
 * 
 * @export
 * @interface ResourcesHubsResourceFetch
 */
export interface ResourcesHubsResourceFetch {
    /**
     * 
     * @type {string}
     * @memberof ResourcesHubsResourceFetch
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof ResourcesHubsResourceFetch
     */
    id: string;
    /**
     * 
     * @type {ResourcesHubsResourceFetchAttributes}
     * @memberof ResourcesHubsResourceFetch
     */
    attributes: ResourcesHubsResourceFetchAttributes;
    /**
     * 
     * @type {ResourcesHubsResourceFetchRelationships}
     * @memberof ResourcesHubsResourceFetch
     */
    relationships?: ResourcesHubsResourceFetchRelationships;
}

/**
 * Check if a given object implements the ResourcesHubsResourceFetch interface.
 */
export function instanceOfResourcesHubsResourceFetch(value: object): value is ResourcesHubsResourceFetch {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('attributes' in value) || value['attributes'] === undefined) return false;
    return true;
}

export function ResourcesHubsResourceFetchFromJSON(json: any): ResourcesHubsResourceFetch {
    return ResourcesHubsResourceFetchFromJSONTyped(json, false);
}

export function ResourcesHubsResourceFetchFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourcesHubsResourceFetch {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': ResourcesHubsResourceFetchAttributesFromJSON(json['attributes']),
        'relationships': json['relationships'] == null ? undefined : ResourcesHubsResourceFetchRelationshipsFromJSON(json['relationships']),
    };
}

export function ResourcesHubsResourceFetchToJSON(value?: ResourcesHubsResourceFetch | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'id': value['id'],
        'attributes': ResourcesHubsResourceFetchAttributesToJSON(value['attributes']),
        'relationships': ResourcesHubsResourceFetchRelationshipsToJSON(value['relationships']),
    };
}

