/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResourcesUsersRelationshipWallCommentsFetch
 */
export interface ResourcesUsersRelationshipWallCommentsFetch {
    /**
     * 
     * @type {string}
     * @memberof ResourcesUsersRelationshipWallCommentsFetch
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof ResourcesUsersRelationshipWallCommentsFetch
     */
    id: string;
}

/**
 * Check if a given object implements the ResourcesUsersRelationshipWallCommentsFetch interface.
 */
export function instanceOfResourcesUsersRelationshipWallCommentsFetch(value: object): value is ResourcesUsersRelationshipWallCommentsFetch {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ResourcesUsersRelationshipWallCommentsFetchFromJSON(json: any): ResourcesUsersRelationshipWallCommentsFetch {
    return ResourcesUsersRelationshipWallCommentsFetchFromJSONTyped(json, false);
}

export function ResourcesUsersRelationshipWallCommentsFetchFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourcesUsersRelationshipWallCommentsFetch {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
    };
}

export function ResourcesUsersRelationshipWallCommentsFetchToJSON(value?: ResourcesUsersRelationshipWallCommentsFetch | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'id': value['id'],
    };
}

