/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResourceAchievementSetVersionsFetchAttributes
 */
export interface ResourceAchievementSetVersionsFetchAttributes {
    /**
     * 
     * @type {number}
     * @memberof ResourceAchievementSetVersionsFetchAttributes
     */
    readonly version?: number;
    /**
     * 
     * @type {string}
     * @memberof ResourceAchievementSetVersionsFetchAttributes
     */
    readonly createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceAchievementSetVersionsFetchAttributes
     */
    readonly updatedAt?: string;
    /**
     * 
     * @type {number}
     * @memberof ResourceAchievementSetVersionsFetchAttributes
     */
    readonly playersTotal?: number;
    /**
     * 
     * @type {number}
     * @memberof ResourceAchievementSetVersionsFetchAttributes
     */
    readonly playersHardcore?: number;
    /**
     * 
     * @type {number}
     * @memberof ResourceAchievementSetVersionsFetchAttributes
     */
    readonly achievementsPublished?: number;
    /**
     * 
     * @type {number}
     * @memberof ResourceAchievementSetVersionsFetchAttributes
     */
    readonly achievementsUnpublished?: number;
    /**
     * 
     * @type {number}
     * @memberof ResourceAchievementSetVersionsFetchAttributes
     */
    readonly pointsTotal?: number;
    /**
     * 
     * @type {string}
     * @memberof ResourceAchievementSetVersionsFetchAttributes
     */
    readonly achievementSetId?: string;
}

/**
 * Check if a given object implements the ResourceAchievementSetVersionsFetchAttributes interface.
 */
export function instanceOfResourceAchievementSetVersionsFetchAttributes(value: object): value is ResourceAchievementSetVersionsFetchAttributes {
    return true;
}

export function ResourceAchievementSetVersionsFetchAttributesFromJSON(json: any): ResourceAchievementSetVersionsFetchAttributes {
    return ResourceAchievementSetVersionsFetchAttributesFromJSONTyped(json, false);
}

export function ResourceAchievementSetVersionsFetchAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceAchievementSetVersionsFetchAttributes {
    if (json == null) {
        return json;
    }
    return {
        
        'version': json['version'] == null ? undefined : json['version'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
        'playersTotal': json['playersTotal'] == null ? undefined : json['playersTotal'],
        'playersHardcore': json['playersHardcore'] == null ? undefined : json['playersHardcore'],
        'achievementsPublished': json['achievementsPublished'] == null ? undefined : json['achievementsPublished'],
        'achievementsUnpublished': json['achievementsUnpublished'] == null ? undefined : json['achievementsUnpublished'],
        'pointsTotal': json['pointsTotal'] == null ? undefined : json['pointsTotal'],
        'achievementSetId': json['achievementSetId'] == null ? undefined : json['achievementSetId'],
    };
}

export function ResourceAchievementSetVersionsFetchAttributesToJSON(value?: Omit<ResourceAchievementSetVersionsFetchAttributes, 'version'|'createdAt'|'updatedAt'|'playersTotal'|'playersHardcore'|'achievementsPublished'|'achievementsUnpublished'|'pointsTotal'|'achievementSetId'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
    };
}

