/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AchievementsIndex200ResponseJsonapi } from './AchievementsIndex200ResponseJsonapi';
import {
    AchievementsIndex200ResponseJsonapiFromJSON,
    AchievementsIndex200ResponseJsonapiFromJSONTyped,
    AchievementsIndex200ResponseJsonapiToJSON,
} from './AchievementsIndex200ResponseJsonapi';
import type { ResourcesSystemsResourceFetch } from './ResourcesSystemsResourceFetch';
import {
    ResourcesSystemsResourceFetchFromJSON,
    ResourcesSystemsResourceFetchFromJSONTyped,
    ResourcesSystemsResourceFetchToJSON,
} from './ResourcesSystemsResourceFetch';

/**
 * 
 * @export
 * @interface SystemsShow200Response
 */
export interface SystemsShow200Response {
    /**
     * 
     * @type {AchievementsIndex200ResponseJsonapi}
     * @memberof SystemsShow200Response
     */
    jsonapi: AchievementsIndex200ResponseJsonapi;
    /**
     * 
     * @type {ResourcesSystemsResourceFetch}
     * @memberof SystemsShow200Response
     */
    data: ResourcesSystemsResourceFetch;
}

/**
 * Check if a given object implements the SystemsShow200Response interface.
 */
export function instanceOfSystemsShow200Response(value: object): value is SystemsShow200Response {
    if (!('jsonapi' in value) || value['jsonapi'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function SystemsShow200ResponseFromJSON(json: any): SystemsShow200Response {
    return SystemsShow200ResponseFromJSONTyped(json, false);
}

export function SystemsShow200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemsShow200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonapi': AchievementsIndex200ResponseJsonapiFromJSON(json['jsonapi']),
        'data': ResourcesSystemsResourceFetchFromJSON(json['data']),
    };
}

export function SystemsShow200ResponseToJSON(value?: SystemsShow200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'jsonapi': AchievementsIndex200ResponseJsonapiToJSON(value['jsonapi']),
        'data': ResourcesSystemsResourceFetchToJSON(value['data']),
    };
}

