/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AchievementsIndex200ResponseJsonapi } from './AchievementsIndex200ResponseJsonapi';
import {
    AchievementsIndex200ResponseJsonapiFromJSON,
    AchievementsIndex200ResponseJsonapiFromJSONTyped,
    AchievementsIndex200ResponseJsonapiToJSON,
} from './AchievementsIndex200ResponseJsonapi';
import type { ResourcesSystemsResourceFetch } from './ResourcesSystemsResourceFetch';
import {
    ResourcesSystemsResourceFetchFromJSON,
    ResourcesSystemsResourceFetchFromJSONTyped,
    ResourcesSystemsResourceFetchToJSON,
} from './ResourcesSystemsResourceFetch';

/**
 * 
 * @export
 * @interface SystemsIndex200Response
 */
export interface SystemsIndex200Response {
    /**
     * 
     * @type {AchievementsIndex200ResponseJsonapi}
     * @memberof SystemsIndex200Response
     */
    jsonapi: AchievementsIndex200ResponseJsonapi;
    /**
     * 
     * @type {Array<ResourcesSystemsResourceFetch>}
     * @memberof SystemsIndex200Response
     */
    data: Array<ResourcesSystemsResourceFetch>;
}

/**
 * Check if a given object implements the SystemsIndex200Response interface.
 */
export function instanceOfSystemsIndex200Response(value: object): value is SystemsIndex200Response {
    if (!('jsonapi' in value) || value['jsonapi'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function SystemsIndex200ResponseFromJSON(json: any): SystemsIndex200Response {
    return SystemsIndex200ResponseFromJSONTyped(json, false);
}

export function SystemsIndex200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemsIndex200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonapi': AchievementsIndex200ResponseJsonapiFromJSON(json['jsonapi']),
        'data': ((json['data'] as Array<any>).map(ResourcesSystemsResourceFetchFromJSON)),
    };
}

export function SystemsIndex200ResponseToJSON(value?: SystemsIndex200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'jsonapi': AchievementsIndex200ResponseJsonapiToJSON(value['jsonapi']),
        'data': ((value['data'] as Array<any>).map(ResourcesSystemsResourceFetchToJSON)),
    };
}

