/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SystemLinks } from './SystemLinks';
import {
    SystemLinksFromJSON,
    SystemLinksFromJSONTyped,
    SystemLinksToJSON,
} from './SystemLinks';

/**
 * May include a list of IDs of relevant items in the `data` field. To retrieve these listed items as well, add "system" to the "include" query parameter; results will be found in `.included`.
 * @export
 * @interface System
 */
export interface System {
    /**
     * 
     * @type {SystemLinks}
     * @memberof System
     */
    links?: SystemLinks;
}

/**
 * Check if a given object implements the System interface.
 */
export function instanceOfSystem(value: object): value is System {
    return true;
}

export function SystemFromJSON(json: any): System {
    return SystemFromJSONTyped(json, false);
}

export function SystemFromJSONTyped(json: any, ignoreDiscriminator: boolean): System {
    if (json == null) {
        return json;
    }
    return {
        
        'links': json['links'] == null ? undefined : SystemLinksFromJSON(json['links']),
    };
}

export function SystemToJSON(value?: System | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'links': SystemLinksToJSON(value['links']),
    };
}

