/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Tickets1Links } from './Tickets1Links';
import {
    Tickets1LinksFromJSON,
    Tickets1LinksFromJSONTyped,
    Tickets1LinksToJSON,
} from './Tickets1Links';

/**
 * May include a list of IDs of relevant items in the `data` field. To retrieve these listed items as well, add "tickets" to the "include" query parameter; results will be found in `.included`.
 * @export
 * @interface Tickets1
 */
export interface Tickets1 {
    /**
     * 
     * @type {Tickets1Links}
     * @memberof Tickets1
     */
    links?: Tickets1Links;
}

/**
 * Check if a given object implements the Tickets1 interface.
 */
export function instanceOfTickets1(value: object): value is Tickets1 {
    return true;
}

export function Tickets1FromJSON(json: any): Tickets1 {
    return Tickets1FromJSONTyped(json, false);
}

export function Tickets1FromJSONTyped(json: any, ignoreDiscriminator: boolean): Tickets1 {
    if (json == null) {
        return json;
    }
    return {
        
        'links': json['links'] == null ? undefined : Tickets1LinksFromJSON(json['links']),
    };
}

export function Tickets1ToJSON(value?: Tickets1 | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'links': Tickets1LinksToJSON(value['links']),
    };
}

