/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TicketsLinks } from './TicketsLinks';
import {
    TicketsLinksFromJSON,
    TicketsLinksFromJSONTyped,
    TicketsLinksToJSON,
} from './TicketsLinks';

/**
 * May include a list of IDs of relevant items in the `data` field. To retrieve these listed items as well, add "tickets" to the "include" query parameter; results will be found in `.included`.
 * @export
 * @interface Tickets
 */
export interface Tickets {
    /**
     * 
     * @type {TicketsLinks}
     * @memberof Tickets
     */
    links?: TicketsLinks;
}

/**
 * Check if a given object implements the Tickets interface.
 */
export function instanceOfTickets(value: object): value is Tickets {
    return true;
}

export function TicketsFromJSON(json: any): Tickets {
    return TicketsFromJSONTyped(json, false);
}

export function TicketsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Tickets {
    if (json == null) {
        return json;
    }
    return {
        
        'links': json['links'] == null ? undefined : TicketsLinksFromJSON(json['links']),
    };
}

export function TicketsToJSON(value?: Tickets | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'links': TicketsLinksToJSON(value['links']),
    };
}

