/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResourceAuthorFetch } from './ResourceAuthorFetch';
import {
    ResourceAuthorFetchFromJSON,
    ResourceAuthorFetchFromJSONTyped,
    ResourceAuthorFetchToJSON,
} from './ResourceAuthorFetch';
import type { ResourceDeveloperFetchAttributes } from './ResourceDeveloperFetchAttributes';
import {
    ResourceDeveloperFetchAttributesFromJSON,
    ResourceDeveloperFetchAttributesFromJSONTyped,
    ResourceDeveloperFetchAttributesToJSON,
} from './ResourceDeveloperFetchAttributes';
import type { ResourceReporterFetch } from './ResourceReporterFetch';
import {
    ResourceReporterFetchFromJSON,
    ResourceReporterFetchFromJSONTyped,
    ResourceReporterFetchToJSON,
} from './ResourceReporterFetch';
import type { ResourceLeaderboardFetch } from './ResourceLeaderboardFetch';
import {
    ResourceLeaderboardFetchFromJSON,
    ResourceLeaderboardFetchFromJSONTyped,
    ResourceLeaderboardFetchToJSON,
} from './ResourceLeaderboardFetch';
import type { ResourceAchievementFetch } from './ResourceAchievementFetch';
import {
    ResourceAchievementFetchFromJSON,
    ResourceAchievementFetchFromJSONTyped,
    ResourceAchievementFetchToJSON,
} from './ResourceAchievementFetch';
import type { ResourceDeveloperFetchRelationships } from './ResourceDeveloperFetchRelationships';
import {
    ResourceDeveloperFetchRelationshipsFromJSON,
    ResourceDeveloperFetchRelationshipsFromJSONTyped,
    ResourceDeveloperFetchRelationshipsToJSON,
} from './ResourceDeveloperFetchRelationships';
import type { ResourceResolverFetch } from './ResourceResolverFetch';
import {
    ResourceResolverFetchFromJSON,
    ResourceResolverFetchFromJSONTyped,
    ResourceResolverFetchToJSON,
} from './ResourceResolverFetch';

/**
 * 
 * @export
 * @interface TicketsIndex200ResponseIncludedInner
 */
export interface TicketsIndex200ResponseIncludedInner {
    /**
     * 
     * @type {string}
     * @memberof TicketsIndex200ResponseIncludedInner
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof TicketsIndex200ResponseIncludedInner
     */
    id: string;
    /**
     * 
     * @type {ResourceDeveloperFetchAttributes}
     * @memberof TicketsIndex200ResponseIncludedInner
     */
    attributes: ResourceDeveloperFetchAttributes;
    /**
     * 
     * @type {ResourceDeveloperFetchRelationships}
     * @memberof TicketsIndex200ResponseIncludedInner
     */
    relationships?: ResourceDeveloperFetchRelationships;
}

/**
 * Check if a given object implements the TicketsIndex200ResponseIncludedInner interface.
 */
export function instanceOfTicketsIndex200ResponseIncludedInner(value: object): value is TicketsIndex200ResponseIncludedInner {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('attributes' in value) || value['attributes'] === undefined) return false;
    return true;
}

export function TicketsIndex200ResponseIncludedInnerFromJSON(json: any): TicketsIndex200ResponseIncludedInner {
    return TicketsIndex200ResponseIncludedInnerFromJSONTyped(json, false);
}

export function TicketsIndex200ResponseIncludedInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TicketsIndex200ResponseIncludedInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': ResourceDeveloperFetchAttributesFromJSON(json['attributes']),
        'relationships': json['relationships'] == null ? undefined : ResourceDeveloperFetchRelationshipsFromJSON(json['relationships']),
    };
}

export function TicketsIndex200ResponseIncludedInnerToJSON(value?: TicketsIndex200ResponseIncludedInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'id': value['id'],
        'attributes': ResourceDeveloperFetchAttributesToJSON(value['attributes']),
        'relationships': ResourceDeveloperFetchRelationshipsToJSON(value['relationships']),
    };
}

