/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AchievementsIndex200ResponseJsonapi } from './AchievementsIndex200ResponseJsonapi';
import {
    AchievementsIndex200ResponseJsonapiFromJSON,
    AchievementsIndex200ResponseJsonapiFromJSONTyped,
    AchievementsIndex200ResponseJsonapiToJSON,
} from './AchievementsIndex200ResponseJsonapi';
import type { ResourcesUsersRelationshipFollowingFetch } from './ResourcesUsersRelationshipFollowingFetch';
import {
    ResourcesUsersRelationshipFollowingFetchFromJSON,
    ResourcesUsersRelationshipFollowingFetchFromJSONTyped,
    ResourcesUsersRelationshipFollowingFetchToJSON,
} from './ResourcesUsersRelationshipFollowingFetch';

/**
 * 
 * @export
 * @interface UsersFollowingShow200Response
 */
export interface UsersFollowingShow200Response {
    /**
     * 
     * @type {AchievementsIndex200ResponseJsonapi}
     * @memberof UsersFollowingShow200Response
     */
    jsonapi: AchievementsIndex200ResponseJsonapi;
    /**
     * 
     * @type {Array<ResourcesUsersRelationshipFollowingFetch>}
     * @memberof UsersFollowingShow200Response
     */
    data: Array<ResourcesUsersRelationshipFollowingFetch>;
}

/**
 * Check if a given object implements the UsersFollowingShow200Response interface.
 */
export function instanceOfUsersFollowingShow200Response(value: object): value is UsersFollowingShow200Response {
    if (!('jsonapi' in value) || value['jsonapi'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function UsersFollowingShow200ResponseFromJSON(json: any): UsersFollowingShow200Response {
    return UsersFollowingShow200ResponseFromJSONTyped(json, false);
}

export function UsersFollowingShow200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersFollowingShow200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonapi': AchievementsIndex200ResponseJsonapiFromJSON(json['jsonapi']),
        'data': ((json['data'] as Array<any>).map(ResourcesUsersRelationshipFollowingFetchFromJSON)),
    };
}

export function UsersFollowingShow200ResponseToJSON(value?: UsersFollowingShow200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'jsonapi': AchievementsIndex200ResponseJsonapiToJSON(value['jsonapi']),
        'data': ((value['data'] as Array<any>).map(ResourcesUsersRelationshipFollowingFetchToJSON)),
    };
}

