/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AchievementsIndex200ResponseJsonapi } from './AchievementsIndex200ResponseJsonapi';
import {
    AchievementsIndex200ResponseJsonapiFromJSON,
    AchievementsIndex200ResponseJsonapiFromJSONTyped,
    AchievementsIndex200ResponseJsonapiToJSON,
} from './AchievementsIndex200ResponseJsonapi';
import type { UsersIndex200ResponseIncludedInner } from './UsersIndex200ResponseIncludedInner';
import {
    UsersIndex200ResponseIncludedInnerFromJSON,
    UsersIndex200ResponseIncludedInnerFromJSONTyped,
    UsersIndex200ResponseIncludedInnerToJSON,
} from './UsersIndex200ResponseIncludedInner';
import type { ResourcesUsersResourceFetch } from './ResourcesUsersResourceFetch';
import {
    ResourcesUsersResourceFetchFromJSON,
    ResourcesUsersResourceFetchFromJSONTyped,
    ResourcesUsersResourceFetchToJSON,
} from './ResourcesUsersResourceFetch';

/**
 * 
 * @export
 * @interface UsersIndex200Response
 */
export interface UsersIndex200Response {
    /**
     * 
     * @type {AchievementsIndex200ResponseJsonapi}
     * @memberof UsersIndex200Response
     */
    jsonapi: AchievementsIndex200ResponseJsonapi;
    /**
     * 
     * @type {Array<ResourcesUsersResourceFetch>}
     * @memberof UsersIndex200Response
     */
    data: Array<ResourcesUsersResourceFetch>;
    /**
     * 
     * @type {Array<UsersIndex200ResponseIncludedInner>}
     * @memberof UsersIndex200Response
     */
    included?: Array<UsersIndex200ResponseIncludedInner>;
}

/**
 * Check if a given object implements the UsersIndex200Response interface.
 */
export function instanceOfUsersIndex200Response(value: object): value is UsersIndex200Response {
    if (!('jsonapi' in value) || value['jsonapi'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function UsersIndex200ResponseFromJSON(json: any): UsersIndex200Response {
    return UsersIndex200ResponseFromJSONTyped(json, false);
}

export function UsersIndex200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersIndex200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonapi': AchievementsIndex200ResponseJsonapiFromJSON(json['jsonapi']),
        'data': ((json['data'] as Array<any>).map(ResourcesUsersResourceFetchFromJSON)),
        'included': json['included'] == null ? undefined : ((json['included'] as Array<any>).map(UsersIndex200ResponseIncludedInnerFromJSON)),
    };
}

export function UsersIndex200ResponseToJSON(value?: UsersIndex200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'jsonapi': AchievementsIndex200ResponseJsonapiToJSON(value['jsonapi']),
        'data': ((value['data'] as Array<any>).map(ResourcesUsersResourceFetchToJSON)),
        'included': value['included'] == null ? undefined : ((value['included'] as Array<any>).map(UsersIndex200ResponseIncludedInnerToJSON)),
    };
}

