/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User1Links } from './User1Links';
import {
    User1LinksFromJSON,
    User1LinksFromJSONTyped,
    User1LinksToJSON,
} from './User1Links';

/**
 * May include a list of IDs of relevant items in the `data` field. To retrieve these listed items as well, add "user" to the "include" query parameter; results will be found in `.included`.
 * @export
 * @interface User1
 */
export interface User1 {
    /**
     * 
     * @type {User1Links}
     * @memberof User1
     */
    links?: User1Links;
}

/**
 * Check if a given object implements the User1 interface.
 */
export function instanceOfUser1(value: object): value is User1 {
    return true;
}

export function User1FromJSON(json: any): User1 {
    return User1FromJSONTyped(json, false);
}

export function User1FromJSONTyped(json: any, ignoreDiscriminator: boolean): User1 {
    if (json == null) {
        return json;
    }
    return {
        
        'links': json['links'] == null ? undefined : User1LinksFromJSON(json['links']),
    };
}

export function User1ToJSON(value?: User1 | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'links': User1LinksToJSON(value['links']),
    };
}

