/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResourcePlayerAchievementsFetch } from './ResourcePlayerAchievementsFetch';
import {
    ResourcePlayerAchievementsFetchFromJSON,
    ResourcePlayerAchievementsFetchFromJSONTyped,
    ResourcePlayerAchievementsFetchToJSON,
} from './ResourcePlayerAchievementsFetch';
import type { ResourceFollowersFetchRelationships } from './ResourceFollowersFetchRelationships';
import {
    ResourceFollowersFetchRelationshipsFromJSON,
    ResourceFollowersFetchRelationshipsFromJSONTyped,
    ResourceFollowersFetchRelationshipsToJSON,
} from './ResourceFollowersFetchRelationships';
import type { ResourceFollowersFetchAttributes } from './ResourceFollowersFetchAttributes';
import {
    ResourceFollowersFetchAttributesFromJSON,
    ResourceFollowersFetchAttributesFromJSONTyped,
    ResourceFollowersFetchAttributesToJSON,
} from './ResourceFollowersFetchAttributes';
import type { ResourceWallCommentsFetch } from './ResourceWallCommentsFetch';
import {
    ResourceWallCommentsFetchFromJSON,
    ResourceWallCommentsFetchFromJSONTyped,
    ResourceWallCommentsFetchToJSON,
} from './ResourceWallCommentsFetch';
import type { ResourceFollowersFetch } from './ResourceFollowersFetch';
import {
    ResourceFollowersFetchFromJSON,
    ResourceFollowersFetchFromJSONTyped,
    ResourceFollowersFetchToJSON,
} from './ResourceFollowersFetch';
import type { ResourcePlayerGamesFetch } from './ResourcePlayerGamesFetch';
import {
    ResourcePlayerGamesFetchFromJSON,
    ResourcePlayerGamesFetchFromJSONTyped,
    ResourcePlayerGamesFetchToJSON,
} from './ResourcePlayerGamesFetch';
import type { ResourcePlayerAchievementSetsFetch } from './ResourcePlayerAchievementSetsFetch';
import {
    ResourcePlayerAchievementSetsFetchFromJSON,
    ResourcePlayerAchievementSetsFetchFromJSONTyped,
    ResourcePlayerAchievementSetsFetchToJSON,
} from './ResourcePlayerAchievementSetsFetch';
import type { ResourceFollowingFetch } from './ResourceFollowingFetch';
import {
    ResourceFollowingFetchFromJSON,
    ResourceFollowingFetchFromJSONTyped,
    ResourceFollowingFetchToJSON,
} from './ResourceFollowingFetch';
import type { ResourceAchievementSetClaimsFetch } from './ResourceAchievementSetClaimsFetch';
import {
    ResourceAchievementSetClaimsFetchFromJSON,
    ResourceAchievementSetClaimsFetchFromJSONTyped,
    ResourceAchievementSetClaimsFetchToJSON,
} from './ResourceAchievementSetClaimsFetch';
import type { ResourceAwardsFetch1 } from './ResourceAwardsFetch1';
import {
    ResourceAwardsFetch1FromJSON,
    ResourceAwardsFetch1FromJSONTyped,
    ResourceAwardsFetch1ToJSON,
} from './ResourceAwardsFetch1';
import type { ResourceTicketsFetch } from './ResourceTicketsFetch';
import {
    ResourceTicketsFetchFromJSON,
    ResourceTicketsFetchFromJSONTyped,
    ResourceTicketsFetchToJSON,
} from './ResourceTicketsFetch';

/**
 * 
 * @export
 * @interface UsersIndex200ResponseIncludedInner
 */
export interface UsersIndex200ResponseIncludedInner {
    /**
     * 
     * @type {string}
     * @memberof UsersIndex200ResponseIncludedInner
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof UsersIndex200ResponseIncludedInner
     */
    id: string;
    /**
     * 
     * @type {ResourceFollowersFetchAttributes}
     * @memberof UsersIndex200ResponseIncludedInner
     */
    attributes: ResourceFollowersFetchAttributes;
    /**
     * 
     * @type {ResourceFollowersFetchRelationships}
     * @memberof UsersIndex200ResponseIncludedInner
     */
    relationships?: ResourceFollowersFetchRelationships;
}

/**
 * Check if a given object implements the UsersIndex200ResponseIncludedInner interface.
 */
export function instanceOfUsersIndex200ResponseIncludedInner(value: object): value is UsersIndex200ResponseIncludedInner {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('attributes' in value) || value['attributes'] === undefined) return false;
    return true;
}

export function UsersIndex200ResponseIncludedInnerFromJSON(json: any): UsersIndex200ResponseIncludedInner {
    return UsersIndex200ResponseIncludedInnerFromJSONTyped(json, false);
}

export function UsersIndex200ResponseIncludedInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersIndex200ResponseIncludedInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': ResourceFollowersFetchAttributesFromJSON(json['attributes']),
        'relationships': json['relationships'] == null ? undefined : ResourceFollowersFetchRelationshipsFromJSON(json['relationships']),
    };
}

export function UsersIndex200ResponseIncludedInnerToJSON(value?: UsersIndex200ResponseIncludedInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'id': value['id'],
        'attributes': ResourceFollowersFetchAttributesToJSON(value['attributes']),
        'relationships': ResourceFollowersFetchRelationshipsToJSON(value['relationships']),
    };
}

