/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResourcesUsersRelationshipAwardsFetch } from './ResourcesUsersRelationshipAwardsFetch';
import {
    ResourcesUsersRelationshipAwardsFetchFromJSON,
    ResourcesUsersRelationshipAwardsFetchFromJSONTyped,
    ResourcesUsersRelationshipAwardsFetchToJSON,
} from './ResourcesUsersRelationshipAwardsFetch';
import type { AchievementsIndex200ResponseJsonapi } from './AchievementsIndex200ResponseJsonapi';
import {
    AchievementsIndex200ResponseJsonapiFromJSON,
    AchievementsIndex200ResponseJsonapiFromJSONTyped,
    AchievementsIndex200ResponseJsonapiToJSON,
} from './AchievementsIndex200ResponseJsonapi';

/**
 * 
 * @export
 * @interface UsersAwardsShow200Response
 */
export interface UsersAwardsShow200Response {
    /**
     * 
     * @type {AchievementsIndex200ResponseJsonapi}
     * @memberof UsersAwardsShow200Response
     */
    jsonapi: AchievementsIndex200ResponseJsonapi;
    /**
     * 
     * @type {Array<ResourcesUsersRelationshipAwardsFetch>}
     * @memberof UsersAwardsShow200Response
     */
    data: Array<ResourcesUsersRelationshipAwardsFetch>;
}

/**
 * Check if a given object implements the UsersAwardsShow200Response interface.
 */
export function instanceOfUsersAwardsShow200Response(value: object): value is UsersAwardsShow200Response {
    if (!('jsonapi' in value) || value['jsonapi'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function UsersAwardsShow200ResponseFromJSON(json: any): UsersAwardsShow200Response {
    return UsersAwardsShow200ResponseFromJSONTyped(json, false);
}

export function UsersAwardsShow200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersAwardsShow200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonapi': AchievementsIndex200ResponseJsonapiFromJSON(json['jsonapi']),
        'data': ((json['data'] as Array<any>).map(ResourcesUsersRelationshipAwardsFetchFromJSON)),
    };
}

export function UsersAwardsShow200ResponseToJSON(value?: UsersAwardsShow200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'jsonapi': AchievementsIndex200ResponseJsonapiToJSON(value['jsonapi']),
        'data': ((value['data'] as Array<any>).map(ResourcesUsersRelationshipAwardsFetchToJSON)),
    };
}

