/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResourcesUsersRelationshipPlayerAchievementsFetch } from './ResourcesUsersRelationshipPlayerAchievementsFetch';
import {
    ResourcesUsersRelationshipPlayerAchievementsFetchFromJSON,
    ResourcesUsersRelationshipPlayerAchievementsFetchFromJSONTyped,
    ResourcesUsersRelationshipPlayerAchievementsFetchToJSON,
} from './ResourcesUsersRelationshipPlayerAchievementsFetch';
import type { AchievementsIndex200ResponseJsonapi } from './AchievementsIndex200ResponseJsonapi';
import {
    AchievementsIndex200ResponseJsonapiFromJSON,
    AchievementsIndex200ResponseJsonapiFromJSONTyped,
    AchievementsIndex200ResponseJsonapiToJSON,
} from './AchievementsIndex200ResponseJsonapi';

/**
 * 
 * @export
 * @interface UsersPlayerAchievementsShow200Response
 */
export interface UsersPlayerAchievementsShow200Response {
    /**
     * 
     * @type {AchievementsIndex200ResponseJsonapi}
     * @memberof UsersPlayerAchievementsShow200Response
     */
    jsonapi: AchievementsIndex200ResponseJsonapi;
    /**
     * 
     * @type {Array<ResourcesUsersRelationshipPlayerAchievementsFetch>}
     * @memberof UsersPlayerAchievementsShow200Response
     */
    data: Array<ResourcesUsersRelationshipPlayerAchievementsFetch>;
}

/**
 * Check if a given object implements the UsersPlayerAchievementsShow200Response interface.
 */
export function instanceOfUsersPlayerAchievementsShow200Response(value: object): value is UsersPlayerAchievementsShow200Response {
    if (!('jsonapi' in value) || value['jsonapi'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function UsersPlayerAchievementsShow200ResponseFromJSON(json: any): UsersPlayerAchievementsShow200Response {
    return UsersPlayerAchievementsShow200ResponseFromJSONTyped(json, false);
}

export function UsersPlayerAchievementsShow200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersPlayerAchievementsShow200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonapi': AchievementsIndex200ResponseJsonapiFromJSON(json['jsonapi']),
        'data': ((json['data'] as Array<any>).map(ResourcesUsersRelationshipPlayerAchievementsFetchFromJSON)),
    };
}

export function UsersPlayerAchievementsShow200ResponseToJSON(value?: UsersPlayerAchievementsShow200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'jsonapi': AchievementsIndex200ResponseJsonapiToJSON(value['jsonapi']),
        'data': ((value['data'] as Array<any>).map(ResourcesUsersRelationshipPlayerAchievementsFetchToJSON)),
    };
}

