/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AchievementsIndex200ResponseJsonapi } from './AchievementsIndex200ResponseJsonapi';
import {
    AchievementsIndex200ResponseJsonapiFromJSON,
    AchievementsIndex200ResponseJsonapiFromJSONTyped,
    AchievementsIndex200ResponseJsonapiToJSON,
} from './AchievementsIndex200ResponseJsonapi';
import type { ResourcesUsersRelationshipFollowersFetch } from './ResourcesUsersRelationshipFollowersFetch';
import {
    ResourcesUsersRelationshipFollowersFetchFromJSON,
    ResourcesUsersRelationshipFollowersFetchFromJSONTyped,
    ResourcesUsersRelationshipFollowersFetchToJSON,
} from './ResourcesUsersRelationshipFollowersFetch';

/**
 * 
 * @export
 * @interface UsersFollowersShow200Response
 */
export interface UsersFollowersShow200Response {
    /**
     * 
     * @type {AchievementsIndex200ResponseJsonapi}
     * @memberof UsersFollowersShow200Response
     */
    jsonapi: AchievementsIndex200ResponseJsonapi;
    /**
     * 
     * @type {Array<ResourcesUsersRelationshipFollowersFetch>}
     * @memberof UsersFollowersShow200Response
     */
    data: Array<ResourcesUsersRelationshipFollowersFetch>;
}

/**
 * Check if a given object implements the UsersFollowersShow200Response interface.
 */
export function instanceOfUsersFollowersShow200Response(value: object): value is UsersFollowersShow200Response {
    if (!('jsonapi' in value) || value['jsonapi'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function UsersFollowersShow200ResponseFromJSON(json: any): UsersFollowersShow200Response {
    return UsersFollowersShow200ResponseFromJSONTyped(json, false);
}

export function UsersFollowersShow200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersFollowersShow200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonapi': AchievementsIndex200ResponseJsonapiFromJSON(json['jsonapi']),
        'data': ((json['data'] as Array<any>).map(ResourcesUsersRelationshipFollowersFetchFromJSON)),
    };
}

export function UsersFollowersShow200ResponseToJSON(value?: UsersFollowersShow200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'jsonapi': AchievementsIndex200ResponseJsonapiToJSON(value['jsonapi']),
        'data': ((value['data'] as Array<any>).map(ResourcesUsersRelationshipFollowersFetchToJSON)),
    };
}

