/* tslint:disable */
/* eslint-disable */
/**
 * RetroAchievements
 * JSON:API built using Laravel
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WallCommentsLinks
 */
export interface WallCommentsLinks {
    /**
     * 
     * @type {string}
     * @memberof WallCommentsLinks
     */
    related?: string;
    /**
     * 
     * @type {string}
     * @memberof WallCommentsLinks
     */
    self?: string;
}

/**
 * Check if a given object implements the WallCommentsLinks interface.
 */
export function instanceOfWallCommentsLinks(value: object): value is WallCommentsLinks {
    return true;
}

export function WallCommentsLinksFromJSON(json: any): WallCommentsLinks {
    return WallCommentsLinksFromJSONTyped(json, false);
}

export function WallCommentsLinksFromJSONTyped(json: any, ignoreDiscriminator: boolean): WallCommentsLinks {
    if (json == null) {
        return json;
    }
    return {
        
        'related': json['related'] == null ? undefined : json['related'],
        'self': json['self'] == null ? undefined : json['self'],
    };
}

export function WallCommentsLinksToJSON(value?: WallCommentsLinks | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'related': value['related'],
        'self': value['self'],
    };
}

